// Code generated by MockGen. DO NOT EDIT.
// Source: ./repo (interfaces: DepositsRepo)
//
// Generated by this command:
//
//	mockgen -destination repo/mocks/repo.go -package mocks ./repo DepositsRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sqlc "github.com/MountainHubTech/rvpay-go/deposits/db/sqlc"
	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockDepositsRepo is a mock of DepositsRepo interface.
type MockDepositsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDepositsRepoMockRecorder
	isgomock struct{}
}

// MockDepositsRepoMockRecorder is the mock recorder for MockDepositsRepo.
type MockDepositsRepoMockRecorder struct {
	mock *MockDepositsRepo
}

// NewMockDepositsRepo creates a new mock instance.
func NewMockDepositsRepo(ctrl *gomock.Controller) *MockDepositsRepo {
	mock := &MockDepositsRepo{ctrl: ctrl}
	mock.recorder = &MockDepositsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepositsRepo) EXPECT() *MockDepositsRepoMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockDepositsRepo) Begin(ctx context.Context) (sqlc.Querier, pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(sqlc.Querier)
	ret1, _ := ret[1].(pgx.Tx)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Begin indicates an expected call of Begin.
func (mr *MockDepositsRepoMockRecorder) Begin(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockDepositsRepo)(nil).Begin), ctx)
}

// Do mocks base method.
func (m *MockDepositsRepo) Do() sqlc.Querier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do")
	ret0, _ := ret[0].(sqlc.Querier)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockDepositsRepoMockRecorder) Do() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockDepositsRepo)(nil).Do))
}
