// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deposits.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDeposit = `-- name: CreateDeposit :one
INSERT INTO deposits (
    client_name,
    customer_id,
    merchant_id,
    amount,
    currency,
    payment_type,
    payer_phone_number,
    provider,
    status,
    idempotency_key,
    ghl_transaction_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, client_name, customer_id, merchant_id, amount, currency, payment_type, payer_phone_number, provider, status, external_reference, idempotency_key, initiated_at, completed_at, failed_at, failure_reason, created_at, updated_at, ghl_transaction_id, ghl_charge_id
`

type CreateDepositParams struct {
	ClientName       string          `json:"client_name"`
	CustomerID       *string         `json:"customer_id"`
	MerchantID       *string         `json:"merchant_id"`
	Amount           pgtype.Numeric  `json:"amount"`
	Currency         string          `json:"currency"`
	PaymentType      PaymentType     `json:"payment_type"`
	PayerPhoneNumber string          `json:"payer_phone_number"`
	Provider         PaymentProvider `json:"provider"`
	Status           DepositStatus   `json:"status"`
	IdempotencyKey   uuid.UUID       `json:"idempotency_key"`
	GhlTransactionID *string         `json:"ghl_transaction_id"`
}

func (q *Queries) CreateDeposit(ctx context.Context, arg CreateDepositParams) (Deposit, error) {
	row := q.db.QueryRow(ctx, createDeposit,
		arg.ClientName,
		arg.CustomerID,
		arg.MerchantID,
		arg.Amount,
		arg.Currency,
		arg.PaymentType,
		arg.PayerPhoneNumber,
		arg.Provider,
		arg.Status,
		arg.IdempotencyKey,
		arg.GhlTransactionID,
	)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.CustomerID,
		&i.MerchantID,
		&i.Amount,
		&i.Currency,
		&i.PaymentType,
		&i.PayerPhoneNumber,
		&i.Provider,
		&i.Status,
		&i.ExternalReference,
		&i.IdempotencyKey,
		&i.InitiatedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GhlTransactionID,
		&i.GhlChargeID,
	)
	return i, err
}

const getDepositByExternalReference = `-- name: GetDepositByExternalReference :one
SELECT id, client_name, customer_id, merchant_id, amount, currency, payment_type, payer_phone_number, provider, status, external_reference, idempotency_key, initiated_at, completed_at, failed_at, failure_reason, created_at, updated_at, ghl_transaction_id, ghl_charge_id FROM deposits WHERE external_reference = $1
`

func (q *Queries) GetDepositByExternalReference(ctx context.Context, externalReference *string) (Deposit, error) {
	row := q.db.QueryRow(ctx, getDepositByExternalReference, externalReference)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.CustomerID,
		&i.MerchantID,
		&i.Amount,
		&i.Currency,
		&i.PaymentType,
		&i.PayerPhoneNumber,
		&i.Provider,
		&i.Status,
		&i.ExternalReference,
		&i.IdempotencyKey,
		&i.InitiatedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GhlTransactionID,
		&i.GhlChargeID,
	)
	return i, err
}

const getDepositByGHLChargeID = `-- name: GetDepositByGHLChargeID :one
SELECT id, client_name, customer_id, merchant_id, amount, currency, payment_type, payer_phone_number, provider, status, external_reference, idempotency_key, initiated_at, completed_at, failed_at, failure_reason, created_at, updated_at, ghl_transaction_id, ghl_charge_id FROM deposits WHERE ghl_charge_id = $1
`

func (q *Queries) GetDepositByGHLChargeID(ctx context.Context, ghlChargeID *string) (Deposit, error) {
	row := q.db.QueryRow(ctx, getDepositByGHLChargeID, ghlChargeID)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.CustomerID,
		&i.MerchantID,
		&i.Amount,
		&i.Currency,
		&i.PaymentType,
		&i.PayerPhoneNumber,
		&i.Provider,
		&i.Status,
		&i.ExternalReference,
		&i.IdempotencyKey,
		&i.InitiatedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GhlTransactionID,
		&i.GhlChargeID,
	)
	return i, err
}

const getDepositByGHLTransactionID = `-- name: GetDepositByGHLTransactionID :one
SELECT id, client_name, customer_id, merchant_id, amount, currency, payment_type, payer_phone_number, provider, status, external_reference, idempotency_key, initiated_at, completed_at, failed_at, failure_reason, created_at, updated_at, ghl_transaction_id, ghl_charge_id FROM deposits WHERE ghl_transaction_id = $1
`

func (q *Queries) GetDepositByGHLTransactionID(ctx context.Context, ghlTransactionID *string) (Deposit, error) {
	row := q.db.QueryRow(ctx, getDepositByGHLTransactionID, ghlTransactionID)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.CustomerID,
		&i.MerchantID,
		&i.Amount,
		&i.Currency,
		&i.PaymentType,
		&i.PayerPhoneNumber,
		&i.Provider,
		&i.Status,
		&i.ExternalReference,
		&i.IdempotencyKey,
		&i.InitiatedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GhlTransactionID,
		&i.GhlChargeID,
	)
	return i, err
}

const getDepositByID = `-- name: GetDepositByID :one
SELECT id, client_name, customer_id, merchant_id, amount, currency, payment_type, payer_phone_number, provider, status, external_reference, idempotency_key, initiated_at, completed_at, failed_at, failure_reason, created_at, updated_at, ghl_transaction_id, ghl_charge_id FROM deposits WHERE id = $1
`

func (q *Queries) GetDepositByID(ctx context.Context, id uuid.UUID) (Deposit, error) {
	row := q.db.QueryRow(ctx, getDepositByID, id)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.CustomerID,
		&i.MerchantID,
		&i.Amount,
		&i.Currency,
		&i.PaymentType,
		&i.PayerPhoneNumber,
		&i.Provider,
		&i.Status,
		&i.ExternalReference,
		&i.IdempotencyKey,
		&i.InitiatedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GhlTransactionID,
		&i.GhlChargeID,
	)
	return i, err
}

const getDepositByIdempotencyKey = `-- name: GetDepositByIdempotencyKey :one
SELECT id, client_name, customer_id, merchant_id, amount, currency, payment_type, payer_phone_number, provider, status, external_reference, idempotency_key, initiated_at, completed_at, failed_at, failure_reason, created_at, updated_at, ghl_transaction_id, ghl_charge_id FROM deposits WHERE idempotency_key = $1
`

func (q *Queries) GetDepositByIdempotencyKey(ctx context.Context, idempotencyKey uuid.UUID) (Deposit, error) {
	row := q.db.QueryRow(ctx, getDepositByIdempotencyKey, idempotencyKey)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.CustomerID,
		&i.MerchantID,
		&i.Amount,
		&i.Currency,
		&i.PaymentType,
		&i.PayerPhoneNumber,
		&i.Provider,
		&i.Status,
		&i.ExternalReference,
		&i.IdempotencyKey,
		&i.InitiatedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GhlTransactionID,
		&i.GhlChargeID,
	)
	return i, err
}

const listDepositsByClient = `-- name: ListDepositsByClient :many
SELECT id, client_name, customer_id, merchant_id, amount, currency, payment_type, payer_phone_number, provider, status, external_reference, idempotency_key, initiated_at, completed_at, failed_at, failure_reason, created_at, updated_at, ghl_transaction_id, ghl_charge_id FROM deposits
WHERE client_name = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDepositsByClient(ctx context.Context, clientName string) ([]Deposit, error) {
	rows, err := q.db.Query(ctx, listDepositsByClient, clientName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deposit{}
	for rows.Next() {
		var i Deposit
		if err := rows.Scan(
			&i.ID,
			&i.ClientName,
			&i.CustomerID,
			&i.MerchantID,
			&i.Amount,
			&i.Currency,
			&i.PaymentType,
			&i.PayerPhoneNumber,
			&i.Provider,
			&i.Status,
			&i.ExternalReference,
			&i.IdempotencyKey,
			&i.InitiatedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GhlTransactionID,
			&i.GhlChargeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepositsByCustomer = `-- name: ListDepositsByCustomer :many
SELECT id, client_name, customer_id, merchant_id, amount, currency, payment_type, payer_phone_number, provider, status, external_reference, idempotency_key, initiated_at, completed_at, failed_at, failure_reason, created_at, updated_at, ghl_transaction_id, ghl_charge_id FROM deposits
WHERE customer_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDepositsByCustomer(ctx context.Context, customerID *string) ([]Deposit, error) {
	rows, err := q.db.Query(ctx, listDepositsByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deposit{}
	for rows.Next() {
		var i Deposit
		if err := rows.Scan(
			&i.ID,
			&i.ClientName,
			&i.CustomerID,
			&i.MerchantID,
			&i.Amount,
			&i.Currency,
			&i.PaymentType,
			&i.PayerPhoneNumber,
			&i.Provider,
			&i.Status,
			&i.ExternalReference,
			&i.IdempotencyKey,
			&i.InitiatedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GhlTransactionID,
			&i.GhlChargeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepositsByMerchant = `-- name: ListDepositsByMerchant :many
SELECT id, client_name, customer_id, merchant_id, amount, currency, payment_type, payer_phone_number, provider, status, external_reference, idempotency_key, initiated_at, completed_at, failed_at, failure_reason, created_at, updated_at, ghl_transaction_id, ghl_charge_id FROM deposits
WHERE merchant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDepositsByMerchant(ctx context.Context, merchantID *string) ([]Deposit, error) {
	rows, err := q.db.Query(ctx, listDepositsByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deposit{}
	for rows.Next() {
		var i Deposit
		if err := rows.Scan(
			&i.ID,
			&i.ClientName,
			&i.CustomerID,
			&i.MerchantID,
			&i.Amount,
			&i.Currency,
			&i.PaymentType,
			&i.PayerPhoneNumber,
			&i.Provider,
			&i.Status,
			&i.ExternalReference,
			&i.IdempotencyKey,
			&i.InitiatedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GhlTransactionID,
			&i.GhlChargeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepositsByStatus = `-- name: ListDepositsByStatus :many
SELECT id, client_name, customer_id, merchant_id, amount, currency, payment_type, payer_phone_number, provider, status, external_reference, idempotency_key, initiated_at, completed_at, failed_at, failure_reason, created_at, updated_at, ghl_transaction_id, ghl_charge_id FROM deposits
WHERE status = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDepositsByStatus(ctx context.Context, status DepositStatus) ([]Deposit, error) {
	rows, err := q.db.Query(ctx, listDepositsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deposit{}
	for rows.Next() {
		var i Deposit
		if err := rows.Scan(
			&i.ID,
			&i.ClientName,
			&i.CustomerID,
			&i.MerchantID,
			&i.Amount,
			&i.Currency,
			&i.PaymentType,
			&i.PayerPhoneNumber,
			&i.Provider,
			&i.Status,
			&i.ExternalReference,
			&i.IdempotencyKey,
			&i.InitiatedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GhlTransactionID,
			&i.GhlChargeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDepositExternalReference = `-- name: UpdateDepositExternalReference :exec
UPDATE deposits
SET external_reference = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateDepositExternalReferenceParams struct {
	ID                uuid.UUID `json:"id"`
	ExternalReference *string   `json:"external_reference"`
}

func (q *Queries) UpdateDepositExternalReference(ctx context.Context, arg UpdateDepositExternalReferenceParams) error {
	_, err := q.db.Exec(ctx, updateDepositExternalReference, arg.ID, arg.ExternalReference)
	return err
}

const updateDepositGHLReference = `-- name: UpdateDepositGHLReference :one
UPDATE deposits
SET ghl_transaction_id = $2,
    ghl_charge_id = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, client_name, customer_id, merchant_id, amount, currency, payment_type, payer_phone_number, provider, status, external_reference, idempotency_key, initiated_at, completed_at, failed_at, failure_reason, created_at, updated_at, ghl_transaction_id, ghl_charge_id
`

type UpdateDepositGHLReferenceParams struct {
	ID               uuid.UUID `json:"id"`
	GhlTransactionID *string   `json:"ghl_transaction_id"`
	GhlChargeID      *string   `json:"ghl_charge_id"`
}

func (q *Queries) UpdateDepositGHLReference(ctx context.Context, arg UpdateDepositGHLReferenceParams) (Deposit, error) {
	row := q.db.QueryRow(ctx, updateDepositGHLReference, arg.ID, arg.GhlTransactionID, arg.GhlChargeID)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.CustomerID,
		&i.MerchantID,
		&i.Amount,
		&i.Currency,
		&i.PaymentType,
		&i.PayerPhoneNumber,
		&i.Provider,
		&i.Status,
		&i.ExternalReference,
		&i.IdempotencyKey,
		&i.InitiatedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GhlTransactionID,
		&i.GhlChargeID,
	)
	return i, err
}

const updateDepositStatus = `-- name: UpdateDepositStatus :one
UPDATE deposits
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, client_name, customer_id, merchant_id, amount, currency, payment_type, payer_phone_number, provider, status, external_reference, idempotency_key, initiated_at, completed_at, failed_at, failure_reason, created_at, updated_at, ghl_transaction_id, ghl_charge_id
`

type UpdateDepositStatusParams struct {
	ID     uuid.UUID     `json:"id"`
	Status DepositStatus `json:"status"`
}

func (q *Queries) UpdateDepositStatus(ctx context.Context, arg UpdateDepositStatusParams) (Deposit, error) {
	row := q.db.QueryRow(ctx, updateDepositStatus, arg.ID, arg.Status)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.CustomerID,
		&i.MerchantID,
		&i.Amount,
		&i.Currency,
		&i.PaymentType,
		&i.PayerPhoneNumber,
		&i.Provider,
		&i.Status,
		&i.ExternalReference,
		&i.IdempotencyKey,
		&i.InitiatedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GhlTransactionID,
		&i.GhlChargeID,
	)
	return i, err
}

const updateDepositStatusAndCompletedAt = `-- name: UpdateDepositStatusAndCompletedAt :one
UPDATE deposits
SET status = $2,
    completed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, client_name, customer_id, merchant_id, amount, currency, payment_type, payer_phone_number, provider, status, external_reference, idempotency_key, initiated_at, completed_at, failed_at, failure_reason, created_at, updated_at, ghl_transaction_id, ghl_charge_id
`

type UpdateDepositStatusAndCompletedAtParams struct {
	ID     uuid.UUID     `json:"id"`
	Status DepositStatus `json:"status"`
}

func (q *Queries) UpdateDepositStatusAndCompletedAt(ctx context.Context, arg UpdateDepositStatusAndCompletedAtParams) (Deposit, error) {
	row := q.db.QueryRow(ctx, updateDepositStatusAndCompletedAt, arg.ID, arg.Status)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.CustomerID,
		&i.MerchantID,
		&i.Amount,
		&i.Currency,
		&i.PaymentType,
		&i.PayerPhoneNumber,
		&i.Provider,
		&i.Status,
		&i.ExternalReference,
		&i.IdempotencyKey,
		&i.InitiatedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GhlTransactionID,
		&i.GhlChargeID,
	)
	return i, err
}

const updateDepositStatusAndFailedAt = `-- name: UpdateDepositStatusAndFailedAt :one
UPDATE deposits
SET status = $2,
    failed_at = NOW(),
    failure_reason = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, client_name, customer_id, merchant_id, amount, currency, payment_type, payer_phone_number, provider, status, external_reference, idempotency_key, initiated_at, completed_at, failed_at, failure_reason, created_at, updated_at, ghl_transaction_id, ghl_charge_id
`

type UpdateDepositStatusAndFailedAtParams struct {
	ID            uuid.UUID     `json:"id"`
	Status        DepositStatus `json:"status"`
	FailureReason *string       `json:"failure_reason"`
}

func (q *Queries) UpdateDepositStatusAndFailedAt(ctx context.Context, arg UpdateDepositStatusAndFailedAtParams) (Deposit, error) {
	row := q.db.QueryRow(ctx, updateDepositStatusAndFailedAt, arg.ID, arg.Status, arg.FailureReason)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.CustomerID,
		&i.MerchantID,
		&i.Amount,
		&i.Currency,
		&i.PaymentType,
		&i.PayerPhoneNumber,
		&i.Provider,
		&i.Status,
		&i.ExternalReference,
		&i.IdempotencyKey,
		&i.InitiatedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GhlTransactionID,
		&i.GhlChargeID,
	)
	return i, err
}
