// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: payment_events.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const claimDuePaymentEvents = `-- name: ClaimDuePaymentEvents :many
UPDATE payment_events AS pe
SET attempts = pe.attempts + 1,
    updated_at = NOW()
WHERE pe.id IN (
    SELECT inner_pe.id FROM payment_events AS inner_pe
    WHERE inner_pe.delivery_status = 'pending'
      AND inner_pe.attempts < $2
      AND inner_pe.next_retry_at <= NOW()
    ORDER BY inner_pe.created_at
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING pe.id, pe.deposit_id, pe.event_id, pe.event_type, pe.idempotency_key, pe.payload, pe.delivery_status, pe.attempts, pe.last_error, pe.next_retry_at, pe.delivered_at, pe.created_at, pe.updated_at
`

type ClaimDuePaymentEventsParams struct {
	Limit    int32 `json:"limit"`
	Attempts int32 `json:"attempts"`
}

// Atomically claims due, non-exhausted pending events for delivery and
// increments the attempt count. FOR UPDATE + SKIP LOCKED prevents two
// concurrent workers from claiming the same row.
func (q *Queries) ClaimDuePaymentEvents(ctx context.Context, arg ClaimDuePaymentEventsParams) ([]PaymentEvent, error) {
	rows, err := q.db.Query(ctx, claimDuePaymentEvents, arg.Limit, arg.Attempts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentEvent{}
	for rows.Next() {
		var i PaymentEvent
		if err := rows.Scan(
			&i.ID,
			&i.DepositID,
			&i.EventID,
			&i.EventType,
			&i.IdempotencyKey,
			&i.Payload,
			&i.DeliveryStatus,
			&i.Attempts,
			&i.LastError,
			&i.NextRetryAt,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentEventByDepositID = `-- name: GetPaymentEventByDepositID :one
SELECT id, deposit_id, event_id, event_type, idempotency_key, payload, delivery_status, attempts, last_error, next_retry_at, delivered_at, created_at, updated_at FROM payment_events WHERE deposit_id = $1
`

func (q *Queries) GetPaymentEventByDepositID(ctx context.Context, depositID uuid.UUID) (PaymentEvent, error) {
	row := q.db.QueryRow(ctx, getPaymentEventByDepositID, depositID)
	var i PaymentEvent
	err := row.Scan(
		&i.ID,
		&i.DepositID,
		&i.EventID,
		&i.EventType,
		&i.IdempotencyKey,
		&i.Payload,
		&i.DeliveryStatus,
		&i.Attempts,
		&i.LastError,
		&i.NextRetryAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPaymentEvent = `-- name: InsertPaymentEvent :one
INSERT INTO payment_events (deposit_id, event_id, event_type, idempotency_key, payload)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (deposit_id) DO NOTHING
RETURNING id, deposit_id, event_id, event_type, idempotency_key, payload, delivery_status, attempts, last_error, next_retry_at, delivered_at, created_at, updated_at
`

type InsertPaymentEventParams struct {
	DepositID      uuid.UUID `json:"deposit_id"`
	EventID        uuid.UUID `json:"event_id"`
	EventType      string    `json:"event_type"`
	IdempotencyKey string    `json:"idempotency_key"`
	Payload        []byte    `json:"payload"`
}

// Idempotent emission: one logical event per deposit. A concurrent duplicate
// callback either loses the terminal-state race (ErrNotFound on finalize) or
// is a no-op here. Returns an empty row when the event already exists.
func (q *Queries) InsertPaymentEvent(ctx context.Context, arg InsertPaymentEventParams) (PaymentEvent, error) {
	row := q.db.QueryRow(ctx, insertPaymentEvent,
		arg.DepositID,
		arg.EventID,
		arg.EventType,
		arg.IdempotencyKey,
		arg.Payload,
	)
	var i PaymentEvent
	err := row.Scan(
		&i.ID,
		&i.DepositID,
		&i.EventID,
		&i.EventType,
		&i.IdempotencyKey,
		&i.Payload,
		&i.DeliveryStatus,
		&i.Attempts,
		&i.LastError,
		&i.NextRetryAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordPaymentEventFailure = `-- name: RecordPaymentEventFailure :one
UPDATE payment_events
SET delivery_status = 'failed',
    last_error = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, deposit_id, event_id, event_type, idempotency_key, payload, delivery_status, attempts, last_error, next_retry_at, delivered_at, created_at, updated_at
`

type RecordPaymentEventFailureParams struct {
	ID        uuid.UUID `json:"id"`
	LastError *string   `json:"last_error"`
}

// Records a permanent (non-retryable) failure so a configuration problem
// cannot become an infinite retry loop. Payload and identity are preserved.
func (q *Queries) RecordPaymentEventFailure(ctx context.Context, arg RecordPaymentEventFailureParams) (PaymentEvent, error) {
	row := q.db.QueryRow(ctx, recordPaymentEventFailure, arg.ID, arg.LastError)
	var i PaymentEvent
	err := row.Scan(
		&i.ID,
		&i.DepositID,
		&i.EventID,
		&i.EventType,
		&i.IdempotencyKey,
		&i.Payload,
		&i.DeliveryStatus,
		&i.Attempts,
		&i.LastError,
		&i.NextRetryAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordPaymentEventRetry = `-- name: RecordPaymentEventRetry :one
UPDATE payment_events
SET delivery_status = 'pending',
    last_error = $2,
    next_retry_at = NOW() + make_interval(secs => $3::double precision),
    updated_at = NOW()
WHERE id = $1
RETURNING id, deposit_id, event_id, event_type, idempotency_key, payload, delivery_status, attempts, last_error, next_retry_at, delivered_at, created_at, updated_at
`

type RecordPaymentEventRetryParams struct {
	ID        uuid.UUID `json:"id"`
	LastError *string   `json:"last_error"`
	Column3   float64   `json:"column_3"`
}

// Schedules a transient failure for retry at the caller-computed backoff time.
// The event identity (event_id, idempotency_key, payload) is never changed.
func (q *Queries) RecordPaymentEventRetry(ctx context.Context, arg RecordPaymentEventRetryParams) (PaymentEvent, error) {
	row := q.db.QueryRow(ctx, recordPaymentEventRetry, arg.ID, arg.LastError, arg.Column3)
	var i PaymentEvent
	err := row.Scan(
		&i.ID,
		&i.DepositID,
		&i.EventID,
		&i.EventType,
		&i.IdempotencyKey,
		&i.Payload,
		&i.DeliveryStatus,
		&i.Attempts,
		&i.LastError,
		&i.NextRetryAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordPaymentEventSuccess = `-- name: RecordPaymentEventSuccess :one
UPDATE payment_events
SET delivery_status = 'delivered',
    last_error = NULL,
    delivered_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, deposit_id, event_id, event_type, idempotency_key, payload, delivery_status, attempts, last_error, next_retry_at, delivered_at, created_at, updated_at
`

func (q *Queries) RecordPaymentEventSuccess(ctx context.Context, id uuid.UUID) (PaymentEvent, error) {
	row := q.db.QueryRow(ctx, recordPaymentEventSuccess, id)
	var i PaymentEvent
	err := row.Scan(
		&i.ID,
		&i.DepositID,
		&i.EventID,
		&i.EventType,
		&i.IdempotencyKey,
		&i.Payload,
		&i.DeliveryStatus,
		&i.Attempts,
		&i.LastError,
		&i.NextRetryAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
