// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountMerchants(ctx context.Context) (int64, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateDeposit(ctx context.Context, arg CreateDepositParams) (Deposit, error)
	CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchant, error)
	CreatePayout(ctx context.Context, arg CreatePayoutParams) (Payout, error)
	GetCustomerByClientAndMerchantAndPhone(ctx context.Context, arg GetCustomerByClientAndMerchantAndPhoneParams) (Customer, error)
	GetCustomerByID(ctx context.Context, id uuid.UUID) (Customer, error)
	GetDepositByExternalReference(ctx context.Context, externalReference *string) (Deposit, error)
	GetDepositByGHLChargeID(ctx context.Context, ghlChargeID *string) (Deposit, error)
	GetDepositByGHLTransactionID(ctx context.Context, ghlTransactionID *string) (Deposit, error)
	GetDepositByID(ctx context.Context, id uuid.UUID) (Deposit, error)
	GetDepositByIdempotencyKey(ctx context.Context, idempotencyKey uuid.UUID) (Deposit, error)
	GetMerchantByID(ctx context.Context, id uuid.UUID) (Merchant, error)
	GetMerchantBySlug(ctx context.Context, slug string) (Merchant, error)
	GetPayoutByExternalReference(ctx context.Context, externalReference *string) (Payout, error)
	GetPayoutByID(ctx context.Context, id uuid.UUID) (Payout, error)
	GetPayoutByIdempotencyKey(ctx context.Context, idempotencyKey uuid.UUID) (Payout, error)
	ListCustomersByClient(ctx context.Context, clientID uuid.UUID) ([]Customer, error)
	ListCustomersByMerchant(ctx context.Context, merchantID uuid.UUID) ([]Customer, error)
	ListDepositsByClient(ctx context.Context, clientName string) ([]Deposit, error)
	ListDepositsByCustomer(ctx context.Context, customerID *string) ([]Deposit, error)
	ListDepositsByMerchant(ctx context.Context, merchantID *string) ([]Deposit, error)
	ListDepositsByStatus(ctx context.Context, status DepositStatus) ([]Deposit, error)
	ListMerchants(ctx context.Context, arg ListMerchantsParams) ([]Merchant, error)
	ListPayoutsByClient(ctx context.Context, clientID uuid.UUID) ([]Payout, error)
	ListPayoutsByMerchant(ctx context.Context, merchantID uuid.UUID) ([]Payout, error)
	ListPayoutsByStatus(ctx context.Context, status PayoutStatus) ([]Payout, error)
	UpdateCustomerStatus(ctx context.Context, arg UpdateCustomerStatusParams) (Customer, error)
	UpdateDepositGHLReference(ctx context.Context, arg UpdateDepositGHLReferenceParams) (Deposit, error)
	UpdateDepositStatus(ctx context.Context, arg UpdateDepositStatusParams) (Deposit, error)
	UpdateDepositStatusAndCompletedAt(ctx context.Context, arg UpdateDepositStatusAndCompletedAtParams) (Deposit, error)
	UpdateDepositStatusAndFailedAt(ctx context.Context, arg UpdateDepositStatusAndFailedAtParams) (Deposit, error)
	UpdateMerchantStatus(ctx context.Context, arg UpdateMerchantStatusParams) (Merchant, error)
	UpdatePayoutStatus(ctx context.Context, arg UpdatePayoutStatusParams) (Payout, error)
	UpdatePayoutStatusAndCompletedAt(ctx context.Context, arg UpdatePayoutStatusAndCompletedAtParams) (Payout, error)
	UpdatePayoutStatusAndFailedAt(ctx context.Context, arg UpdatePayoutStatusAndFailedAtParams) (Payout, error)
}

var _ Querier = (*Queries)(nil)
