// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: clients.proto

package clientsgrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientsService_CreateClient_FullMethodName     = "/clientsgrpc.ClientsService/CreateClient"
	ClientsService_UpdateClient_FullMethodName     = "/clientsgrpc.ClientsService/UpdateClient"
	ClientsService_DeleteClient_FullMethodName     = "/clientsgrpc.ClientsService/DeleteClient"
	ClientsService_GetClient_FullMethodName        = "/clientsgrpc.ClientsService/GetClient"
	ClientsService_ListClients_FullMethodName      = "/clientsgrpc.ClientsService/ListClients"
	ClientsService_ActivateClient_FullMethodName   = "/clientsgrpc.ClientsService/ActivateClient"
	ClientsService_DeactivateClient_FullMethodName = "/clientsgrpc.ClientsService/DeactivateClient"
)

// ClientsServiceClient is the client API for ClientsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClientsService manages client accounts.
type ClientsServiceClient interface {
	// CreateClient creates a new client account.
	CreateClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*CreateClientResponse, error)
	// UpdateClient updates an existing client account.
	UpdateClient(ctx context.Context, in *UpdateClientRequest, opts ...grpc.CallOption) (*UpdateClientResponse, error)
	// DeleteClient deletes a client account.
	DeleteClient(ctx context.Context, in *DeleteClientRequest, opts ...grpc.CallOption) (*DeleteClientResponse, error)
	// GetClient fetches a single client account.
	GetClient(ctx context.Context, in *GetClientRequest, opts ...grpc.CallOption) (*GetClientResponse, error)
	// ListClients lists client accounts.
	ListClients(ctx context.Context, in *ListClientsRequest, opts ...grpc.CallOption) (*ListClientsResponse, error)
	// ActivateClient activates a client account.
	ActivateClient(ctx context.Context, in *ActivateClientRequest, opts ...grpc.CallOption) (*ActivateClientResponse, error)
	// DeactivateClient deactivates a client account.
	DeactivateClient(ctx context.Context, in *DeactivateClientRequest, opts ...grpc.CallOption) (*DeactivateClientResponse, error)
}

type clientsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientsServiceClient(cc grpc.ClientConnInterface) ClientsServiceClient {
	return &clientsServiceClient{cc}
}

func (c *clientsServiceClient) CreateClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*CreateClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateClientResponse)
	err := c.cc.Invoke(ctx, ClientsService_CreateClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServiceClient) UpdateClient(ctx context.Context, in *UpdateClientRequest, opts ...grpc.CallOption) (*UpdateClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateClientResponse)
	err := c.cc.Invoke(ctx, ClientsService_UpdateClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServiceClient) DeleteClient(ctx context.Context, in *DeleteClientRequest, opts ...grpc.CallOption) (*DeleteClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteClientResponse)
	err := c.cc.Invoke(ctx, ClientsService_DeleteClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServiceClient) GetClient(ctx context.Context, in *GetClientRequest, opts ...grpc.CallOption) (*GetClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClientResponse)
	err := c.cc.Invoke(ctx, ClientsService_GetClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServiceClient) ListClients(ctx context.Context, in *ListClientsRequest, opts ...grpc.CallOption) (*ListClientsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListClientsResponse)
	err := c.cc.Invoke(ctx, ClientsService_ListClients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServiceClient) ActivateClient(ctx context.Context, in *ActivateClientRequest, opts ...grpc.CallOption) (*ActivateClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateClientResponse)
	err := c.cc.Invoke(ctx, ClientsService_ActivateClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsServiceClient) DeactivateClient(ctx context.Context, in *DeactivateClientRequest, opts ...grpc.CallOption) (*DeactivateClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeactivateClientResponse)
	err := c.cc.Invoke(ctx, ClientsService_DeactivateClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientsServiceServer is the server API for ClientsService service.
// All implementations must embed UnimplementedClientsServiceServer
// for forward compatibility.
//
// ClientsService manages client accounts.
type ClientsServiceServer interface {
	// CreateClient creates a new client account.
	CreateClient(context.Context, *CreateClientRequest) (*CreateClientResponse, error)
	// UpdateClient updates an existing client account.
	UpdateClient(context.Context, *UpdateClientRequest) (*UpdateClientResponse, error)
	// DeleteClient deletes a client account.
	DeleteClient(context.Context, *DeleteClientRequest) (*DeleteClientResponse, error)
	// GetClient fetches a single client account.
	GetClient(context.Context, *GetClientRequest) (*GetClientResponse, error)
	// ListClients lists client accounts.
	ListClients(context.Context, *ListClientsRequest) (*ListClientsResponse, error)
	// ActivateClient activates a client account.
	ActivateClient(context.Context, *ActivateClientRequest) (*ActivateClientResponse, error)
	// DeactivateClient deactivates a client account.
	DeactivateClient(context.Context, *DeactivateClientRequest) (*DeactivateClientResponse, error)
	mustEmbedUnimplementedClientsServiceServer()
}

// UnimplementedClientsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientsServiceServer struct{}

func (UnimplementedClientsServiceServer) CreateClient(context.Context, *CreateClientRequest) (*CreateClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateClient not implemented")
}
func (UnimplementedClientsServiceServer) UpdateClient(context.Context, *UpdateClientRequest) (*UpdateClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateClient not implemented")
}
func (UnimplementedClientsServiceServer) DeleteClient(context.Context, *DeleteClientRequest) (*DeleteClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteClient not implemented")
}
func (UnimplementedClientsServiceServer) GetClient(context.Context, *GetClientRequest) (*GetClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClient not implemented")
}
func (UnimplementedClientsServiceServer) ListClients(context.Context, *ListClientsRequest) (*ListClientsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListClients not implemented")
}
func (UnimplementedClientsServiceServer) ActivateClient(context.Context, *ActivateClientRequest) (*ActivateClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateClient not implemented")
}
func (UnimplementedClientsServiceServer) DeactivateClient(context.Context, *DeactivateClientRequest) (*DeactivateClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeactivateClient not implemented")
}
func (UnimplementedClientsServiceServer) mustEmbedUnimplementedClientsServiceServer() {}
func (UnimplementedClientsServiceServer) testEmbeddedByValue()                        {}

// UnsafeClientsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientsServiceServer will
// result in compilation errors.
type UnsafeClientsServiceServer interface {
	mustEmbedUnimplementedClientsServiceServer()
}

func RegisterClientsServiceServer(s grpc.ServiceRegistrar, srv ClientsServiceServer) {
	// If the following call pancis, it indicates UnimplementedClientsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientsService_ServiceDesc, srv)
}

func _ClientsService_CreateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServiceServer).CreateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientsService_CreateClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServiceServer).CreateClient(ctx, req.(*CreateClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsService_UpdateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServiceServer).UpdateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientsService_UpdateClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServiceServer).UpdateClient(ctx, req.(*UpdateClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsService_DeleteClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServiceServer).DeleteClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientsService_DeleteClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServiceServer).DeleteClient(ctx, req.(*DeleteClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsService_GetClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServiceServer).GetClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientsService_GetClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServiceServer).GetClient(ctx, req.(*GetClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsService_ListClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServiceServer).ListClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientsService_ListClients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServiceServer).ListClients(ctx, req.(*ListClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsService_ActivateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServiceServer).ActivateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientsService_ActivateClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServiceServer).ActivateClient(ctx, req.(*ActivateClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientsService_DeactivateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServiceServer).DeactivateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientsService_DeactivateClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServiceServer).DeactivateClient(ctx, req.(*DeactivateClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientsService_ServiceDesc is the grpc.ServiceDesc for ClientsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clientsgrpc.ClientsService",
	HandlerType: (*ClientsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateClient",
			Handler:    _ClientsService_CreateClient_Handler,
		},
		{
			MethodName: "UpdateClient",
			Handler:    _ClientsService_UpdateClient_Handler,
		},
		{
			MethodName: "DeleteClient",
			Handler:    _ClientsService_DeleteClient_Handler,
		},
		{
			MethodName: "GetClient",
			Handler:    _ClientsService_GetClient_Handler,
		},
		{
			MethodName: "ListClients",
			Handler:    _ClientsService_ListClients_Handler,
		},
		{
			MethodName: "ActivateClient",
			Handler:    _ClientsService_ActivateClient_Handler,
		},
		{
			MethodName: "DeactivateClient",
			Handler:    _ClientsService_DeactivateClient_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clients.proto",
}

const (
	PlatformsService_ListPlatforms_FullMethodName   = "/clientsgrpc.PlatformsService/ListPlatforms"
	PlatformsService_GetPlatform_FullMethodName     = "/clientsgrpc.PlatformsService/GetPlatform"
	PlatformsService_EnablePlatform_FullMethodName  = "/clientsgrpc.PlatformsService/EnablePlatform"
	PlatformsService_DisablePlatform_FullMethodName = "/clientsgrpc.PlatformsService/DisablePlatform"
)

// PlatformsServiceClient is the client API for PlatformsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PlatformsService manages supported marketplace platforms.
type PlatformsServiceClient interface {
	// ListPlatforms lists supported platforms.
	ListPlatforms(ctx context.Context, in *ListPlatformsRequest, opts ...grpc.CallOption) (*ListPlatformsResponse, error)
	// GetPlatform fetches a single platform.
	GetPlatform(ctx context.Context, in *GetPlatformRequest, opts ...grpc.CallOption) (*GetPlatformResponse, error)
	// EnablePlatform enables a platform.
	EnablePlatform(ctx context.Context, in *EnablePlatformRequest, opts ...grpc.CallOption) (*EnablePlatformResponse, error)
	// DisablePlatform disables a platform.
	DisablePlatform(ctx context.Context, in *DisablePlatformRequest, opts ...grpc.CallOption) (*DisablePlatformResponse, error)
}

type platformsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlatformsServiceClient(cc grpc.ClientConnInterface) PlatformsServiceClient {
	return &platformsServiceClient{cc}
}

func (c *platformsServiceClient) ListPlatforms(ctx context.Context, in *ListPlatformsRequest, opts ...grpc.CallOption) (*ListPlatformsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPlatformsResponse)
	err := c.cc.Invoke(ctx, PlatformsService_ListPlatforms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformsServiceClient) GetPlatform(ctx context.Context, in *GetPlatformRequest, opts ...grpc.CallOption) (*GetPlatformResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlatformResponse)
	err := c.cc.Invoke(ctx, PlatformsService_GetPlatform_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformsServiceClient) EnablePlatform(ctx context.Context, in *EnablePlatformRequest, opts ...grpc.CallOption) (*EnablePlatformResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnablePlatformResponse)
	err := c.cc.Invoke(ctx, PlatformsService_EnablePlatform_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformsServiceClient) DisablePlatform(ctx context.Context, in *DisablePlatformRequest, opts ...grpc.CallOption) (*DisablePlatformResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisablePlatformResponse)
	err := c.cc.Invoke(ctx, PlatformsService_DisablePlatform_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlatformsServiceServer is the server API for PlatformsService service.
// All implementations must embed UnimplementedPlatformsServiceServer
// for forward compatibility.
//
// PlatformsService manages supported marketplace platforms.
type PlatformsServiceServer interface {
	// ListPlatforms lists supported platforms.
	ListPlatforms(context.Context, *ListPlatformsRequest) (*ListPlatformsResponse, error)
	// GetPlatform fetches a single platform.
	GetPlatform(context.Context, *GetPlatformRequest) (*GetPlatformResponse, error)
	// EnablePlatform enables a platform.
	EnablePlatform(context.Context, *EnablePlatformRequest) (*EnablePlatformResponse, error)
	// DisablePlatform disables a platform.
	DisablePlatform(context.Context, *DisablePlatformRequest) (*DisablePlatformResponse, error)
	mustEmbedUnimplementedPlatformsServiceServer()
}

// UnimplementedPlatformsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlatformsServiceServer struct{}

func (UnimplementedPlatformsServiceServer) ListPlatforms(context.Context, *ListPlatformsRequest) (*ListPlatformsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPlatforms not implemented")
}
func (UnimplementedPlatformsServiceServer) GetPlatform(context.Context, *GetPlatformRequest) (*GetPlatformResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlatform not implemented")
}
func (UnimplementedPlatformsServiceServer) EnablePlatform(context.Context, *EnablePlatformRequest) (*EnablePlatformResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnablePlatform not implemented")
}
func (UnimplementedPlatformsServiceServer) DisablePlatform(context.Context, *DisablePlatformRequest) (*DisablePlatformResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisablePlatform not implemented")
}
func (UnimplementedPlatformsServiceServer) mustEmbedUnimplementedPlatformsServiceServer() {}
func (UnimplementedPlatformsServiceServer) testEmbeddedByValue()                          {}

// UnsafePlatformsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlatformsServiceServer will
// result in compilation errors.
type UnsafePlatformsServiceServer interface {
	mustEmbedUnimplementedPlatformsServiceServer()
}

func RegisterPlatformsServiceServer(s grpc.ServiceRegistrar, srv PlatformsServiceServer) {
	// If the following call pancis, it indicates UnimplementedPlatformsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlatformsService_ServiceDesc, srv)
}

func _PlatformsService_ListPlatforms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlatformsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformsServiceServer).ListPlatforms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformsService_ListPlatforms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformsServiceServer).ListPlatforms(ctx, req.(*ListPlatformsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformsService_GetPlatform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlatformRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformsServiceServer).GetPlatform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformsService_GetPlatform_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformsServiceServer).GetPlatform(ctx, req.(*GetPlatformRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformsService_EnablePlatform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnablePlatformRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformsServiceServer).EnablePlatform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformsService_EnablePlatform_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformsServiceServer).EnablePlatform(ctx, req.(*EnablePlatformRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformsService_DisablePlatform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisablePlatformRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformsServiceServer).DisablePlatform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformsService_DisablePlatform_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformsServiceServer).DisablePlatform(ctx, req.(*DisablePlatformRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlatformsService_ServiceDesc is the grpc.ServiceDesc for PlatformsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlatformsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clientsgrpc.PlatformsService",
	HandlerType: (*PlatformsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPlatforms",
			Handler:    _PlatformsService_ListPlatforms_Handler,
		},
		{
			MethodName: "GetPlatform",
			Handler:    _PlatformsService_GetPlatform_Handler,
		},
		{
			MethodName: "EnablePlatform",
			Handler:    _PlatformsService_EnablePlatform_Handler,
		},
		{
			MethodName: "DisablePlatform",
			Handler:    _PlatformsService_DisablePlatform_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clients.proto",
}

const (
	IntegrationsService_InstallIntegration_FullMethodName    = "/clientsgrpc.IntegrationsService/InstallIntegration"
	IntegrationsService_UninstallIntegration_FullMethodName  = "/clientsgrpc.IntegrationsService/UninstallIntegration"
	IntegrationsService_GetIntegration_FullMethodName        = "/clientsgrpc.IntegrationsService/GetIntegration"
	IntegrationsService_ListIntegrations_FullMethodName      = "/clientsgrpc.IntegrationsService/ListIntegrations"
	IntegrationsService_ReconnectIntegration_FullMethodName  = "/clientsgrpc.IntegrationsService/ReconnectIntegration"
	IntegrationsService_DisconnectIntegration_FullMethodName = "/clientsgrpc.IntegrationsService/DisconnectIntegration"
	IntegrationsService_SyncIntegration_FullMethodName       = "/clientsgrpc.IntegrationsService/SyncIntegration"
	IntegrationsService_HealthCheck_FullMethodName           = "/clientsgrpc.IntegrationsService/HealthCheck"
)

// IntegrationsServiceClient is the client API for IntegrationsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IntegrationsService manages client-platform integrations.
type IntegrationsServiceClient interface {
	// InstallIntegration installs a platform for a client.
	InstallIntegration(ctx context.Context, in *InstallIntegrationRequest, opts ...grpc.CallOption) (*InstallIntegrationResponse, error)
	// UninstallIntegration uninstalls a platform for a client.
	UninstallIntegration(ctx context.Context, in *UninstallIntegrationRequest, opts ...grpc.CallOption) (*UninstallIntegrationResponse, error)
	// GetIntegration fetches a single integration.
	GetIntegration(ctx context.Context, in *GetIntegrationRequest, opts ...grpc.CallOption) (*GetIntegrationResponse, error)
	// ListIntegrations lists integrations.
	ListIntegrations(ctx context.Context, in *ListIntegrationsRequest, opts ...grpc.CallOption) (*ListIntegrationsResponse, error)
	// ReconnectIntegration reconnects an integration.
	ReconnectIntegration(ctx context.Context, in *ReconnectIntegrationRequest, opts ...grpc.CallOption) (*ReconnectIntegrationResponse, error)
	// DisconnectIntegration disconnects an integration.
	DisconnectIntegration(ctx context.Context, in *DisconnectIntegrationRequest, opts ...grpc.CallOption) (*DisconnectIntegrationResponse, error)
	// SyncIntegration synchronizes an integration.
	SyncIntegration(ctx context.Context, in *SyncIntegrationRequest, opts ...grpc.CallOption) (*SyncIntegrationResponse, error)
	// HealthCheck returns a 200 to ensure the server is live.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type integrationsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIntegrationsServiceClient(cc grpc.ClientConnInterface) IntegrationsServiceClient {
	return &integrationsServiceClient{cc}
}

func (c *integrationsServiceClient) InstallIntegration(ctx context.Context, in *InstallIntegrationRequest, opts ...grpc.CallOption) (*InstallIntegrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallIntegrationResponse)
	err := c.cc.Invoke(ctx, IntegrationsService_InstallIntegration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationsServiceClient) UninstallIntegration(ctx context.Context, in *UninstallIntegrationRequest, opts ...grpc.CallOption) (*UninstallIntegrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UninstallIntegrationResponse)
	err := c.cc.Invoke(ctx, IntegrationsService_UninstallIntegration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationsServiceClient) GetIntegration(ctx context.Context, in *GetIntegrationRequest, opts ...grpc.CallOption) (*GetIntegrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIntegrationResponse)
	err := c.cc.Invoke(ctx, IntegrationsService_GetIntegration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationsServiceClient) ListIntegrations(ctx context.Context, in *ListIntegrationsRequest, opts ...grpc.CallOption) (*ListIntegrationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIntegrationsResponse)
	err := c.cc.Invoke(ctx, IntegrationsService_ListIntegrations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationsServiceClient) ReconnectIntegration(ctx context.Context, in *ReconnectIntegrationRequest, opts ...grpc.CallOption) (*ReconnectIntegrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconnectIntegrationResponse)
	err := c.cc.Invoke(ctx, IntegrationsService_ReconnectIntegration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationsServiceClient) DisconnectIntegration(ctx context.Context, in *DisconnectIntegrationRequest, opts ...grpc.CallOption) (*DisconnectIntegrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectIntegrationResponse)
	err := c.cc.Invoke(ctx, IntegrationsService_DisconnectIntegration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationsServiceClient) SyncIntegration(ctx context.Context, in *SyncIntegrationRequest, opts ...grpc.CallOption) (*SyncIntegrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncIntegrationResponse)
	err := c.cc.Invoke(ctx, IntegrationsService_SyncIntegration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationsServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, IntegrationsService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntegrationsServiceServer is the server API for IntegrationsService service.
// All implementations must embed UnimplementedIntegrationsServiceServer
// for forward compatibility.
//
// IntegrationsService manages client-platform integrations.
type IntegrationsServiceServer interface {
	// InstallIntegration installs a platform for a client.
	InstallIntegration(context.Context, *InstallIntegrationRequest) (*InstallIntegrationResponse, error)
	// UninstallIntegration uninstalls a platform for a client.
	UninstallIntegration(context.Context, *UninstallIntegrationRequest) (*UninstallIntegrationResponse, error)
	// GetIntegration fetches a single integration.
	GetIntegration(context.Context, *GetIntegrationRequest) (*GetIntegrationResponse, error)
	// ListIntegrations lists integrations.
	ListIntegrations(context.Context, *ListIntegrationsRequest) (*ListIntegrationsResponse, error)
	// ReconnectIntegration reconnects an integration.
	ReconnectIntegration(context.Context, *ReconnectIntegrationRequest) (*ReconnectIntegrationResponse, error)
	// DisconnectIntegration disconnects an integration.
	DisconnectIntegration(context.Context, *DisconnectIntegrationRequest) (*DisconnectIntegrationResponse, error)
	// SyncIntegration synchronizes an integration.
	SyncIntegration(context.Context, *SyncIntegrationRequest) (*SyncIntegrationResponse, error)
	// HealthCheck returns a 200 to ensure the server is live.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedIntegrationsServiceServer()
}

// UnimplementedIntegrationsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIntegrationsServiceServer struct{}

func (UnimplementedIntegrationsServiceServer) InstallIntegration(context.Context, *InstallIntegrationRequest) (*InstallIntegrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InstallIntegration not implemented")
}
func (UnimplementedIntegrationsServiceServer) UninstallIntegration(context.Context, *UninstallIntegrationRequest) (*UninstallIntegrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UninstallIntegration not implemented")
}
func (UnimplementedIntegrationsServiceServer) GetIntegration(context.Context, *GetIntegrationRequest) (*GetIntegrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIntegration not implemented")
}
func (UnimplementedIntegrationsServiceServer) ListIntegrations(context.Context, *ListIntegrationsRequest) (*ListIntegrationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIntegrations not implemented")
}
func (UnimplementedIntegrationsServiceServer) ReconnectIntegration(context.Context, *ReconnectIntegrationRequest) (*ReconnectIntegrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReconnectIntegration not implemented")
}
func (UnimplementedIntegrationsServiceServer) DisconnectIntegration(context.Context, *DisconnectIntegrationRequest) (*DisconnectIntegrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisconnectIntegration not implemented")
}
func (UnimplementedIntegrationsServiceServer) SyncIntegration(context.Context, *SyncIntegrationRequest) (*SyncIntegrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncIntegration not implemented")
}
func (UnimplementedIntegrationsServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedIntegrationsServiceServer) mustEmbedUnimplementedIntegrationsServiceServer() {}
func (UnimplementedIntegrationsServiceServer) testEmbeddedByValue()                             {}

// UnsafeIntegrationsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntegrationsServiceServer will
// result in compilation errors.
type UnsafeIntegrationsServiceServer interface {
	mustEmbedUnimplementedIntegrationsServiceServer()
}

func RegisterIntegrationsServiceServer(s grpc.ServiceRegistrar, srv IntegrationsServiceServer) {
	// If the following call pancis, it indicates UnimplementedIntegrationsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IntegrationsService_ServiceDesc, srv)
}

func _IntegrationsService_InstallIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallIntegrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationsServiceServer).InstallIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrationsService_InstallIntegration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationsServiceServer).InstallIntegration(ctx, req.(*InstallIntegrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationsService_UninstallIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UninstallIntegrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationsServiceServer).UninstallIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrationsService_UninstallIntegration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationsServiceServer).UninstallIntegration(ctx, req.(*UninstallIntegrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationsService_GetIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIntegrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationsServiceServer).GetIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrationsService_GetIntegration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationsServiceServer).GetIntegration(ctx, req.(*GetIntegrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationsService_ListIntegrations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIntegrationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationsServiceServer).ListIntegrations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrationsService_ListIntegrations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationsServiceServer).ListIntegrations(ctx, req.(*ListIntegrationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationsService_ReconnectIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconnectIntegrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationsServiceServer).ReconnectIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrationsService_ReconnectIntegration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationsServiceServer).ReconnectIntegration(ctx, req.(*ReconnectIntegrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationsService_DisconnectIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectIntegrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationsServiceServer).DisconnectIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrationsService_DisconnectIntegration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationsServiceServer).DisconnectIntegration(ctx, req.(*DisconnectIntegrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationsService_SyncIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncIntegrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationsServiceServer).SyncIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrationsService_SyncIntegration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationsServiceServer).SyncIntegration(ctx, req.(*SyncIntegrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationsService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationsServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrationsService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationsServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IntegrationsService_ServiceDesc is the grpc.ServiceDesc for IntegrationsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IntegrationsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clientsgrpc.IntegrationsService",
	HandlerType: (*IntegrationsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InstallIntegration",
			Handler:    _IntegrationsService_InstallIntegration_Handler,
		},
		{
			MethodName: "UninstallIntegration",
			Handler:    _IntegrationsService_UninstallIntegration_Handler,
		},
		{
			MethodName: "GetIntegration",
			Handler:    _IntegrationsService_GetIntegration_Handler,
		},
		{
			MethodName: "ListIntegrations",
			Handler:    _IntegrationsService_ListIntegrations_Handler,
		},
		{
			MethodName: "ReconnectIntegration",
			Handler:    _IntegrationsService_ReconnectIntegration_Handler,
		},
		{
			MethodName: "DisconnectIntegration",
			Handler:    _IntegrationsService_DisconnectIntegration_Handler,
		},
		{
			MethodName: "SyncIntegration",
			Handler:    _IntegrationsService_SyncIntegration_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _IntegrationsService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clients.proto",
}
