// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: clients.proto

package clientsgrpc

import (
	commongrpc "github.com/I-Frostbyte/rvpay-go/grpc/go/commongrpc"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Client represents a business using RVPay.
type Client struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier of the client.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name is the display name of the client.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// status is the current lifecycle state of the client.
	Status commongrpc.ClientStatus `protobuf:"varint,3,opt,name=status,proto3,enum=commongrpc.ClientStatus" json:"status,omitempty"`
	// created_at is the time the client was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at is the time the client was last modified.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_clients_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{0}
}

func (x *Client) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Client) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Client) GetStatus() commongrpc.ClientStatus {
	if x != nil {
		return x.Status
	}
	return commongrpc.ClientStatus(0)
}

func (x *Client) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Client) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateClientRequest is the request to create a new client.
type CreateClientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the display name of the client.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientRequest) Reset() {
	*x = CreateClientRequest{}
	mi := &file_clients_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientRequest) ProtoMessage() {}

func (x *CreateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientRequest.ProtoReflect.Descriptor instead.
func (*CreateClientRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{1}
}

func (x *CreateClientRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// CreateClientResponse is the response after creating a client.
type CreateClientResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client is the created client resource.
	Client        *Client `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientResponse) Reset() {
	*x = CreateClientResponse{}
	mi := &file_clients_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientResponse) ProtoMessage() {}

func (x *CreateClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientResponse.ProtoReflect.Descriptor instead.
func (*CreateClientResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{2}
}

func (x *CreateClientResponse) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

// UpdateClientRequest is the request to update an existing client.
type UpdateClientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier of the client to update.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name is the updated display name of the client.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClientRequest) Reset() {
	*x = UpdateClientRequest{}
	mi := &file_clients_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientRequest) ProtoMessage() {}

func (x *UpdateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientRequest.ProtoReflect.Descriptor instead.
func (*UpdateClientRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateClientRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateClientRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// UpdateClientResponse is the response after updating a client.
type UpdateClientResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client is the updated client resource.
	Client        *Client `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClientResponse) Reset() {
	*x = UpdateClientResponse{}
	mi := &file_clients_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientResponse) ProtoMessage() {}

func (x *UpdateClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientResponse.ProtoReflect.Descriptor instead.
func (*UpdateClientResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateClientResponse) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

// DeleteClientRequest is the request to delete a client.
type DeleteClientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier of the client to delete.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClientRequest) Reset() {
	*x = DeleteClientRequest{}
	mi := &file_clients_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClientRequest) ProtoMessage() {}

func (x *DeleteClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClientRequest.ProtoReflect.Descriptor instead.
func (*DeleteClientRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteClientRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteClientResponse is the response after deleting a client.
type DeleteClientResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier of the deleted client.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClientResponse) Reset() {
	*x = DeleteClientResponse{}
	mi := &file_clients_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClientResponse) ProtoMessage() {}

func (x *DeleteClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClientResponse.ProtoReflect.Descriptor instead.
func (*DeleteClientResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteClientResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetClientRequest is the request to fetch a single client.
type GetClientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier of the client to fetch.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientRequest) Reset() {
	*x = GetClientRequest{}
	mi := &file_clients_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientRequest) ProtoMessage() {}

func (x *GetClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientRequest.ProtoReflect.Descriptor instead.
func (*GetClientRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{7}
}

func (x *GetClientRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetClientResponse is the response containing a single client.
type GetClientResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client is the requested client resource.
	Client        *Client `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientResponse) Reset() {
	*x = GetClientResponse{}
	mi := &file_clients_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientResponse) ProtoMessage() {}

func (x *GetClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientResponse.ProtoReflect.Descriptor instead.
func (*GetClientResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{8}
}

func (x *GetClientResponse) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

// ListClientsRequest is the request to list clients.
type ListClientsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pagination controls the page size and cursor.
	Pagination    *commongrpc.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientsRequest) Reset() {
	*x = ListClientsRequest{}
	mi := &file_clients_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsRequest) ProtoMessage() {}

func (x *ListClientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientsRequest.ProtoReflect.Descriptor instead.
func (*ListClientsRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{9}
}

func (x *ListClientsRequest) GetPagination() *commongrpc.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// ListClientsResponse is the response containing a list of clients.
type ListClientsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// clients is the list of client resources.
	Clients []*Client `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	// pagination carries the next page cursor and total count.
	Pagination    *commongrpc.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientsResponse) Reset() {
	*x = ListClientsResponse{}
	mi := &file_clients_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsResponse) ProtoMessage() {}

func (x *ListClientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientsResponse.ProtoReflect.Descriptor instead.
func (*ListClientsResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{10}
}

func (x *ListClientsResponse) GetClients() []*Client {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *ListClientsResponse) GetPagination() *commongrpc.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// ActivateClientRequest is the request to activate a client.
type ActivateClientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier of the client to activate.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateClientRequest) Reset() {
	*x = ActivateClientRequest{}
	mi := &file_clients_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateClientRequest) ProtoMessage() {}

func (x *ActivateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateClientRequest.ProtoReflect.Descriptor instead.
func (*ActivateClientRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{11}
}

func (x *ActivateClientRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ActivateClientResponse is the response after activating a client.
type ActivateClientResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client is the updated client resource.
	Client        *Client `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateClientResponse) Reset() {
	*x = ActivateClientResponse{}
	mi := &file_clients_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateClientResponse) ProtoMessage() {}

func (x *ActivateClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateClientResponse.ProtoReflect.Descriptor instead.
func (*ActivateClientResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{12}
}

func (x *ActivateClientResponse) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

// DeactivateClientRequest is the request to deactivate a client.
type DeactivateClientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier of the client to deactivate.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateClientRequest) Reset() {
	*x = DeactivateClientRequest{}
	mi := &file_clients_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateClientRequest) ProtoMessage() {}

func (x *DeactivateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateClientRequest.ProtoReflect.Descriptor instead.
func (*DeactivateClientRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{13}
}

func (x *DeactivateClientRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeactivateClientResponse is the response after deactivating a client.
type DeactivateClientResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client is the updated client resource.
	Client        *Client `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateClientResponse) Reset() {
	*x = DeactivateClientResponse{}
	mi := &file_clients_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateClientResponse) ProtoMessage() {}

func (x *DeactivateClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateClientResponse.ProtoReflect.Descriptor instead.
func (*DeactivateClientResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{14}
}

func (x *DeactivateClientResponse) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

// Platform represents a supported external marketplace platform.
type Platform struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier of the platform.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name is the canonical name of the platform.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// display_name is the human-readable name of the platform.
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// slug is the URL-safe identifier of the platform.
	Slug string `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	// status is the current lifecycle state of the platform.
	Status commongrpc.PlatformStatus `protobuf:"varint,5,opt,name=status,proto3,enum=commongrpc.PlatformStatus" json:"status,omitempty"`
	// capabilities lists the capabilities the platform supports.
	Capabilities []commongrpc.ProviderCapability `protobuf:"varint,6,rep,packed,name=capabilities,proto3,enum=commongrpc.ProviderCapability" json:"capabilities,omitempty"`
	// created_at is the time the platform was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at is the time the platform was last modified.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Platform) Reset() {
	*x = Platform{}
	mi := &file_clients_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Platform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Platform) ProtoMessage() {}

func (x *Platform) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Platform.ProtoReflect.Descriptor instead.
func (*Platform) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{15}
}

func (x *Platform) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Platform) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Platform) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Platform) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Platform) GetStatus() commongrpc.PlatformStatus {
	if x != nil {
		return x.Status
	}
	return commongrpc.PlatformStatus(0)
}

func (x *Platform) GetCapabilities() []commongrpc.ProviderCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Platform) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Platform) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ListPlatformsRequest is the request to list platforms.
type ListPlatformsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pagination controls the page size and cursor.
	Pagination    *commongrpc.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlatformsRequest) Reset() {
	*x = ListPlatformsRequest{}
	mi := &file_clients_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlatformsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlatformsRequest) ProtoMessage() {}

func (x *ListPlatformsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlatformsRequest.ProtoReflect.Descriptor instead.
func (*ListPlatformsRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{16}
}

func (x *ListPlatformsRequest) GetPagination() *commongrpc.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// ListPlatformsResponse is the response containing a list of platforms.
type ListPlatformsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// platforms is the list of platform resources.
	Platforms []*Platform `protobuf:"bytes,1,rep,name=platforms,proto3" json:"platforms,omitempty"`
	// pagination carries the next page cursor and total count.
	Pagination    *commongrpc.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlatformsResponse) Reset() {
	*x = ListPlatformsResponse{}
	mi := &file_clients_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlatformsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlatformsResponse) ProtoMessage() {}

func (x *ListPlatformsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlatformsResponse.ProtoReflect.Descriptor instead.
func (*ListPlatformsResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{17}
}

func (x *ListPlatformsResponse) GetPlatforms() []*Platform {
	if x != nil {
		return x.Platforms
	}
	return nil
}

func (x *ListPlatformsResponse) GetPagination() *commongrpc.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// GetPlatformRequest is the request to fetch a single platform.
type GetPlatformRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier of the platform to fetch.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlatformRequest) Reset() {
	*x = GetPlatformRequest{}
	mi := &file_clients_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlatformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformRequest) ProtoMessage() {}

func (x *GetPlatformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformRequest.ProtoReflect.Descriptor instead.
func (*GetPlatformRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{18}
}

func (x *GetPlatformRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetPlatformResponse is the response containing a single platform.
type GetPlatformResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// platform is the requested platform resource.
	Platform      *Platform `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlatformResponse) Reset() {
	*x = GetPlatformResponse{}
	mi := &file_clients_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlatformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformResponse) ProtoMessage() {}

func (x *GetPlatformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformResponse.ProtoReflect.Descriptor instead.
func (*GetPlatformResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{19}
}

func (x *GetPlatformResponse) GetPlatform() *Platform {
	if x != nil {
		return x.Platform
	}
	return nil
}

// EnablePlatformRequest is the request to enable a platform.
type EnablePlatformRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier of the platform to enable.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnablePlatformRequest) Reset() {
	*x = EnablePlatformRequest{}
	mi := &file_clients_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnablePlatformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnablePlatformRequest) ProtoMessage() {}

func (x *EnablePlatformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnablePlatformRequest.ProtoReflect.Descriptor instead.
func (*EnablePlatformRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{20}
}

func (x *EnablePlatformRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// EnablePlatformResponse is the response after enabling a platform.
type EnablePlatformResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// platform is the updated platform resource.
	Platform      *Platform `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnablePlatformResponse) Reset() {
	*x = EnablePlatformResponse{}
	mi := &file_clients_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnablePlatformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnablePlatformResponse) ProtoMessage() {}

func (x *EnablePlatformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnablePlatformResponse.ProtoReflect.Descriptor instead.
func (*EnablePlatformResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{21}
}

func (x *EnablePlatformResponse) GetPlatform() *Platform {
	if x != nil {
		return x.Platform
	}
	return nil
}

// DisablePlatformRequest is the request to disable a platform.
type DisablePlatformRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier of the platform to disable.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisablePlatformRequest) Reset() {
	*x = DisablePlatformRequest{}
	mi := &file_clients_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisablePlatformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisablePlatformRequest) ProtoMessage() {}

func (x *DisablePlatformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisablePlatformRequest.ProtoReflect.Descriptor instead.
func (*DisablePlatformRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{22}
}

func (x *DisablePlatformRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DisablePlatformResponse is the response after disabling a platform.
type DisablePlatformResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// platform is the updated platform resource.
	Platform      *Platform `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisablePlatformResponse) Reset() {
	*x = DisablePlatformResponse{}
	mi := &file_clients_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisablePlatformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisablePlatformResponse) ProtoMessage() {}

func (x *DisablePlatformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisablePlatformResponse.ProtoReflect.Descriptor instead.
func (*DisablePlatformResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{23}
}

func (x *DisablePlatformResponse) GetPlatform() *Platform {
	if x != nil {
		return x.Platform
	}
	return nil
}

// Integration represents a client connected to a platform.
type Integration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier of the integration.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// client_id is the unique identifier of the owning client.
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// platform_id is the unique identifier of the connected platform.
	PlatformId string `protobuf:"bytes,3,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	// external_account_id is the provider-side account identifier.
	ExternalAccountId string `protobuf:"bytes,4,opt,name=external_account_id,json=externalAccountId,proto3" json:"external_account_id,omitempty"`
	// status is the current lifecycle state of the integration.
	Status commongrpc.IntegrationStatus `protobuf:"varint,5,opt,name=status,proto3,enum=commongrpc.IntegrationStatus" json:"status,omitempty"`
	// installed_at is the time the integration was installed.
	InstalledAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=installed_at,json=installedAt,proto3" json:"installed_at,omitempty"`
	// last_sync_at is the time the integration was last synchronized.
	LastSyncAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_sync_at,json=lastSyncAt,proto3" json:"last_sync_at,omitempty"`
	// created_at is the time the integration was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at is the time the integration was last modified.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Integration) Reset() {
	*x = Integration{}
	mi := &file_clients_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Integration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Integration) ProtoMessage() {}

func (x *Integration) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Integration.ProtoReflect.Descriptor instead.
func (*Integration) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{24}
}

func (x *Integration) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Integration) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Integration) GetPlatformId() string {
	if x != nil {
		return x.PlatformId
	}
	return ""
}

func (x *Integration) GetExternalAccountId() string {
	if x != nil {
		return x.ExternalAccountId
	}
	return ""
}

func (x *Integration) GetStatus() commongrpc.IntegrationStatus {
	if x != nil {
		return x.Status
	}
	return commongrpc.IntegrationStatus(0)
}

func (x *Integration) GetInstalledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.InstalledAt
	}
	return nil
}

func (x *Integration) GetLastSyncAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSyncAt
	}
	return nil
}

func (x *Integration) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Integration) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// InstallIntegrationRequest is the request to install an integration.
type InstallIntegrationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client_id is the unique identifier of the owning client.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// platform_id is the unique identifier of the platform to connect.
	PlatformId string `protobuf:"bytes,2,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	// external_account_id is the provider-side account identifier (e.g. the GHL
	// locationId) that deterministically maps this integration to the correct
	// client. It is optional and backwards-compatible; when omitted the
	// integration is created without a provider account binding.
	ExternalAccountId string `protobuf:"bytes,3,opt,name=external_account_id,json=externalAccountId,proto3" json:"external_account_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InstallIntegrationRequest) Reset() {
	*x = InstallIntegrationRequest{}
	mi := &file_clients_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallIntegrationRequest) ProtoMessage() {}

func (x *InstallIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallIntegrationRequest.ProtoReflect.Descriptor instead.
func (*InstallIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{25}
}

func (x *InstallIntegrationRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *InstallIntegrationRequest) GetPlatformId() string {
	if x != nil {
		return x.PlatformId
	}
	return ""
}

func (x *InstallIntegrationRequest) GetExternalAccountId() string {
	if x != nil {
		return x.ExternalAccountId
	}
	return ""
}

// InstallIntegrationResponse is the response after installing an integration.
type InstallIntegrationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// integration is the installed integration resource.
	Integration   *Integration `protobuf:"bytes,1,opt,name=integration,proto3" json:"integration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallIntegrationResponse) Reset() {
	*x = InstallIntegrationResponse{}
	mi := &file_clients_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallIntegrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallIntegrationResponse) ProtoMessage() {}

func (x *InstallIntegrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallIntegrationResponse.ProtoReflect.Descriptor instead.
func (*InstallIntegrationResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{26}
}

func (x *InstallIntegrationResponse) GetIntegration() *Integration {
	if x != nil {
		return x.Integration
	}
	return nil
}

// UninstallIntegrationRequest is the request to uninstall an integration.
type UninstallIntegrationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier of the integration to uninstall.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UninstallIntegrationRequest) Reset() {
	*x = UninstallIntegrationRequest{}
	mi := &file_clients_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallIntegrationRequest) ProtoMessage() {}

func (x *UninstallIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallIntegrationRequest.ProtoReflect.Descriptor instead.
func (*UninstallIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{27}
}

func (x *UninstallIntegrationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// UninstallIntegrationResponse is the response after uninstalling an
// integration.
type UninstallIntegrationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier of the uninstalled integration.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UninstallIntegrationResponse) Reset() {
	*x = UninstallIntegrationResponse{}
	mi := &file_clients_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallIntegrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallIntegrationResponse) ProtoMessage() {}

func (x *UninstallIntegrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallIntegrationResponse.ProtoReflect.Descriptor instead.
func (*UninstallIntegrationResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{28}
}

func (x *UninstallIntegrationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetIntegrationRequest is the request to fetch a single integration.
type GetIntegrationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier of the integration to fetch.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIntegrationRequest) Reset() {
	*x = GetIntegrationRequest{}
	mi := &file_clients_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntegrationRequest) ProtoMessage() {}

func (x *GetIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntegrationRequest.ProtoReflect.Descriptor instead.
func (*GetIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{29}
}

func (x *GetIntegrationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetIntegrationResponse is the response containing a single integration.
type GetIntegrationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// integration is the requested integration resource.
	Integration   *Integration `protobuf:"bytes,1,opt,name=integration,proto3" json:"integration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIntegrationResponse) Reset() {
	*x = GetIntegrationResponse{}
	mi := &file_clients_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIntegrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntegrationResponse) ProtoMessage() {}

func (x *GetIntegrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntegrationResponse.ProtoReflect.Descriptor instead.
func (*GetIntegrationResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{30}
}

func (x *GetIntegrationResponse) GetIntegration() *Integration {
	if x != nil {
		return x.Integration
	}
	return nil
}

// ListIntegrationsRequest is the request to list integrations.
type ListIntegrationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client_id filters integrations by owning client.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// platform_id filters integrations by connected platform.
	PlatformId string `protobuf:"bytes,2,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	// pagination controls the page size and cursor.
	Pagination    *commongrpc.PaginationRequest `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIntegrationsRequest) Reset() {
	*x = ListIntegrationsRequest{}
	mi := &file_clients_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIntegrationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIntegrationsRequest) ProtoMessage() {}

func (x *ListIntegrationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIntegrationsRequest.ProtoReflect.Descriptor instead.
func (*ListIntegrationsRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{31}
}

func (x *ListIntegrationsRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ListIntegrationsRequest) GetPlatformId() string {
	if x != nil {
		return x.PlatformId
	}
	return ""
}

func (x *ListIntegrationsRequest) GetPagination() *commongrpc.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// ListIntegrationsResponse is the response containing a list of integrations.
type ListIntegrationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// integrations is the list of integration resources.
	Integrations []*Integration `protobuf:"bytes,1,rep,name=integrations,proto3" json:"integrations,omitempty"`
	// pagination carries the next page cursor and total count.
	Pagination    *commongrpc.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIntegrationsResponse) Reset() {
	*x = ListIntegrationsResponse{}
	mi := &file_clients_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIntegrationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIntegrationsResponse) ProtoMessage() {}

func (x *ListIntegrationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIntegrationsResponse.ProtoReflect.Descriptor instead.
func (*ListIntegrationsResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{32}
}

func (x *ListIntegrationsResponse) GetIntegrations() []*Integration {
	if x != nil {
		return x.Integrations
	}
	return nil
}

func (x *ListIntegrationsResponse) GetPagination() *commongrpc.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// ReconnectIntegrationRequest is the request to reconnect an integration.
type ReconnectIntegrationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier of the integration to reconnect.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconnectIntegrationRequest) Reset() {
	*x = ReconnectIntegrationRequest{}
	mi := &file_clients_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconnectIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectIntegrationRequest) ProtoMessage() {}

func (x *ReconnectIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectIntegrationRequest.ProtoReflect.Descriptor instead.
func (*ReconnectIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{33}
}

func (x *ReconnectIntegrationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ReconnectIntegrationResponse is the response after reconnecting an
// integration.
type ReconnectIntegrationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// integration is the updated integration resource.
	Integration   *Integration `protobuf:"bytes,1,opt,name=integration,proto3" json:"integration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconnectIntegrationResponse) Reset() {
	*x = ReconnectIntegrationResponse{}
	mi := &file_clients_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconnectIntegrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectIntegrationResponse) ProtoMessage() {}

func (x *ReconnectIntegrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectIntegrationResponse.ProtoReflect.Descriptor instead.
func (*ReconnectIntegrationResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{34}
}

func (x *ReconnectIntegrationResponse) GetIntegration() *Integration {
	if x != nil {
		return x.Integration
	}
	return nil
}

// DisconnectIntegrationRequest is the request to disconnect an integration.
type DisconnectIntegrationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier of the integration to disconnect.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectIntegrationRequest) Reset() {
	*x = DisconnectIntegrationRequest{}
	mi := &file_clients_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectIntegrationRequest) ProtoMessage() {}

func (x *DisconnectIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectIntegrationRequest.ProtoReflect.Descriptor instead.
func (*DisconnectIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{35}
}

func (x *DisconnectIntegrationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DisconnectIntegrationResponse is the response after disconnecting an
// integration.
type DisconnectIntegrationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// integration is the updated integration resource.
	Integration   *Integration `protobuf:"bytes,1,opt,name=integration,proto3" json:"integration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectIntegrationResponse) Reset() {
	*x = DisconnectIntegrationResponse{}
	mi := &file_clients_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectIntegrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectIntegrationResponse) ProtoMessage() {}

func (x *DisconnectIntegrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectIntegrationResponse.ProtoReflect.Descriptor instead.
func (*DisconnectIntegrationResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{36}
}

func (x *DisconnectIntegrationResponse) GetIntegration() *Integration {
	if x != nil {
		return x.Integration
	}
	return nil
}

// SyncIntegrationRequest is the request to synchronize an integration.
type SyncIntegrationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier of the integration to synchronize.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncIntegrationRequest) Reset() {
	*x = SyncIntegrationRequest{}
	mi := &file_clients_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncIntegrationRequest) ProtoMessage() {}

func (x *SyncIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncIntegrationRequest.ProtoReflect.Descriptor instead.
func (*SyncIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{37}
}

func (x *SyncIntegrationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// SyncIntegrationResponse is the response after synchronizing an integration.
type SyncIntegrationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// integration is the updated integration resource.
	Integration   *Integration `protobuf:"bytes,1,opt,name=integration,proto3" json:"integration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncIntegrationResponse) Reset() {
	*x = SyncIntegrationResponse{}
	mi := &file_clients_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncIntegrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncIntegrationResponse) ProtoMessage() {}

func (x *SyncIntegrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncIntegrationResponse.ProtoReflect.Descriptor instead.
func (*SyncIntegrationResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{38}
}

func (x *SyncIntegrationResponse) GetIntegration() *Integration {
	if x != nil {
		return x.Integration
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_clients_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{39}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_clients_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{40}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_clients_proto protoreflect.FileDescriptor

const file_clients_proto_rawDesc = "" +
	"\n" +
	"\rclients.proto\x12\vclientsgrpc\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\fcommon.proto\"\xd4\x01\n" +
	"\x06Client\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x120\n" +
	"\x06status\x18\x03 \x01(\x0e2\x18.commongrpc.ClientStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\")\n" +
	"\x13CreateClientRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"C\n" +
	"\x14CreateClientResponse\x12+\n" +
	"\x06client\x18\x01 \x01(\v2\x13.clientsgrpc.ClientR\x06client\"9\n" +
	"\x13UpdateClientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"C\n" +
	"\x14UpdateClientResponse\x12+\n" +
	"\x06client\x18\x01 \x01(\v2\x13.clientsgrpc.ClientR\x06client\"%\n" +
	"\x13DeleteClientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"&\n" +
	"\x14DeleteClientResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\"\n" +
	"\x10GetClientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x11GetClientResponse\x12+\n" +
	"\x06client\x18\x01 \x01(\v2\x13.clientsgrpc.ClientR\x06client\"S\n" +
	"\x12ListClientsRequest\x12=\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1d.commongrpc.PaginationRequestR\n" +
	"pagination\"\x84\x01\n" +
	"\x13ListClientsResponse\x12-\n" +
	"\aclients\x18\x01 \x03(\v2\x13.clientsgrpc.ClientR\aclients\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1e.commongrpc.PaginationResponseR\n" +
	"pagination\"'\n" +
	"\x15ActivateClientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x16ActivateClientResponse\x12+\n" +
	"\x06client\x18\x01 \x01(\v2\x13.clientsgrpc.ClientR\x06client\")\n" +
	"\x17DeactivateClientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"G\n" +
	"\x18DeactivateClientResponse\x12+\n" +
	"\x06client\x18\x01 \x01(\v2\x13.clientsgrpc.ClientR\x06client\"\xd3\x02\n" +
	"\bPlatform\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x122\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1a.commongrpc.PlatformStatusR\x06status\x12B\n" +
	"\fcapabilities\x18\x06 \x03(\x0e2\x1e.commongrpc.ProviderCapabilityR\fcapabilities\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"U\n" +
	"\x14ListPlatformsRequest\x12=\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1d.commongrpc.PaginationRequestR\n" +
	"pagination\"\x8c\x01\n" +
	"\x15ListPlatformsResponse\x123\n" +
	"\tplatforms\x18\x01 \x03(\v2\x15.clientsgrpc.PlatformR\tplatforms\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1e.commongrpc.PaginationResponseR\n" +
	"pagination\"$\n" +
	"\x12GetPlatformRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x13GetPlatformResponse\x121\n" +
	"\bplatform\x18\x01 \x01(\v2\x15.clientsgrpc.PlatformR\bplatform\"'\n" +
	"\x15EnablePlatformRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"K\n" +
	"\x16EnablePlatformResponse\x121\n" +
	"\bplatform\x18\x01 \x01(\v2\x15.clientsgrpc.PlatformR\bplatform\"(\n" +
	"\x16DisablePlatformRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"L\n" +
	"\x17DisablePlatformResponse\x121\n" +
	"\bplatform\x18\x01 \x01(\v2\x15.clientsgrpc.PlatformR\bplatform\"\xb5\x03\n" +
	"\vIntegration\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1f\n" +
	"\vplatform_id\x18\x03 \x01(\tR\n" +
	"platformId\x12.\n" +
	"\x13external_account_id\x18\x04 \x01(\tR\x11externalAccountId\x125\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1d.commongrpc.IntegrationStatusR\x06status\x12=\n" +
	"\finstalled_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vinstalledAt\x12<\n" +
	"\flast_sync_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSyncAt\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x89\x01\n" +
	"\x19InstallIntegrationRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vplatform_id\x18\x02 \x01(\tR\n" +
	"platformId\x12.\n" +
	"\x13external_account_id\x18\x03 \x01(\tR\x11externalAccountId\"X\n" +
	"\x1aInstallIntegrationResponse\x12:\n" +
	"\vintegration\x18\x01 \x01(\v2\x18.clientsgrpc.IntegrationR\vintegration\"-\n" +
	"\x1bUninstallIntegrationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x1cUninstallIntegrationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\x15GetIntegrationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"T\n" +
	"\x16GetIntegrationResponse\x12:\n" +
	"\vintegration\x18\x01 \x01(\v2\x18.clientsgrpc.IntegrationR\vintegration\"\x96\x01\n" +
	"\x17ListIntegrationsRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vplatform_id\x18\x02 \x01(\tR\n" +
	"platformId\x12=\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x1d.commongrpc.PaginationRequestR\n" +
	"pagination\"\x98\x01\n" +
	"\x18ListIntegrationsResponse\x12<\n" +
	"\fintegrations\x18\x01 \x03(\v2\x18.clientsgrpc.IntegrationR\fintegrations\x12>\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1e.commongrpc.PaginationResponseR\n" +
	"pagination\"-\n" +
	"\x1bReconnectIntegrationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Z\n" +
	"\x1cReconnectIntegrationResponse\x12:\n" +
	"\vintegration\x18\x01 \x01(\v2\x18.clientsgrpc.IntegrationR\vintegration\".\n" +
	"\x1cDisconnectIntegrationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"[\n" +
	"\x1dDisconnectIntegrationResponse\x12:\n" +
	"\vintegration\x18\x01 \x01(\v2\x18.clientsgrpc.IntegrationR\vintegration\"(\n" +
	"\x16SyncIntegrationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"U\n" +
	"\x17SyncIntegrationResponse\x12:\n" +
	"\vintegration\x18\x01 \x01(\v2\x18.clientsgrpc.IntegrationR\vintegration\"\x14\n" +
	"\x12HealthCheckRequest\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xe8\x06\n" +
	"\x0eClientsService\x12r\n" +
	"\fCreateClient\x12 .clientsgrpc.CreateClientRequest\x1a!.clientsgrpc.CreateClientResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/public/clients\x12w\n" +
	"\fUpdateClient\x12 .clientsgrpc.UpdateClientRequest\x1a!.clientsgrpc.UpdateClientResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*2\x17/v1/public/clients/{id}\x12t\n" +
	"\fDeleteClient\x12 .clientsgrpc.DeleteClientRequest\x1a!.clientsgrpc.DeleteClientResponse\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/v1/public/clients/{id}\x12k\n" +
	"\tGetClient\x12\x1d.clientsgrpc.GetClientRequest\x1a\x1e.clientsgrpc.GetClientResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/public/clients/{id}\x12l\n" +
	"\vListClients\x12\x1f.clientsgrpc.ListClientsRequest\x1a .clientsgrpc.ListClientsResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/public/clients\x12\x86\x01\n" +
	"\x0eActivateClient\x12\".clientsgrpc.ActivateClientRequest\x1a#.clientsgrpc.ActivateClientResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /v1/public/clients/{id}:activate\x12\x8e\x01\n" +
	"\x10DeactivateClient\x12$.clientsgrpc.DeactivateClientRequest\x1a%.clientsgrpc.DeactivateClientResponse\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/public/clients/{id}:deactivate2\x93\x04\n" +
	"\x10PlatformsService\x12t\n" +
	"\rListPlatforms\x12!.clientsgrpc.ListPlatformsRequest\x1a\".clientsgrpc.ListPlatformsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/public/platforms\x12s\n" +
	"\vGetPlatform\x12\x1f.clientsgrpc.GetPlatformRequest\x1a .clientsgrpc.GetPlatformResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/public/platforms/{id}\x12\x86\x01\n" +
	"\x0eEnablePlatform\x12\".clientsgrpc.EnablePlatformRequest\x1a#.clientsgrpc.EnablePlatformResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /v1/public/platforms/{id}:enable\x12\x8a\x01\n" +
	"\x0fDisablePlatform\x12#.clientsgrpc.DisablePlatformRequest\x1a$.clientsgrpc.DisablePlatformResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/public/platforms/{id}:disable2\xbb\b\n" +
	"\x13IntegrationsService\x12\x89\x01\n" +
	"\x12InstallIntegration\x12&.clientsgrpc.InstallIntegrationRequest\x1a'.clientsgrpc.InstallIntegrationResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/public/integrations\x12\x91\x01\n" +
	"\x14UninstallIntegration\x12(.clientsgrpc.UninstallIntegrationRequest\x1a).clientsgrpc.UninstallIntegrationResponse\"$\x82\xd3\xe4\x93\x02\x1e*\x1c/v1/public/integrations/{id}\x12\x7f\n" +
	"\x0eGetIntegration\x12\".clientsgrpc.GetIntegrationRequest\x1a#.clientsgrpc.GetIntegrationResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/public/integrations/{id}\x12\xaf\x01\n" +
	"\x10ListIntegrations\x12$.clientsgrpc.ListIntegrationsRequest\x1a%.clientsgrpc.ListIntegrationsResponse\"N\x82\xd3\xe4\x93\x02HZ-\x12+/v1/public/clients/{client_id}/integrations\x12\x17/v1/public/integrations\x12\x9e\x01\n" +
	"\x14ReconnectIntegration\x12(.clientsgrpc.ReconnectIntegrationRequest\x1a).clientsgrpc.ReconnectIntegrationResponse\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/v1/public/integrations/{id}:reconnect\x12\xa2\x01\n" +
	"\x15DisconnectIntegration\x12).clientsgrpc.DisconnectIntegrationRequest\x1a*.clientsgrpc.DisconnectIntegrationResponse\"2\x82\xd3\xe4\x93\x02,:\x01*\"'/v1/public/integrations/{id}:disconnect\x12\x8a\x01\n" +
	"\x0fSyncIntegration\x12#.clientsgrpc.SyncIntegrationRequest\x1a$.clientsgrpc.SyncIntegrationResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/public/integrations/{id}:sync2\x89\x01\n" +
	"\rHealthService\x12x\n" +
	"\vHealthCheck\x12\x1f.clientsgrpc.HealthCheckRequest\x1a .clientsgrpc.HealthCheckResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v1/public/clients/healthcheckB5Z3github.com/I-Frostbyte/rvpay-go/grpc/go/clientsgrpcb\x06proto3"

var (
	file_clients_proto_rawDescOnce sync.Once
	file_clients_proto_rawDescData []byte
)

func file_clients_proto_rawDescGZIP() []byte {
	file_clients_proto_rawDescOnce.Do(func() {
		file_clients_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clients_proto_rawDesc), len(file_clients_proto_rawDesc)))
	})
	return file_clients_proto_rawDescData
}

var file_clients_proto_msgTypes = make([]protoimpl.MessageInfo, 41)
var file_clients_proto_goTypes = []any{
	(*Client)(nil),                        // 0: clientsgrpc.Client
	(*CreateClientRequest)(nil),           // 1: clientsgrpc.CreateClientRequest
	(*CreateClientResponse)(nil),          // 2: clientsgrpc.CreateClientResponse
	(*UpdateClientRequest)(nil),           // 3: clientsgrpc.UpdateClientRequest
	(*UpdateClientResponse)(nil),          // 4: clientsgrpc.UpdateClientResponse
	(*DeleteClientRequest)(nil),           // 5: clientsgrpc.DeleteClientRequest
	(*DeleteClientResponse)(nil),          // 6: clientsgrpc.DeleteClientResponse
	(*GetClientRequest)(nil),              // 7: clientsgrpc.GetClientRequest
	(*GetClientResponse)(nil),             // 8: clientsgrpc.GetClientResponse
	(*ListClientsRequest)(nil),            // 9: clientsgrpc.ListClientsRequest
	(*ListClientsResponse)(nil),           // 10: clientsgrpc.ListClientsResponse
	(*ActivateClientRequest)(nil),         // 11: clientsgrpc.ActivateClientRequest
	(*ActivateClientResponse)(nil),        // 12: clientsgrpc.ActivateClientResponse
	(*DeactivateClientRequest)(nil),       // 13: clientsgrpc.DeactivateClientRequest
	(*DeactivateClientResponse)(nil),      // 14: clientsgrpc.DeactivateClientResponse
	(*Platform)(nil),                      // 15: clientsgrpc.Platform
	(*ListPlatformsRequest)(nil),          // 16: clientsgrpc.ListPlatformsRequest
	(*ListPlatformsResponse)(nil),         // 17: clientsgrpc.ListPlatformsResponse
	(*GetPlatformRequest)(nil),            // 18: clientsgrpc.GetPlatformRequest
	(*GetPlatformResponse)(nil),           // 19: clientsgrpc.GetPlatformResponse
	(*EnablePlatformRequest)(nil),         // 20: clientsgrpc.EnablePlatformRequest
	(*EnablePlatformResponse)(nil),        // 21: clientsgrpc.EnablePlatformResponse
	(*DisablePlatformRequest)(nil),        // 22: clientsgrpc.DisablePlatformRequest
	(*DisablePlatformResponse)(nil),       // 23: clientsgrpc.DisablePlatformResponse
	(*Integration)(nil),                   // 24: clientsgrpc.Integration
	(*InstallIntegrationRequest)(nil),     // 25: clientsgrpc.InstallIntegrationRequest
	(*InstallIntegrationResponse)(nil),    // 26: clientsgrpc.InstallIntegrationResponse
	(*UninstallIntegrationRequest)(nil),   // 27: clientsgrpc.UninstallIntegrationRequest
	(*UninstallIntegrationResponse)(nil),  // 28: clientsgrpc.UninstallIntegrationResponse
	(*GetIntegrationRequest)(nil),         // 29: clientsgrpc.GetIntegrationRequest
	(*GetIntegrationResponse)(nil),        // 30: clientsgrpc.GetIntegrationResponse
	(*ListIntegrationsRequest)(nil),       // 31: clientsgrpc.ListIntegrationsRequest
	(*ListIntegrationsResponse)(nil),      // 32: clientsgrpc.ListIntegrationsResponse
	(*ReconnectIntegrationRequest)(nil),   // 33: clientsgrpc.ReconnectIntegrationRequest
	(*ReconnectIntegrationResponse)(nil),  // 34: clientsgrpc.ReconnectIntegrationResponse
	(*DisconnectIntegrationRequest)(nil),  // 35: clientsgrpc.DisconnectIntegrationRequest
	(*DisconnectIntegrationResponse)(nil), // 36: clientsgrpc.DisconnectIntegrationResponse
	(*SyncIntegrationRequest)(nil),        // 37: clientsgrpc.SyncIntegrationRequest
	(*SyncIntegrationResponse)(nil),       // 38: clientsgrpc.SyncIntegrationResponse
	(*HealthCheckRequest)(nil),            // 39: clientsgrpc.HealthCheckRequest
	(*HealthCheckResponse)(nil),           // 40: clientsgrpc.HealthCheckResponse
	(commongrpc.ClientStatus)(0),          // 41: commongrpc.ClientStatus
	(*timestamppb.Timestamp)(nil),         // 42: google.protobuf.Timestamp
	(*commongrpc.PaginationRequest)(nil),  // 43: commongrpc.PaginationRequest
	(*commongrpc.PaginationResponse)(nil), // 44: commongrpc.PaginationResponse
	(commongrpc.PlatformStatus)(0),        // 45: commongrpc.PlatformStatus
	(commongrpc.ProviderCapability)(0),    // 46: commongrpc.ProviderCapability
	(commongrpc.IntegrationStatus)(0),     // 47: commongrpc.IntegrationStatus
}
var file_clients_proto_depIdxs = []int32{
	41, // 0: clientsgrpc.Client.status:type_name -> commongrpc.ClientStatus
	42, // 1: clientsgrpc.Client.created_at:type_name -> google.protobuf.Timestamp
	42, // 2: clientsgrpc.Client.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: clientsgrpc.CreateClientResponse.client:type_name -> clientsgrpc.Client
	0,  // 4: clientsgrpc.UpdateClientResponse.client:type_name -> clientsgrpc.Client
	0,  // 5: clientsgrpc.GetClientResponse.client:type_name -> clientsgrpc.Client
	43, // 6: clientsgrpc.ListClientsRequest.pagination:type_name -> commongrpc.PaginationRequest
	0,  // 7: clientsgrpc.ListClientsResponse.clients:type_name -> clientsgrpc.Client
	44, // 8: clientsgrpc.ListClientsResponse.pagination:type_name -> commongrpc.PaginationResponse
	0,  // 9: clientsgrpc.ActivateClientResponse.client:type_name -> clientsgrpc.Client
	0,  // 10: clientsgrpc.DeactivateClientResponse.client:type_name -> clientsgrpc.Client
	45, // 11: clientsgrpc.Platform.status:type_name -> commongrpc.PlatformStatus
	46, // 12: clientsgrpc.Platform.capabilities:type_name -> commongrpc.ProviderCapability
	42, // 13: clientsgrpc.Platform.created_at:type_name -> google.protobuf.Timestamp
	42, // 14: clientsgrpc.Platform.updated_at:type_name -> google.protobuf.Timestamp
	43, // 15: clientsgrpc.ListPlatformsRequest.pagination:type_name -> commongrpc.PaginationRequest
	15, // 16: clientsgrpc.ListPlatformsResponse.platforms:type_name -> clientsgrpc.Platform
	44, // 17: clientsgrpc.ListPlatformsResponse.pagination:type_name -> commongrpc.PaginationResponse
	15, // 18: clientsgrpc.GetPlatformResponse.platform:type_name -> clientsgrpc.Platform
	15, // 19: clientsgrpc.EnablePlatformResponse.platform:type_name -> clientsgrpc.Platform
	15, // 20: clientsgrpc.DisablePlatformResponse.platform:type_name -> clientsgrpc.Platform
	47, // 21: clientsgrpc.Integration.status:type_name -> commongrpc.IntegrationStatus
	42, // 22: clientsgrpc.Integration.installed_at:type_name -> google.protobuf.Timestamp
	42, // 23: clientsgrpc.Integration.last_sync_at:type_name -> google.protobuf.Timestamp
	42, // 24: clientsgrpc.Integration.created_at:type_name -> google.protobuf.Timestamp
	42, // 25: clientsgrpc.Integration.updated_at:type_name -> google.protobuf.Timestamp
	24, // 26: clientsgrpc.InstallIntegrationResponse.integration:type_name -> clientsgrpc.Integration
	24, // 27: clientsgrpc.GetIntegrationResponse.integration:type_name -> clientsgrpc.Integration
	43, // 28: clientsgrpc.ListIntegrationsRequest.pagination:type_name -> commongrpc.PaginationRequest
	24, // 29: clientsgrpc.ListIntegrationsResponse.integrations:type_name -> clientsgrpc.Integration
	44, // 30: clientsgrpc.ListIntegrationsResponse.pagination:type_name -> commongrpc.PaginationResponse
	24, // 31: clientsgrpc.ReconnectIntegrationResponse.integration:type_name -> clientsgrpc.Integration
	24, // 32: clientsgrpc.DisconnectIntegrationResponse.integration:type_name -> clientsgrpc.Integration
	24, // 33: clientsgrpc.SyncIntegrationResponse.integration:type_name -> clientsgrpc.Integration
	1,  // 34: clientsgrpc.ClientsService.CreateClient:input_type -> clientsgrpc.CreateClientRequest
	3,  // 35: clientsgrpc.ClientsService.UpdateClient:input_type -> clientsgrpc.UpdateClientRequest
	5,  // 36: clientsgrpc.ClientsService.DeleteClient:input_type -> clientsgrpc.DeleteClientRequest
	7,  // 37: clientsgrpc.ClientsService.GetClient:input_type -> clientsgrpc.GetClientRequest
	9,  // 38: clientsgrpc.ClientsService.ListClients:input_type -> clientsgrpc.ListClientsRequest
	11, // 39: clientsgrpc.ClientsService.ActivateClient:input_type -> clientsgrpc.ActivateClientRequest
	13, // 40: clientsgrpc.ClientsService.DeactivateClient:input_type -> clientsgrpc.DeactivateClientRequest
	16, // 41: clientsgrpc.PlatformsService.ListPlatforms:input_type -> clientsgrpc.ListPlatformsRequest
	18, // 42: clientsgrpc.PlatformsService.GetPlatform:input_type -> clientsgrpc.GetPlatformRequest
	20, // 43: clientsgrpc.PlatformsService.EnablePlatform:input_type -> clientsgrpc.EnablePlatformRequest
	22, // 44: clientsgrpc.PlatformsService.DisablePlatform:input_type -> clientsgrpc.DisablePlatformRequest
	25, // 45: clientsgrpc.IntegrationsService.InstallIntegration:input_type -> clientsgrpc.InstallIntegrationRequest
	27, // 46: clientsgrpc.IntegrationsService.UninstallIntegration:input_type -> clientsgrpc.UninstallIntegrationRequest
	29, // 47: clientsgrpc.IntegrationsService.GetIntegration:input_type -> clientsgrpc.GetIntegrationRequest
	31, // 48: clientsgrpc.IntegrationsService.ListIntegrations:input_type -> clientsgrpc.ListIntegrationsRequest
	33, // 49: clientsgrpc.IntegrationsService.ReconnectIntegration:input_type -> clientsgrpc.ReconnectIntegrationRequest
	35, // 50: clientsgrpc.IntegrationsService.DisconnectIntegration:input_type -> clientsgrpc.DisconnectIntegrationRequest
	37, // 51: clientsgrpc.IntegrationsService.SyncIntegration:input_type -> clientsgrpc.SyncIntegrationRequest
	39, // 52: clientsgrpc.HealthService.HealthCheck:input_type -> clientsgrpc.HealthCheckRequest
	2,  // 53: clientsgrpc.ClientsService.CreateClient:output_type -> clientsgrpc.CreateClientResponse
	4,  // 54: clientsgrpc.ClientsService.UpdateClient:output_type -> clientsgrpc.UpdateClientResponse
	6,  // 55: clientsgrpc.ClientsService.DeleteClient:output_type -> clientsgrpc.DeleteClientResponse
	8,  // 56: clientsgrpc.ClientsService.GetClient:output_type -> clientsgrpc.GetClientResponse
	10, // 57: clientsgrpc.ClientsService.ListClients:output_type -> clientsgrpc.ListClientsResponse
	12, // 58: clientsgrpc.ClientsService.ActivateClient:output_type -> clientsgrpc.ActivateClientResponse
	14, // 59: clientsgrpc.ClientsService.DeactivateClient:output_type -> clientsgrpc.DeactivateClientResponse
	17, // 60: clientsgrpc.PlatformsService.ListPlatforms:output_type -> clientsgrpc.ListPlatformsResponse
	19, // 61: clientsgrpc.PlatformsService.GetPlatform:output_type -> clientsgrpc.GetPlatformResponse
	21, // 62: clientsgrpc.PlatformsService.EnablePlatform:output_type -> clientsgrpc.EnablePlatformResponse
	23, // 63: clientsgrpc.PlatformsService.DisablePlatform:output_type -> clientsgrpc.DisablePlatformResponse
	26, // 64: clientsgrpc.IntegrationsService.InstallIntegration:output_type -> clientsgrpc.InstallIntegrationResponse
	28, // 65: clientsgrpc.IntegrationsService.UninstallIntegration:output_type -> clientsgrpc.UninstallIntegrationResponse
	30, // 66: clientsgrpc.IntegrationsService.GetIntegration:output_type -> clientsgrpc.GetIntegrationResponse
	32, // 67: clientsgrpc.IntegrationsService.ListIntegrations:output_type -> clientsgrpc.ListIntegrationsResponse
	34, // 68: clientsgrpc.IntegrationsService.ReconnectIntegration:output_type -> clientsgrpc.ReconnectIntegrationResponse
	36, // 69: clientsgrpc.IntegrationsService.DisconnectIntegration:output_type -> clientsgrpc.DisconnectIntegrationResponse
	38, // 70: clientsgrpc.IntegrationsService.SyncIntegration:output_type -> clientsgrpc.SyncIntegrationResponse
	40, // 71: clientsgrpc.HealthService.HealthCheck:output_type -> clientsgrpc.HealthCheckResponse
	53, // [53:72] is the sub-list for method output_type
	34, // [34:53] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_clients_proto_init() }
func file_clients_proto_init() {
	if File_clients_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clients_proto_rawDesc), len(file_clients_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   41,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_clients_proto_goTypes,
		DependencyIndexes: file_clients_proto_depIdxs,
		MessageInfos:      file_clients_proto_msgTypes,
	}.Build()
	File_clients_proto = out.File
	file_clients_proto_goTypes = nil
	file_clients_proto_depIdxs = nil
}
