// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: integrations.proto

package integrationsgrpc

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Integration struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Provider       string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	LocationId     string                 `protobuf:"bytes,3,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	AccessToken    string                 `protobuf:"bytes,4,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken   string                 `protobuf:"bytes,5,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TokenExpiresAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=token_expires_at,json=tokenExpiresAt,proto3" json:"token_expires_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Integration) Reset() {
	*x = Integration{}
	mi := &file_integrations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Integration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Integration) ProtoMessage() {}

func (x *Integration) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Integration.ProtoReflect.Descriptor instead.
func (*Integration) Descriptor() ([]byte, []int) {
	return file_integrations_proto_rawDescGZIP(), []int{0}
}

func (x *Integration) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Integration) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Integration) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *Integration) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *Integration) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *Integration) GetTokenExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TokenExpiresAt
	}
	return nil
}

func (x *Integration) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Integration) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateIntegrationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Provider       string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	LocationId     string                 `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	AccessToken    string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken   string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TokenExpiresAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=token_expires_at,json=tokenExpiresAt,proto3" json:"token_expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateIntegrationRequest) Reset() {
	*x = CreateIntegrationRequest{}
	mi := &file_integrations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIntegrationRequest) ProtoMessage() {}

func (x *CreateIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIntegrationRequest.ProtoReflect.Descriptor instead.
func (*CreateIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_integrations_proto_rawDescGZIP(), []int{1}
}

func (x *CreateIntegrationRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CreateIntegrationRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *CreateIntegrationRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *CreateIntegrationRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *CreateIntegrationRequest) GetTokenExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TokenExpiresAt
	}
	return nil
}

type CreateIntegrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Integration   *Integration           `protobuf:"bytes,1,opt,name=integration,proto3" json:"integration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIntegrationResponse) Reset() {
	*x = CreateIntegrationResponse{}
	mi := &file_integrations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIntegrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIntegrationResponse) ProtoMessage() {}

func (x *CreateIntegrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIntegrationResponse.ProtoReflect.Descriptor instead.
func (*CreateIntegrationResponse) Descriptor() ([]byte, []int) {
	return file_integrations_proto_rawDescGZIP(), []int{2}
}

func (x *CreateIntegrationResponse) GetIntegration() *Integration {
	if x != nil {
		return x.Integration
	}
	return nil
}

type GetIntegrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIntegrationRequest) Reset() {
	*x = GetIntegrationRequest{}
	mi := &file_integrations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntegrationRequest) ProtoMessage() {}

func (x *GetIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntegrationRequest.ProtoReflect.Descriptor instead.
func (*GetIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_integrations_proto_rawDescGZIP(), []int{3}
}

func (x *GetIntegrationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetIntegrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Integration   *Integration           `protobuf:"bytes,1,opt,name=integration,proto3" json:"integration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIntegrationResponse) Reset() {
	*x = GetIntegrationResponse{}
	mi := &file_integrations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIntegrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntegrationResponse) ProtoMessage() {}

func (x *GetIntegrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntegrationResponse.ProtoReflect.Descriptor instead.
func (*GetIntegrationResponse) Descriptor() ([]byte, []int) {
	return file_integrations_proto_rawDescGZIP(), []int{4}
}

func (x *GetIntegrationResponse) GetIntegration() *Integration {
	if x != nil {
		return x.Integration
	}
	return nil
}

type DeleteIntegrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIntegrationRequest) Reset() {
	*x = DeleteIntegrationRequest{}
	mi := &file_integrations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIntegrationRequest) ProtoMessage() {}

func (x *DeleteIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIntegrationRequest.ProtoReflect.Descriptor instead.
func (*DeleteIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_integrations_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteIntegrationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteIntegrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIntegrationResponse) Reset() {
	*x = DeleteIntegrationResponse{}
	mi := &file_integrations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIntegrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIntegrationResponse) ProtoMessage() {}

func (x *DeleteIntegrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIntegrationResponse.ProtoReflect.Descriptor instead.
func (*DeleteIntegrationResponse) Descriptor() ([]byte, []int) {
	return file_integrations_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteIntegrationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ProcessWebhookEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessWebhookEventRequest) Reset() {
	*x = ProcessWebhookEventRequest{}
	mi := &file_integrations_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessWebhookEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessWebhookEventRequest) ProtoMessage() {}

func (x *ProcessWebhookEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessWebhookEventRequest.ProtoReflect.Descriptor instead.
func (*ProcessWebhookEventRequest) Descriptor() ([]byte, []int) {
	return file_integrations_proto_rawDescGZIP(), []int{7}
}

func (x *ProcessWebhookEventRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ProcessWebhookEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ProcessWebhookEventRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type ProcessWebhookEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Processed     bool                   `protobuf:"varint,2,opt,name=processed,proto3" json:"processed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessWebhookEventResponse) Reset() {
	*x = ProcessWebhookEventResponse{}
	mi := &file_integrations_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessWebhookEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessWebhookEventResponse) ProtoMessage() {}

func (x *ProcessWebhookEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessWebhookEventResponse.ProtoReflect.Descriptor instead.
func (*ProcessWebhookEventResponse) Descriptor() ([]byte, []int) {
	return file_integrations_proto_rawDescGZIP(), []int{8}
}

func (x *ProcessWebhookEventResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProcessWebhookEventResponse) GetProcessed() bool {
	if x != nil {
		return x.Processed
	}
	return false
}

var File_integrations_proto protoreflect.FileDescriptor

const file_integrations_proto_rawDesc = "" +
	"\n" +
	"\x12integrations.proto\x12\x10integrationsgrpc\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\xde\x02\n" +
	"\vIntegration\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x1f\n" +
	"\vlocation_id\x18\x03 \x01(\tR\n" +
	"locationId\x12!\n" +
	"\faccess_token\x18\x04 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x05 \x01(\tR\frefreshToken\x12D\n" +
	"\x10token_expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x0etokenExpiresAt\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe5\x01\n" +
	"\x18CreateIntegrationRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1f\n" +
	"\vlocation_id\x18\x02 \x01(\tR\n" +
	"locationId\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x12D\n" +
	"\x10token_expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0etokenExpiresAt\"\\\n" +
	"\x19CreateIntegrationResponse\x12?\n" +
	"\vintegration\x18\x01 \x01(\v2\x1d.integrationsgrpc.IntegrationR\vintegration\"'\n" +
	"\x15GetIntegrationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Y\n" +
	"\x16GetIntegrationResponse\x12?\n" +
	"\vintegration\x18\x01 \x01(\v2\x1d.integrationsgrpc.IntegrationR\vintegration\"*\n" +
	"\x18DeleteIntegrationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x19DeleteIntegrationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"q\n" +
	"\x1aProcessWebhookEventRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"K\n" +
	"\x1bProcessWebhookEventResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tprocessed\x18\x02 \x01(\bR\tprocessed2\xdd\x04\n" +
	"\x12IntegrationService\x12\x90\x01\n" +
	"\x11CreateIntegration\x12*.integrationsgrpc.CreateIntegrationRequest\x1a+.integrationsgrpc.CreateIntegrationResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/public/integrations\x12\x89\x01\n" +
	"\x0eGetIntegration\x12'.integrationsgrpc.GetIntegrationRequest\x1a(.integrationsgrpc.GetIntegrationResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/public/integrations/{id}\x12\x92\x01\n" +
	"\x11DeleteIntegration\x12*.integrationsgrpc.DeleteIntegrationRequest\x1a+.integrationsgrpc.DeleteIntegrationResponse\"$\x82\xd3\xe4\x93\x02\x1e*\x1c/v1/public/integrations/{id}\x12\x92\x01\n" +
	"\x13ProcessWebhookEvent\x12,.integrationsgrpc.ProcessWebhookEventRequest\x1a-.integrationsgrpc.ProcessWebhookEventResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/public/webhooksB:Z8github.com/I-Frostbyte/rvpay-go/grpc/go/integrationsgrpcb\x06proto3"

var (
	file_integrations_proto_rawDescOnce sync.Once
	file_integrations_proto_rawDescData []byte
)

func file_integrations_proto_rawDescGZIP() []byte {
	file_integrations_proto_rawDescOnce.Do(func() {
		file_integrations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_integrations_proto_rawDesc), len(file_integrations_proto_rawDesc)))
	})
	return file_integrations_proto_rawDescData
}

var file_integrations_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_integrations_proto_goTypes = []any{
	(*Integration)(nil),                 // 0: integrationsgrpc.Integration
	(*CreateIntegrationRequest)(nil),    // 1: integrationsgrpc.CreateIntegrationRequest
	(*CreateIntegrationResponse)(nil),   // 2: integrationsgrpc.CreateIntegrationResponse
	(*GetIntegrationRequest)(nil),       // 3: integrationsgrpc.GetIntegrationRequest
	(*GetIntegrationResponse)(nil),      // 4: integrationsgrpc.GetIntegrationResponse
	(*DeleteIntegrationRequest)(nil),    // 5: integrationsgrpc.DeleteIntegrationRequest
	(*DeleteIntegrationResponse)(nil),   // 6: integrationsgrpc.DeleteIntegrationResponse
	(*ProcessWebhookEventRequest)(nil),  // 7: integrationsgrpc.ProcessWebhookEventRequest
	(*ProcessWebhookEventResponse)(nil), // 8: integrationsgrpc.ProcessWebhookEventResponse
	(*timestamppb.Timestamp)(nil),       // 9: google.protobuf.Timestamp
}
var file_integrations_proto_depIdxs = []int32{
	9,  // 0: integrationsgrpc.Integration.token_expires_at:type_name -> google.protobuf.Timestamp
	9,  // 1: integrationsgrpc.Integration.created_at:type_name -> google.protobuf.Timestamp
	9,  // 2: integrationsgrpc.Integration.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 3: integrationsgrpc.CreateIntegrationRequest.token_expires_at:type_name -> google.protobuf.Timestamp
	0,  // 4: integrationsgrpc.CreateIntegrationResponse.integration:type_name -> integrationsgrpc.Integration
	0,  // 5: integrationsgrpc.GetIntegrationResponse.integration:type_name -> integrationsgrpc.Integration
	1,  // 6: integrationsgrpc.IntegrationService.CreateIntegration:input_type -> integrationsgrpc.CreateIntegrationRequest
	3,  // 7: integrationsgrpc.IntegrationService.GetIntegration:input_type -> integrationsgrpc.GetIntegrationRequest
	5,  // 8: integrationsgrpc.IntegrationService.DeleteIntegration:input_type -> integrationsgrpc.DeleteIntegrationRequest
	7,  // 9: integrationsgrpc.IntegrationService.ProcessWebhookEvent:input_type -> integrationsgrpc.ProcessWebhookEventRequest
	2,  // 10: integrationsgrpc.IntegrationService.CreateIntegration:output_type -> integrationsgrpc.CreateIntegrationResponse
	4,  // 11: integrationsgrpc.IntegrationService.GetIntegration:output_type -> integrationsgrpc.GetIntegrationResponse
	6,  // 12: integrationsgrpc.IntegrationService.DeleteIntegration:output_type -> integrationsgrpc.DeleteIntegrationResponse
	8,  // 13: integrationsgrpc.IntegrationService.ProcessWebhookEvent:output_type -> integrationsgrpc.ProcessWebhookEventResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_integrations_proto_init() }
func file_integrations_proto_init() {
	if File_integrations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_integrations_proto_rawDesc), len(file_integrations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_integrations_proto_goTypes,
		DependencyIndexes: file_integrations_proto_depIdxs,
		MessageInfos:      file_integrations_proto_msgTypes,
	}.Build()
	File_integrations_proto = out.File
	file_integrations_proto_goTypes = nil
	file_integrations_proto_depIdxs = nil
}
