// Code generated by MockGen. DO NOT EDIT.
// Source: ./repo (interfaces: TransactionsRepo,MerchantRepo,CustomerRepo,DepositRepo,PayoutRepo)
//
// Generated by this command:
//
//	mockgen -destination repo/mocks/repo.go -package mocks ./repo TransactionsRepo,MerchantRepo,CustomerRepo,DepositRepo,PayoutRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sqlc "github.com/I-Frostbyte/rvpay-go/transactions/db/sqlc"
	uuid "github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionsRepo is a mock of TransactionsRepo interface.
type MockTransactionsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionsRepoMockRecorder
	isgomock struct{}
}

// MockTransactionsRepoMockRecorder is the mock recorder for MockTransactionsRepo.
type MockTransactionsRepoMockRecorder struct {
	mock *MockTransactionsRepo
}

// NewMockTransactionsRepo creates a new mock instance.
func NewMockTransactionsRepo(ctrl *gomock.Controller) *MockTransactionsRepo {
	mock := &MockTransactionsRepo{ctrl: ctrl}
	mock.recorder = &MockTransactionsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionsRepo) EXPECT() *MockTransactionsRepoMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockTransactionsRepo) Begin(ctx context.Context) (sqlc.Querier, pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(sqlc.Querier)
	ret1, _ := ret[1].(pgx.Tx)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Begin indicates an expected call of Begin.
func (mr *MockTransactionsRepoMockRecorder) Begin(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockTransactionsRepo)(nil).Begin), ctx)
}

// Do mocks base method.
func (m *MockTransactionsRepo) Do() sqlc.Querier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do")
	ret0, _ := ret[0].(sqlc.Querier)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockTransactionsRepoMockRecorder) Do() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockTransactionsRepo)(nil).Do))
}

// MockMerchantRepo is a mock of MerchantRepo interface.
type MockMerchantRepo struct {
	ctrl     *gomock.Controller
	recorder *MockMerchantRepoMockRecorder
	isgomock struct{}
}

// MockMerchantRepoMockRecorder is the mock recorder for MockMerchantRepo.
type MockMerchantRepoMockRecorder struct {
	mock *MockMerchantRepo
}

// NewMockMerchantRepo creates a new mock instance.
func NewMockMerchantRepo(ctrl *gomock.Controller) *MockMerchantRepo {
	mock := &MockMerchantRepo{ctrl: ctrl}
	mock.recorder = &MockMerchantRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMerchantRepo) EXPECT() *MockMerchantRepoMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockMerchantRepo) Count(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockMerchantRepoMockRecorder) Count(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockMerchantRepo)(nil).Count), ctx)
}

// Create mocks base method.
func (m *MockMerchantRepo) Create(ctx context.Context, name, slug string, status sqlc.MerchantStatus) (sqlc.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name, slug, status)
	ret0, _ := ret[0].(sqlc.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMerchantRepoMockRecorder) Create(ctx, name, slug, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMerchantRepo)(nil).Create), ctx, name, slug, status)
}

// GetByID mocks base method.
func (m *MockMerchantRepo) GetByID(ctx context.Context, id uuid.UUID) (sqlc.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(sqlc.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMerchantRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMerchantRepo)(nil).GetByID), ctx, id)
}

// GetBySlug mocks base method.
func (m *MockMerchantRepo) GetBySlug(ctx context.Context, slug string) (sqlc.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySlug", ctx, slug)
	ret0, _ := ret[0].(sqlc.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySlug indicates an expected call of GetBySlug.
func (mr *MockMerchantRepoMockRecorder) GetBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySlug", reflect.TypeOf((*MockMerchantRepo)(nil).GetBySlug), ctx, slug)
}

// List mocks base method.
func (m *MockMerchantRepo) List(ctx context.Context, limit, offset int32) ([]sqlc.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset)
	ret0, _ := ret[0].([]sqlc.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMerchantRepoMockRecorder) List(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMerchantRepo)(nil).List), ctx, limit, offset)
}

// UpdateStatus mocks base method.
func (m *MockMerchantRepo) UpdateStatus(ctx context.Context, id uuid.UUID, status sqlc.MerchantStatus) (sqlc.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(sqlc.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockMerchantRepoMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockMerchantRepo)(nil).UpdateStatus), ctx, id, status)
}

// MockCustomerRepo is a mock of CustomerRepo interface.
type MockCustomerRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerRepoMockRecorder
	isgomock struct{}
}

// MockCustomerRepoMockRecorder is the mock recorder for MockCustomerRepo.
type MockCustomerRepoMockRecorder struct {
	mock *MockCustomerRepo
}

// NewMockCustomerRepo creates a new mock instance.
func NewMockCustomerRepo(ctrl *gomock.Controller) *MockCustomerRepo {
	mock := &MockCustomerRepo{ctrl: ctrl}
	mock.recorder = &MockCustomerRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerRepo) EXPECT() *MockCustomerRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCustomerRepo) Create(ctx context.Context, clientID, merchantID uuid.UUID, phoneNumber string, status sqlc.CustomerStatus) (sqlc.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, clientID, merchantID, phoneNumber, status)
	ret0, _ := ret[0].(sqlc.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCustomerRepoMockRecorder) Create(ctx, clientID, merchantID, phoneNumber, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCustomerRepo)(nil).Create), ctx, clientID, merchantID, phoneNumber, status)
}

// GetByClientAndMerchantAndPhone mocks base method.
func (m *MockCustomerRepo) GetByClientAndMerchantAndPhone(ctx context.Context, clientID, merchantID uuid.UUID, phoneNumber string) (sqlc.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByClientAndMerchantAndPhone", ctx, clientID, merchantID, phoneNumber)
	ret0, _ := ret[0].(sqlc.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByClientAndMerchantAndPhone indicates an expected call of GetByClientAndMerchantAndPhone.
func (mr *MockCustomerRepoMockRecorder) GetByClientAndMerchantAndPhone(ctx, clientID, merchantID, phoneNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByClientAndMerchantAndPhone", reflect.TypeOf((*MockCustomerRepo)(nil).GetByClientAndMerchantAndPhone), ctx, clientID, merchantID, phoneNumber)
}

// GetByID mocks base method.
func (m *MockCustomerRepo) GetByID(ctx context.Context, id uuid.UUID) (sqlc.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(sqlc.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCustomerRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCustomerRepo)(nil).GetByID), ctx, id)
}

// ListByClient mocks base method.
func (m *MockCustomerRepo) ListByClient(ctx context.Context, clientID uuid.UUID) ([]sqlc.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByClient", ctx, clientID)
	ret0, _ := ret[0].([]sqlc.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByClient indicates an expected call of ListByClient.
func (mr *MockCustomerRepoMockRecorder) ListByClient(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByClient", reflect.TypeOf((*MockCustomerRepo)(nil).ListByClient), ctx, clientID)
}

// ListByMerchant mocks base method.
func (m *MockCustomerRepo) ListByMerchant(ctx context.Context, merchantID uuid.UUID) ([]sqlc.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByMerchant", ctx, merchantID)
	ret0, _ := ret[0].([]sqlc.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByMerchant indicates an expected call of ListByMerchant.
func (mr *MockCustomerRepoMockRecorder) ListByMerchant(ctx, merchantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByMerchant", reflect.TypeOf((*MockCustomerRepo)(nil).ListByMerchant), ctx, merchantID)
}

// UpdateStatus mocks base method.
func (m *MockCustomerRepo) UpdateStatus(ctx context.Context, id uuid.UUID, status sqlc.CustomerStatus) (sqlc.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(sqlc.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockCustomerRepoMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockCustomerRepo)(nil).UpdateStatus), ctx, id, status)
}

// MockDepositRepo is a mock of DepositRepo interface.
type MockDepositRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDepositRepoMockRecorder
	isgomock struct{}
}

// MockDepositRepoMockRecorder is the mock recorder for MockDepositRepo.
type MockDepositRepoMockRecorder struct {
	mock *MockDepositRepo
}

// NewMockDepositRepo creates a new mock instance.
func NewMockDepositRepo(ctrl *gomock.Controller) *MockDepositRepo {
	mock := &MockDepositRepo{ctrl: ctrl}
	mock.recorder = &MockDepositRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepositRepo) EXPECT() *MockDepositRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDepositRepo) Create(ctx context.Context, clientName, customerID, merchantID string, amount pgtype.Numeric, currency string, paymentType sqlc.PaymentType, payerPhoneNumber string, provider sqlc.PaymentProvider, status sqlc.DepositStatus, idempotencyKey uuid.UUID, ghlTransactionID string) (sqlc.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, clientName, customerID, merchantID, amount, currency, paymentType, payerPhoneNumber, provider, status, idempotencyKey, ghlTransactionID)
	ret0, _ := ret[0].(sqlc.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDepositRepoMockRecorder) Create(ctx, clientName, customerID, merchantID, amount, currency, paymentType, payerPhoneNumber, provider, status, idempotencyKey, ghlTransactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDepositRepo)(nil).Create), ctx, clientName, customerID, merchantID, amount, currency, paymentType, payerPhoneNumber, provider, status, idempotencyKey, ghlTransactionID)
}

// GetByExternalReference mocks base method.
func (m *MockDepositRepo) GetByExternalReference(ctx context.Context, externalReference string) (sqlc.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByExternalReference", ctx, externalReference)
	ret0, _ := ret[0].(sqlc.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByExternalReference indicates an expected call of GetByExternalReference.
func (mr *MockDepositRepoMockRecorder) GetByExternalReference(ctx, externalReference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByExternalReference", reflect.TypeOf((*MockDepositRepo)(nil).GetByExternalReference), ctx, externalReference)
}

// GetByGHLChargeID mocks base method.
func (m *MockDepositRepo) GetByGHLChargeID(ctx context.Context, ghlChargeID string) (sqlc.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByGHLChargeID", ctx, ghlChargeID)
	ret0, _ := ret[0].(sqlc.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByGHLChargeID indicates an expected call of GetByGHLChargeID.
func (mr *MockDepositRepoMockRecorder) GetByGHLChargeID(ctx, ghlChargeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByGHLChargeID", reflect.TypeOf((*MockDepositRepo)(nil).GetByGHLChargeID), ctx, ghlChargeID)
}

// GetByGHLTransactionID mocks base method.
func (m *MockDepositRepo) GetByGHLTransactionID(ctx context.Context, ghlTransactionID string) (sqlc.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByGHLTransactionID", ctx, ghlTransactionID)
	ret0, _ := ret[0].(sqlc.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByGHLTransactionID indicates an expected call of GetByGHLTransactionID.
func (mr *MockDepositRepoMockRecorder) GetByGHLTransactionID(ctx, ghlTransactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByGHLTransactionID", reflect.TypeOf((*MockDepositRepo)(nil).GetByGHLTransactionID), ctx, ghlTransactionID)
}

// GetByID mocks base method.
func (m *MockDepositRepo) GetByID(ctx context.Context, id uuid.UUID) (sqlc.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(sqlc.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDepositRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDepositRepo)(nil).GetByID), ctx, id)
}

// GetByIdempotencyKey mocks base method.
func (m *MockDepositRepo) GetByIdempotencyKey(ctx context.Context, idempotencyKey uuid.UUID) (sqlc.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIdempotencyKey", ctx, idempotencyKey)
	ret0, _ := ret[0].(sqlc.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIdempotencyKey indicates an expected call of GetByIdempotencyKey.
func (mr *MockDepositRepoMockRecorder) GetByIdempotencyKey(ctx, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIdempotencyKey", reflect.TypeOf((*MockDepositRepo)(nil).GetByIdempotencyKey), ctx, idempotencyKey)
}

// ListByClient mocks base method.
func (m *MockDepositRepo) ListByClient(ctx context.Context, clientName string) ([]sqlc.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByClient", ctx, clientName)
	ret0, _ := ret[0].([]sqlc.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByClient indicates an expected call of ListByClient.
func (mr *MockDepositRepoMockRecorder) ListByClient(ctx, clientName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByClient", reflect.TypeOf((*MockDepositRepo)(nil).ListByClient), ctx, clientName)
}

// ListByCustomer mocks base method.
func (m *MockDepositRepo) ListByCustomer(ctx context.Context, customerID string) ([]sqlc.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByCustomer", ctx, customerID)
	ret0, _ := ret[0].([]sqlc.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByCustomer indicates an expected call of ListByCustomer.
func (mr *MockDepositRepoMockRecorder) ListByCustomer(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByCustomer", reflect.TypeOf((*MockDepositRepo)(nil).ListByCustomer), ctx, customerID)
}

// ListByMerchant mocks base method.
func (m *MockDepositRepo) ListByMerchant(ctx context.Context, merchantID string) ([]sqlc.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByMerchant", ctx, merchantID)
	ret0, _ := ret[0].([]sqlc.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByMerchant indicates an expected call of ListByMerchant.
func (mr *MockDepositRepoMockRecorder) ListByMerchant(ctx, merchantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByMerchant", reflect.TypeOf((*MockDepositRepo)(nil).ListByMerchant), ctx, merchantID)
}

// ListByStatus mocks base method.
func (m *MockDepositRepo) ListByStatus(ctx context.Context, status sqlc.DepositStatus) ([]sqlc.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByStatus", ctx, status)
	ret0, _ := ret[0].([]sqlc.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByStatus indicates an expected call of ListByStatus.
func (mr *MockDepositRepoMockRecorder) ListByStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByStatus", reflect.TypeOf((*MockDepositRepo)(nil).ListByStatus), ctx, status)
}

// MarkCompleted mocks base method.
func (m *MockDepositRepo) MarkCompleted(ctx context.Context, id uuid.UUID, status sqlc.DepositStatus) (sqlc.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkCompleted", ctx, id, status)
	ret0, _ := ret[0].(sqlc.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkCompleted indicates an expected call of MarkCompleted.
func (mr *MockDepositRepoMockRecorder) MarkCompleted(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkCompleted", reflect.TypeOf((*MockDepositRepo)(nil).MarkCompleted), ctx, id, status)
}

// MarkFailed mocks base method.
func (m *MockDepositRepo) MarkFailed(ctx context.Context, id uuid.UUID, status sqlc.DepositStatus, failureReason string) (sqlc.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, id, status, failureReason)
	ret0, _ := ret[0].(sqlc.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockDepositRepoMockRecorder) MarkFailed(ctx, id, status, failureReason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockDepositRepo)(nil).MarkFailed), ctx, id, status, failureReason)
}

// UpdateGHLReference mocks base method.
func (m *MockDepositRepo) UpdateGHLReference(ctx context.Context, id uuid.UUID, ghlTransactionID, ghlChargeID string) (sqlc.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGHLReference", ctx, id, ghlTransactionID, ghlChargeID)
	ret0, _ := ret[0].(sqlc.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGHLReference indicates an expected call of UpdateGHLReference.
func (mr *MockDepositRepoMockRecorder) UpdateGHLReference(ctx, id, ghlTransactionID, ghlChargeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGHLReference", reflect.TypeOf((*MockDepositRepo)(nil).UpdateGHLReference), ctx, id, ghlTransactionID, ghlChargeID)
}

// UpdateStatus mocks base method.
func (m *MockDepositRepo) UpdateStatus(ctx context.Context, id uuid.UUID, status sqlc.DepositStatus) (sqlc.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(sqlc.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockDepositRepoMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockDepositRepo)(nil).UpdateStatus), ctx, id, status)
}

// MockPayoutRepo is a mock of PayoutRepo interface.
type MockPayoutRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPayoutRepoMockRecorder
	isgomock struct{}
}

// MockPayoutRepoMockRecorder is the mock recorder for MockPayoutRepo.
type MockPayoutRepoMockRecorder struct {
	mock *MockPayoutRepo
}

// NewMockPayoutRepo creates a new mock instance.
func NewMockPayoutRepo(ctrl *gomock.Controller) *MockPayoutRepo {
	mock := &MockPayoutRepo{ctrl: ctrl}
	mock.recorder = &MockPayoutRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPayoutRepo) EXPECT() *MockPayoutRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPayoutRepo) Create(ctx context.Context, clientID, merchantID uuid.UUID, amount pgtype.Numeric, currency string, provider sqlc.PaymentProvider, destinationReference string, status sqlc.PayoutStatus, idempotencyKey uuid.UUID) (sqlc.Payout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, clientID, merchantID, amount, currency, provider, destinationReference, status, idempotencyKey)
	ret0, _ := ret[0].(sqlc.Payout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPayoutRepoMockRecorder) Create(ctx, clientID, merchantID, amount, currency, provider, destinationReference, status, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPayoutRepo)(nil).Create), ctx, clientID, merchantID, amount, currency, provider, destinationReference, status, idempotencyKey)
}

// GetByExternalReference mocks base method.
func (m *MockPayoutRepo) GetByExternalReference(ctx context.Context, externalReference string) (sqlc.Payout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByExternalReference", ctx, externalReference)
	ret0, _ := ret[0].(sqlc.Payout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByExternalReference indicates an expected call of GetByExternalReference.
func (mr *MockPayoutRepoMockRecorder) GetByExternalReference(ctx, externalReference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByExternalReference", reflect.TypeOf((*MockPayoutRepo)(nil).GetByExternalReference), ctx, externalReference)
}

// GetByID mocks base method.
func (m *MockPayoutRepo) GetByID(ctx context.Context, id uuid.UUID) (sqlc.Payout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(sqlc.Payout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPayoutRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPayoutRepo)(nil).GetByID), ctx, id)
}

// GetByIdempotencyKey mocks base method.
func (m *MockPayoutRepo) GetByIdempotencyKey(ctx context.Context, idempotencyKey uuid.UUID) (sqlc.Payout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIdempotencyKey", ctx, idempotencyKey)
	ret0, _ := ret[0].(sqlc.Payout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIdempotencyKey indicates an expected call of GetByIdempotencyKey.
func (mr *MockPayoutRepoMockRecorder) GetByIdempotencyKey(ctx, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIdempotencyKey", reflect.TypeOf((*MockPayoutRepo)(nil).GetByIdempotencyKey), ctx, idempotencyKey)
}

// ListByClient mocks base method.
func (m *MockPayoutRepo) ListByClient(ctx context.Context, clientID uuid.UUID) ([]sqlc.Payout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByClient", ctx, clientID)
	ret0, _ := ret[0].([]sqlc.Payout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByClient indicates an expected call of ListByClient.
func (mr *MockPayoutRepoMockRecorder) ListByClient(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByClient", reflect.TypeOf((*MockPayoutRepo)(nil).ListByClient), ctx, clientID)
}

// ListByMerchant mocks base method.
func (m *MockPayoutRepo) ListByMerchant(ctx context.Context, merchantID uuid.UUID) ([]sqlc.Payout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByMerchant", ctx, merchantID)
	ret0, _ := ret[0].([]sqlc.Payout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByMerchant indicates an expected call of ListByMerchant.
func (mr *MockPayoutRepoMockRecorder) ListByMerchant(ctx, merchantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByMerchant", reflect.TypeOf((*MockPayoutRepo)(nil).ListByMerchant), ctx, merchantID)
}

// ListByStatus mocks base method.
func (m *MockPayoutRepo) ListByStatus(ctx context.Context, status sqlc.PayoutStatus) ([]sqlc.Payout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByStatus", ctx, status)
	ret0, _ := ret[0].([]sqlc.Payout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByStatus indicates an expected call of ListByStatus.
func (mr *MockPayoutRepoMockRecorder) ListByStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByStatus", reflect.TypeOf((*MockPayoutRepo)(nil).ListByStatus), ctx, status)
}

// MarkCompleted mocks base method.
func (m *MockPayoutRepo) MarkCompleted(ctx context.Context, id uuid.UUID, status sqlc.PayoutStatus) (sqlc.Payout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkCompleted", ctx, id, status)
	ret0, _ := ret[0].(sqlc.Payout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkCompleted indicates an expected call of MarkCompleted.
func (mr *MockPayoutRepoMockRecorder) MarkCompleted(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkCompleted", reflect.TypeOf((*MockPayoutRepo)(nil).MarkCompleted), ctx, id, status)
}

// MarkFailed mocks base method.
func (m *MockPayoutRepo) MarkFailed(ctx context.Context, id uuid.UUID, status sqlc.PayoutStatus, failureReason string) (sqlc.Payout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, id, status, failureReason)
	ret0, _ := ret[0].(sqlc.Payout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockPayoutRepoMockRecorder) MarkFailed(ctx, id, status, failureReason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockPayoutRepo)(nil).MarkFailed), ctx, id, status, failureReason)
}

// UpdateStatus mocks base method.
func (m *MockPayoutRepo) UpdateStatus(ctx context.Context, id uuid.UUID, status sqlc.PayoutStatus) (sqlc.Payout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(sqlc.Payout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockPayoutRepoMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockPayoutRepo)(nil).UpdateStatus), ctx, id, status)
}
