// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ClientStatus string

const (
	ClientStatusREGISTERED ClientStatus = "REGISTERED"
	ClientStatusACTIVE     ClientStatus = "ACTIVE"
	ClientStatusSUSPENDED  ClientStatus = "SUSPENDED"
	ClientStatusCLOSED     ClientStatus = "CLOSED"
)

func (e *ClientStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ClientStatus(s)
	case string:
		*e = ClientStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ClientStatus: %T", src)
	}
	return nil
}

type NullClientStatus struct {
	ClientStatus ClientStatus `json:"client_status"`
	Valid        bool         `json:"valid"` // Valid is true if ClientStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullClientStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ClientStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ClientStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullClientStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ClientStatus), nil
}

type IntegrationStatus string

const (
	IntegrationStatusCREATED      IntegrationStatus = "CREATED"
	IntegrationStatusOAUTHPENDING IntegrationStatus = "OAUTH_PENDING"
	IntegrationStatusACTIVE       IntegrationStatus = "ACTIVE"
	IntegrationStatusREVOKED      IntegrationStatus = "REVOKED"
)

func (e *IntegrationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IntegrationStatus(s)
	case string:
		*e = IntegrationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for IntegrationStatus: %T", src)
	}
	return nil
}

type NullIntegrationStatus struct {
	IntegrationStatus IntegrationStatus `json:"integration_status"`
	Valid             bool              `json:"valid"` // Valid is true if IntegrationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIntegrationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.IntegrationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IntegrationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIntegrationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IntegrationStatus), nil
}

type UserRole string

const (
	UserRoleUSERROLEUSER  UserRole = "USER_ROLE_USER"
	UserRoleUSERROLEADMIN UserRole = "USER_ROLE_ADMIN"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type WebhookSubscriptionStatus string

const (
	WebhookSubscriptionStatusACTIVE   WebhookSubscriptionStatus = "ACTIVE"
	WebhookSubscriptionStatusDISABLED WebhookSubscriptionStatus = "DISABLED"
)

func (e *WebhookSubscriptionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebhookSubscriptionStatus(s)
	case string:
		*e = WebhookSubscriptionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WebhookSubscriptionStatus: %T", src)
	}
	return nil
}

type NullWebhookSubscriptionStatus struct {
	WebhookSubscriptionStatus WebhookSubscriptionStatus `json:"webhook_subscription_status"`
	Valid                     bool                      `json:"valid"` // Valid is true if WebhookSubscriptionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebhookSubscriptionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WebhookSubscriptionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebhookSubscriptionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebhookSubscriptionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebhookSubscriptionStatus), nil
}

type AccessToken struct {
	ID               uuid.UUID `json:"id"`
	UserID           uuid.UUID `json:"user_id"`
	TokenHash        string    `json:"token_hash"`
	RefreshTokenHash string    `json:"refresh_token_hash"`
	ExpiresAt        time.Time `json:"expires_at"`
	RefreshExpiresAt time.Time `json:"refresh_expires_at"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type Client struct {
	ID         uuid.UUID    `json:"id"`
	ClientName string       `json:"client_name"`
	Status     ClientStatus `json:"status"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
}

type Integration struct {
	ID                uuid.UUID          `json:"id"`
	ClientID          uuid.UUID          `json:"client_id"`
	PlatformID        uuid.UUID          `json:"platform_id"`
	ExternalAccountID string             `json:"external_account_id"`
	Status            IntegrationStatus  `json:"status"`
	InstalledAt       time.Time          `json:"installed_at"`
	LastSyncAt        pgtype.Timestamptz `json:"last_sync_at"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
}

type OauthState struct {
	ID         uuid.UUID          `json:"id"`
	State      string             `json:"state"`
	ClientID   uuid.UUID          `json:"client_id"`
	PlatformID uuid.UUID          `json:"platform_id"`
	ExpiresAt  time.Time          `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  time.Time          `json:"created_at"`
	UpdatedAt  time.Time          `json:"updated_at"`
}

type OauthToken struct {
	ID            uuid.UUID `json:"id"`
	IntegrationID uuid.UUID `json:"integration_id"`
	AccessToken   string    `json:"access_token"`
	RefreshToken  string    `json:"refresh_token"`
	ExpiresAt     time.Time `json:"expires_at"`
	Scope         string    `json:"scope"`
	TokenType     string    `json:"token_type"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type PaymentProviderConfig struct {
	ID                           uuid.UUID `json:"id"`
	IntegrationID                uuid.UUID `json:"integration_id"`
	ProviderName                 string    `json:"provider_name"`
	ProviderDescription          string    `json:"provider_description"`
	ProviderImageUrl             string    `json:"provider_image_url"`
	LocationID                   string    `json:"location_id"`
	QueryUrl                     string    `json:"query_url"`
	PaymentsUrl                  string    `json:"payments_url"`
	SupportsSubscriptionSchedule bool      `json:"supports_subscription_schedule"`
	ProviderApiKey               string    `json:"provider_api_key"`
	CreatedAt                    time.Time `json:"created_at"`
	UpdatedAt                    time.Time `json:"updated_at"`
}

type Platform struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	DisplayName    string    `json:"display_name"`
	Slug           string    `json:"slug"`
	Enabled        bool      `json:"enabled"`
	OauthCapable   bool      `json:"oauth_capable"`
	WebhookCapable bool      `json:"webhook_capable"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type PlatformMetadatum struct {
	ID            uuid.UUID `json:"id"`
	PlatformID    uuid.UUID `json:"platform_id"`
	MetadataKey   string    `json:"metadata_key"`
	MetadataValue string    `json:"metadata_value"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type User struct {
	ID               uuid.UUID `json:"id"`
	Name             string    `json:"name"`
	Email            string    `json:"email"`
	PasswordHash     string    `json:"password_hash"`
	UserRole         UserRole  `json:"user_role"`
	RefreshTokenHash string    `json:"refresh_token_hash"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type WebhookEvent struct {
	ID              uuid.UUID `json:"id"`
	IntegrationID   uuid.UUID `json:"integration_id"`
	ProviderEventID string    `json:"provider_event_id"`
	EventType       string    `json:"event_type"`
	Payload         []byte    `json:"payload"`
	ReceivedAt      time.Time `json:"received_at"`
	CreatedAt       time.Time `json:"created_at"`
}

type WebhookSubscription struct {
	ID            uuid.UUID                 `json:"id"`
	IntegrationID uuid.UUID                 `json:"integration_id"`
	Endpoint      string                    `json:"endpoint"`
	Secret        string                    `json:"secret"`
	Status        WebhookSubscriptionStatus `json:"status"`
	LastDelivery  pgtype.Timestamptz        `json:"last_delivery"`
	CreatedAt     time.Time                 `json:"created_at"`
	UpdatedAt     time.Time                 `json:"updated_at"`
}
