// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: platforms.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countPlatforms = `-- name: CountPlatforms :one
SELECT COUNT(*) FROM platforms
`

func (q *Queries) CountPlatforms(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPlatforms)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlatform = `-- name: CreatePlatform :one
INSERT INTO platforms (name, display_name, slug, enabled, oauth_capable, webhook_capable)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, display_name, slug, enabled, oauth_capable, webhook_capable, created_at, updated_at
`

type CreatePlatformParams struct {
	Name           string `json:"name"`
	DisplayName    string `json:"display_name"`
	Slug           string `json:"slug"`
	Enabled        bool   `json:"enabled"`
	OauthCapable   bool   `json:"oauth_capable"`
	WebhookCapable bool   `json:"webhook_capable"`
}

func (q *Queries) CreatePlatform(ctx context.Context, arg CreatePlatformParams) (Platform, error) {
	row := q.db.QueryRow(ctx, createPlatform,
		arg.Name,
		arg.DisplayName,
		arg.Slug,
		arg.Enabled,
		arg.OauthCapable,
		arg.WebhookCapable,
	)
	var i Platform
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Slug,
		&i.Enabled,
		&i.OauthCapable,
		&i.WebhookCapable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlatform = `-- name: DeletePlatform :execrows
DELETE FROM platforms WHERE id = $1
`

func (q *Queries) DeletePlatform(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlatform, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPlatformByID = `-- name: GetPlatformByID :one
SELECT id, name, display_name, slug, enabled, oauth_capable, webhook_capable, created_at, updated_at
FROM platforms
WHERE id = $1
`

func (q *Queries) GetPlatformByID(ctx context.Context, id uuid.UUID) (Platform, error) {
	row := q.db.QueryRow(ctx, getPlatformByID, id)
	var i Platform
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Slug,
		&i.Enabled,
		&i.OauthCapable,
		&i.WebhookCapable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformByName = `-- name: GetPlatformByName :one
SELECT id, name, display_name, slug, enabled, oauth_capable, webhook_capable, created_at, updated_at
FROM platforms
WHERE name = $1
`

func (q *Queries) GetPlatformByName(ctx context.Context, name string) (Platform, error) {
	row := q.db.QueryRow(ctx, getPlatformByName, name)
	var i Platform
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Slug,
		&i.Enabled,
		&i.OauthCapable,
		&i.WebhookCapable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformBySlug = `-- name: GetPlatformBySlug :one
SELECT id, name, display_name, slug, enabled, oauth_capable, webhook_capable, created_at, updated_at
FROM platforms
WHERE slug = $1
`

func (q *Queries) GetPlatformBySlug(ctx context.Context, slug string) (Platform, error) {
	row := q.db.QueryRow(ctx, getPlatformBySlug, slug)
	var i Platform
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Slug,
		&i.Enabled,
		&i.OauthCapable,
		&i.WebhookCapable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledPlatforms = `-- name: ListEnabledPlatforms :many
SELECT id, name, display_name, slug, enabled, oauth_capable, webhook_capable, created_at, updated_at
FROM platforms
WHERE enabled = TRUE
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListEnabledPlatformsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListEnabledPlatforms(ctx context.Context, arg ListEnabledPlatformsParams) ([]Platform, error) {
	rows, err := q.db.Query(ctx, listEnabledPlatforms, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Platform{}
	for rows.Next() {
		var i Platform
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Slug,
			&i.Enabled,
			&i.OauthCapable,
			&i.WebhookCapable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatforms = `-- name: ListPlatforms :many
SELECT id, name, display_name, slug, enabled, oauth_capable, webhook_capable, created_at, updated_at
FROM platforms
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPlatformsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPlatforms(ctx context.Context, arg ListPlatformsParams) ([]Platform, error) {
	rows, err := q.db.Query(ctx, listPlatforms, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Platform{}
	for rows.Next() {
		var i Platform
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Slug,
			&i.Enabled,
			&i.OauthCapable,
			&i.WebhookCapable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const platformExistsBySlug = `-- name: PlatformExistsBySlug :one
SELECT EXISTS(
    SELECT 1 FROM platforms WHERE slug = $1
)
`

func (q *Queries) PlatformExistsBySlug(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, platformExistsBySlug, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updatePlatform = `-- name: UpdatePlatform :one
UPDATE platforms
SET name = $2,
    display_name = $3,
    slug = $4,
    enabled = $5,
    oauth_capable = $6,
    webhook_capable = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, display_name, slug, enabled, oauth_capable, webhook_capable, created_at, updated_at
`

type UpdatePlatformParams struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	DisplayName    string    `json:"display_name"`
	Slug           string    `json:"slug"`
	Enabled        bool      `json:"enabled"`
	OauthCapable   bool      `json:"oauth_capable"`
	WebhookCapable bool      `json:"webhook_capable"`
}

func (q *Queries) UpdatePlatform(ctx context.Context, arg UpdatePlatformParams) (Platform, error) {
	row := q.db.QueryRow(ctx, updatePlatform,
		arg.ID,
		arg.Name,
		arg.DisplayName,
		arg.Slug,
		arg.Enabled,
		arg.OauthCapable,
		arg.WebhookCapable,
	)
	var i Platform
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Slug,
		&i.Enabled,
		&i.OauthCapable,
		&i.WebhookCapable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
