// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const clearUserRefreshTokenHash = `-- name: ClearUserRefreshTokenHash :exec
UPDATE users
SET refresh_token_hash = '',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ClearUserRefreshTokenHash(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearUserRefreshTokenHash, id)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password_hash, user_role)
VALUES ($1, $2, $3, $4)
RETURNING id, name, email, password_hash, user_role, refresh_token_hash, created_at, updated_at
`

type CreateUserParams struct {
	Name         string   `json:"name"`
	Email        string   `json:"email"`
	PasswordHash string   `json:"password_hash"`
	UserRole     UserRole `json:"user_role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.UserRole,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.UserRole,
		&i.RefreshTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, user_role, refresh_token_hash, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.UserRole,
		&i.RefreshTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password_hash, user_role, refresh_token_hash, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.UserRole,
		&i.RefreshTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserNameEmail = `-- name: UpdateUserNameEmail :one
UPDATE users
SET name = $2,
    email = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, email, password_hash, user_role, refresh_token_hash, created_at, updated_at
`

type UpdateUserNameEmailParams struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Email string    `json:"email"`
}

func (q *Queries) UpdateUserNameEmail(ctx context.Context, arg UpdateUserNameEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserNameEmail, arg.ID, arg.Name, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.UserRole,
		&i.RefreshTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :one
UPDATE users
SET password_hash = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, email, password_hash, user_role, refresh_token_hash, created_at, updated_at
`

type UpdateUserPasswordHashParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPasswordHash, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.UserRole,
		&i.RefreshTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserRefreshTokenHash = `-- name: UpdateUserRefreshTokenHash :exec
UPDATE users
SET refresh_token_hash = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserRefreshTokenHashParams struct {
	ID               uuid.UUID `json:"id"`
	RefreshTokenHash string    `json:"refresh_token_hash"`
}

func (q *Queries) UpdateUserRefreshTokenHash(ctx context.Context, arg UpdateUserRefreshTokenHashParams) error {
	_, err := q.db.Exec(ctx, updateUserRefreshTokenHash, arg.ID, arg.RefreshTokenHash)
	return err
}
