// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: webhook_events.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createWebhookEvent = `-- name: CreateWebhookEvent :one
INSERT INTO webhook_events (integration_id, provider_event_id, event_type, payload)
VALUES ($1, $2, $3, $4)
ON CONFLICT (integration_id, provider_event_id) DO NOTHING
RETURNING id, integration_id, provider_event_id, event_type, payload, received_at, created_at
`

type CreateWebhookEventParams struct {
	IntegrationID   uuid.UUID `json:"integration_id"`
	ProviderEventID string    `json:"provider_event_id"`
	EventType       string    `json:"event_type"`
	Payload         []byte    `json:"payload"`
}

func (q *Queries) CreateWebhookEvent(ctx context.Context, arg CreateWebhookEventParams) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, createWebhookEvent,
		arg.IntegrationID,
		arg.ProviderEventID,
		arg.EventType,
		arg.Payload,
	)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.ProviderEventID,
		&i.EventType,
		&i.Payload,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWebhookEventByIntegrationAndProvider = `-- name: GetWebhookEventByIntegrationAndProvider :one
SELECT id, integration_id, provider_event_id, event_type, payload, received_at, created_at
FROM webhook_events
WHERE integration_id = $1 AND provider_event_id = $2
`

type GetWebhookEventByIntegrationAndProviderParams struct {
	IntegrationID   uuid.UUID `json:"integration_id"`
	ProviderEventID string    `json:"provider_event_id"`
}

func (q *Queries) GetWebhookEventByIntegrationAndProvider(ctx context.Context, arg GetWebhookEventByIntegrationAndProviderParams) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, getWebhookEventByIntegrationAndProvider, arg.IntegrationID, arg.ProviderEventID)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.ProviderEventID,
		&i.EventType,
		&i.Payload,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}
