// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: webhook_subscriptions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countWebhookSubscriptionsByIntegrationID = `-- name: CountWebhookSubscriptionsByIntegrationID :one
SELECT COUNT(*) FROM webhook_subscriptions WHERE integration_id = $1
`

func (q *Queries) CountWebhookSubscriptionsByIntegrationID(ctx context.Context, integrationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhookSubscriptionsByIntegrationID, integrationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebhookSubscription = `-- name: CreateWebhookSubscription :one
INSERT INTO webhook_subscriptions (integration_id, endpoint, secret, status)
VALUES ($1, $2, $3, $4)
RETURNING id, integration_id, endpoint, secret, status, last_delivery, created_at, updated_at
`

type CreateWebhookSubscriptionParams struct {
	IntegrationID uuid.UUID                 `json:"integration_id"`
	Endpoint      string                    `json:"endpoint"`
	Secret        string                    `json:"secret"`
	Status        WebhookSubscriptionStatus `json:"status"`
}

func (q *Queries) CreateWebhookSubscription(ctx context.Context, arg CreateWebhookSubscriptionParams) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, createWebhookSubscription,
		arg.IntegrationID,
		arg.Endpoint,
		arg.Secret,
		arg.Status,
	)
	var i WebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.Endpoint,
		&i.Secret,
		&i.Status,
		&i.LastDelivery,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebhookSubscription = `-- name: DeleteWebhookSubscription :execrows
DELETE FROM webhook_subscriptions WHERE id = $1
`

func (q *Queries) DeleteWebhookSubscription(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebhookSubscription, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWebhookSubscriptionByID = `-- name: GetWebhookSubscriptionByID :one
SELECT id, integration_id, endpoint, secret, status, last_delivery, created_at, updated_at
FROM webhook_subscriptions
WHERE id = $1
`

func (q *Queries) GetWebhookSubscriptionByID(ctx context.Context, id uuid.UUID) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, getWebhookSubscriptionByID, id)
	var i WebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.Endpoint,
		&i.Secret,
		&i.Status,
		&i.LastDelivery,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookSubscriptionByIntegrationIDAndEndpoint = `-- name: GetWebhookSubscriptionByIntegrationIDAndEndpoint :one
SELECT id, integration_id, endpoint, secret, status, last_delivery, created_at, updated_at
FROM webhook_subscriptions
WHERE integration_id = $1 AND endpoint = $2
`

type GetWebhookSubscriptionByIntegrationIDAndEndpointParams struct {
	IntegrationID uuid.UUID `json:"integration_id"`
	Endpoint      string    `json:"endpoint"`
}

func (q *Queries) GetWebhookSubscriptionByIntegrationIDAndEndpoint(ctx context.Context, arg GetWebhookSubscriptionByIntegrationIDAndEndpointParams) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, getWebhookSubscriptionByIntegrationIDAndEndpoint, arg.IntegrationID, arg.Endpoint)
	var i WebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.Endpoint,
		&i.Secret,
		&i.Status,
		&i.LastDelivery,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveWebhookSubscriptionsByIntegrationID = `-- name: ListActiveWebhookSubscriptionsByIntegrationID :many
SELECT id, integration_id, endpoint, secret, status, last_delivery, created_at, updated_at
FROM webhook_subscriptions
WHERE integration_id = $1 AND status = 'ACTIVE'
ORDER BY created_at DESC
`

func (q *Queries) ListActiveWebhookSubscriptionsByIntegrationID(ctx context.Context, integrationID uuid.UUID) ([]WebhookSubscription, error) {
	rows, err := q.db.Query(ctx, listActiveWebhookSubscriptionsByIntegrationID, integrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookSubscription{}
	for rows.Next() {
		var i WebhookSubscription
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.Endpoint,
			&i.Secret,
			&i.Status,
			&i.LastDelivery,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookSubscriptionsByIntegrationID = `-- name: ListWebhookSubscriptionsByIntegrationID :many
SELECT id, integration_id, endpoint, secret, status, last_delivery, created_at, updated_at
FROM webhook_subscriptions
WHERE integration_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWebhookSubscriptionsByIntegrationIDParams struct {
	IntegrationID uuid.UUID `json:"integration_id"`
	Limit         int32     `json:"limit"`
	Offset        int32     `json:"offset"`
}

func (q *Queries) ListWebhookSubscriptionsByIntegrationID(ctx context.Context, arg ListWebhookSubscriptionsByIntegrationIDParams) ([]WebhookSubscription, error) {
	rows, err := q.db.Query(ctx, listWebhookSubscriptionsByIntegrationID, arg.IntegrationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookSubscription{}
	for rows.Next() {
		var i WebhookSubscription
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.Endpoint,
			&i.Secret,
			&i.Status,
			&i.LastDelivery,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhookSubscriptionLastDelivery = `-- name: UpdateWebhookSubscriptionLastDelivery :one
UPDATE webhook_subscriptions
SET last_delivery = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, integration_id, endpoint, secret, status, last_delivery, created_at, updated_at
`

type UpdateWebhookSubscriptionLastDeliveryParams struct {
	ID           uuid.UUID          `json:"id"`
	LastDelivery pgtype.Timestamptz `json:"last_delivery"`
}

func (q *Queries) UpdateWebhookSubscriptionLastDelivery(ctx context.Context, arg UpdateWebhookSubscriptionLastDeliveryParams) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, updateWebhookSubscriptionLastDelivery, arg.ID, arg.LastDelivery)
	var i WebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.Endpoint,
		&i.Secret,
		&i.Status,
		&i.LastDelivery,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWebhookSubscriptionStatus = `-- name: UpdateWebhookSubscriptionStatus :one
UPDATE webhook_subscriptions
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, integration_id, endpoint, secret, status, last_delivery, created_at, updated_at
`

type UpdateWebhookSubscriptionStatusParams struct {
	ID     uuid.UUID                 `json:"id"`
	Status WebhookSubscriptionStatus `json:"status"`
}

func (q *Queries) UpdateWebhookSubscriptionStatus(ctx context.Context, arg UpdateWebhookSubscriptionStatusParams) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, updateWebhookSubscriptionStatus, arg.ID, arg.Status)
	var i WebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.Endpoint,
		&i.Secret,
		&i.Status,
		&i.LastDelivery,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const webhookSubscriptionExists = `-- name: WebhookSubscriptionExists :one
SELECT EXISTS(
    SELECT 1 FROM webhook_subscriptions WHERE integration_id = $1 AND endpoint = $2
)
`

type WebhookSubscriptionExistsParams struct {
	IntegrationID uuid.UUID `json:"integration_id"`
	Endpoint      string    `json:"endpoint"`
}

func (q *Queries) WebhookSubscriptionExists(ctx context.Context, arg WebhookSubscriptionExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, webhookSubscriptionExists, arg.IntegrationID, arg.Endpoint)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
