// Code generated by MockGen. DO NOT EDIT.
// Source: ./sqlc (interfaces: Querier)
//
// Generated by this command:
//
//	mockgen -destination sqlc/mocks/querier.go -package mocks ./sqlc Querier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sqlc "github.com/I-Frostbyte/rvpay-go/transactions/db/sqlc"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// CountMerchants mocks base method.
func (m *MockQuerier) CountMerchants(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountMerchants", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountMerchants indicates an expected call of CountMerchants.
func (mr *MockQuerierMockRecorder) CountMerchants(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountMerchants", reflect.TypeOf((*MockQuerier)(nil).CountMerchants), ctx)
}

// CreateCustomer mocks base method.
func (m *MockQuerier) CreateCustomer(ctx context.Context, arg sqlc.CreateCustomerParams) (sqlc.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomer", ctx, arg)
	ret0, _ := ret[0].(sqlc.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCustomer indicates an expected call of CreateCustomer.
func (mr *MockQuerierMockRecorder) CreateCustomer(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomer", reflect.TypeOf((*MockQuerier)(nil).CreateCustomer), ctx, arg)
}

// CreateDeposit mocks base method.
func (m *MockQuerier) CreateDeposit(ctx context.Context, arg sqlc.CreateDepositParams) (sqlc.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDeposit", ctx, arg)
	ret0, _ := ret[0].(sqlc.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDeposit indicates an expected call of CreateDeposit.
func (mr *MockQuerierMockRecorder) CreateDeposit(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDeposit", reflect.TypeOf((*MockQuerier)(nil).CreateDeposit), ctx, arg)
}

// CreateMerchant mocks base method.
func (m *MockQuerier) CreateMerchant(ctx context.Context, arg sqlc.CreateMerchantParams) (sqlc.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMerchant", ctx, arg)
	ret0, _ := ret[0].(sqlc.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMerchant indicates an expected call of CreateMerchant.
func (mr *MockQuerierMockRecorder) CreateMerchant(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMerchant", reflect.TypeOf((*MockQuerier)(nil).CreateMerchant), ctx, arg)
}

// CreatePayout mocks base method.
func (m *MockQuerier) CreatePayout(ctx context.Context, arg sqlc.CreatePayoutParams) (sqlc.Payout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayout", ctx, arg)
	ret0, _ := ret[0].(sqlc.Payout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePayout indicates an expected call of CreatePayout.
func (mr *MockQuerierMockRecorder) CreatePayout(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayout", reflect.TypeOf((*MockQuerier)(nil).CreatePayout), ctx, arg)
}

// GetCustomerByClientAndMerchantAndPhone mocks base method.
func (m *MockQuerier) GetCustomerByClientAndMerchantAndPhone(ctx context.Context, arg sqlc.GetCustomerByClientAndMerchantAndPhoneParams) (sqlc.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerByClientAndMerchantAndPhone", ctx, arg)
	ret0, _ := ret[0].(sqlc.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomerByClientAndMerchantAndPhone indicates an expected call of GetCustomerByClientAndMerchantAndPhone.
func (mr *MockQuerierMockRecorder) GetCustomerByClientAndMerchantAndPhone(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerByClientAndMerchantAndPhone", reflect.TypeOf((*MockQuerier)(nil).GetCustomerByClientAndMerchantAndPhone), ctx, arg)
}

// GetCustomerByID mocks base method.
func (m *MockQuerier) GetCustomerByID(ctx context.Context, id uuid.UUID) (sqlc.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerByID", ctx, id)
	ret0, _ := ret[0].(sqlc.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomerByID indicates an expected call of GetCustomerByID.
func (mr *MockQuerierMockRecorder) GetCustomerByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerByID", reflect.TypeOf((*MockQuerier)(nil).GetCustomerByID), ctx, id)
}

// GetDepositByExternalReference mocks base method.
func (m *MockQuerier) GetDepositByExternalReference(ctx context.Context, externalReference string) (sqlc.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepositByExternalReference", ctx, externalReference)
	ret0, _ := ret[0].(sqlc.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepositByExternalReference indicates an expected call of GetDepositByExternalReference.
func (mr *MockQuerierMockRecorder) GetDepositByExternalReference(ctx, externalReference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepositByExternalReference", reflect.TypeOf((*MockQuerier)(nil).GetDepositByExternalReference), ctx, externalReference)
}

// GetDepositByGHLChargeID mocks base method.
func (m *MockQuerier) GetDepositByGHLChargeID(ctx context.Context, ghlChargeID string) (sqlc.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepositByGHLChargeID", ctx, ghlChargeID)
	ret0, _ := ret[0].(sqlc.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepositByGHLChargeID indicates an expected call of GetDepositByGHLChargeID.
func (mr *MockQuerierMockRecorder) GetDepositByGHLChargeID(ctx, ghlChargeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepositByGHLChargeID", reflect.TypeOf((*MockQuerier)(nil).GetDepositByGHLChargeID), ctx, ghlChargeID)
}

// GetDepositByGHLTransactionID mocks base method.
func (m *MockQuerier) GetDepositByGHLTransactionID(ctx context.Context, ghlTransactionID string) (sqlc.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepositByGHLTransactionID", ctx, ghlTransactionID)
	ret0, _ := ret[0].(sqlc.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepositByGHLTransactionID indicates an expected call of GetDepositByGHLTransactionID.
func (mr *MockQuerierMockRecorder) GetDepositByGHLTransactionID(ctx, ghlTransactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepositByGHLTransactionID", reflect.TypeOf((*MockQuerier)(nil).GetDepositByGHLTransactionID), ctx, ghlTransactionID)
}

// GetDepositByID mocks base method.
func (m *MockQuerier) GetDepositByID(ctx context.Context, id uuid.UUID) (sqlc.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepositByID", ctx, id)
	ret0, _ := ret[0].(sqlc.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepositByID indicates an expected call of GetDepositByID.
func (mr *MockQuerierMockRecorder) GetDepositByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepositByID", reflect.TypeOf((*MockQuerier)(nil).GetDepositByID), ctx, id)
}

// GetDepositByIdempotencyKey mocks base method.
func (m *MockQuerier) GetDepositByIdempotencyKey(ctx context.Context, idempotencyKey uuid.UUID) (sqlc.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepositByIdempotencyKey", ctx, idempotencyKey)
	ret0, _ := ret[0].(sqlc.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepositByIdempotencyKey indicates an expected call of GetDepositByIdempotencyKey.
func (mr *MockQuerierMockRecorder) GetDepositByIdempotencyKey(ctx, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepositByIdempotencyKey", reflect.TypeOf((*MockQuerier)(nil).GetDepositByIdempotencyKey), ctx, idempotencyKey)
}

// GetMerchantByID mocks base method.
func (m *MockQuerier) GetMerchantByID(ctx context.Context, id uuid.UUID) (sqlc.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMerchantByID", ctx, id)
	ret0, _ := ret[0].(sqlc.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMerchantByID indicates an expected call of GetMerchantByID.
func (mr *MockQuerierMockRecorder) GetMerchantByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMerchantByID", reflect.TypeOf((*MockQuerier)(nil).GetMerchantByID), ctx, id)
}

// GetMerchantBySlug mocks base method.
func (m *MockQuerier) GetMerchantBySlug(ctx context.Context, slug string) (sqlc.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMerchantBySlug", ctx, slug)
	ret0, _ := ret[0].(sqlc.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMerchantBySlug indicates an expected call of GetMerchantBySlug.
func (mr *MockQuerierMockRecorder) GetMerchantBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMerchantBySlug", reflect.TypeOf((*MockQuerier)(nil).GetMerchantBySlug), ctx, slug)
}

// GetPayoutByExternalReference mocks base method.
func (m *MockQuerier) GetPayoutByExternalReference(ctx context.Context, externalReference string) (sqlc.Payout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayoutByExternalReference", ctx, externalReference)
	ret0, _ := ret[0].(sqlc.Payout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPayoutByExternalReference indicates an expected call of GetPayoutByExternalReference.
func (mr *MockQuerierMockRecorder) GetPayoutByExternalReference(ctx, externalReference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayoutByExternalReference", reflect.TypeOf((*MockQuerier)(nil).GetPayoutByExternalReference), ctx, externalReference)
}

// GetPayoutByID mocks base method.
func (m *MockQuerier) GetPayoutByID(ctx context.Context, id uuid.UUID) (sqlc.Payout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayoutByID", ctx, id)
	ret0, _ := ret[0].(sqlc.Payout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPayoutByID indicates an expected call of GetPayoutByID.
func (mr *MockQuerierMockRecorder) GetPayoutByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayoutByID", reflect.TypeOf((*MockQuerier)(nil).GetPayoutByID), ctx, id)
}

// GetPayoutByIdempotencyKey mocks base method.
func (m *MockQuerier) GetPayoutByIdempotencyKey(ctx context.Context, idempotencyKey uuid.UUID) (sqlc.Payout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayoutByIdempotencyKey", ctx, idempotencyKey)
	ret0, _ := ret[0].(sqlc.Payout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPayoutByIdempotencyKey indicates an expected call of GetPayoutByIdempotencyKey.
func (mr *MockQuerierMockRecorder) GetPayoutByIdempotencyKey(ctx, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayoutByIdempotencyKey", reflect.TypeOf((*MockQuerier)(nil).GetPayoutByIdempotencyKey), ctx, idempotencyKey)
}

// ListCustomersByClient mocks base method.
func (m *MockQuerier) ListCustomersByClient(ctx context.Context, clientID uuid.UUID) ([]sqlc.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCustomersByClient", ctx, clientID)
	ret0, _ := ret[0].([]sqlc.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCustomersByClient indicates an expected call of ListCustomersByClient.
func (mr *MockQuerierMockRecorder) ListCustomersByClient(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCustomersByClient", reflect.TypeOf((*MockQuerier)(nil).ListCustomersByClient), ctx, clientID)
}

// ListCustomersByMerchant mocks base method.
func (m *MockQuerier) ListCustomersByMerchant(ctx context.Context, merchantID uuid.UUID) ([]sqlc.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCustomersByMerchant", ctx, merchantID)
	ret0, _ := ret[0].([]sqlc.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCustomersByMerchant indicates an expected call of ListCustomersByMerchant.
func (mr *MockQuerierMockRecorder) ListCustomersByMerchant(ctx, merchantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCustomersByMerchant", reflect.TypeOf((*MockQuerier)(nil).ListCustomersByMerchant), ctx, merchantID)
}

// ListDepositsByClient mocks base method.
func (m *MockQuerier) ListDepositsByClient(ctx context.Context, clientName string) ([]sqlc.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDepositsByClient", ctx, clientName)
	ret0, _ := ret[0].([]sqlc.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDepositsByClient indicates an expected call of ListDepositsByClient.
func (mr *MockQuerierMockRecorder) ListDepositsByClient(ctx, clientName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDepositsByClient", reflect.TypeOf((*MockQuerier)(nil).ListDepositsByClient), ctx, clientName)
}

// ListDepositsByCustomer mocks base method.
func (m *MockQuerier) ListDepositsByCustomer(ctx context.Context, customerID string) ([]sqlc.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDepositsByCustomer", ctx, customerID)
	ret0, _ := ret[0].([]sqlc.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDepositsByCustomer indicates an expected call of ListDepositsByCustomer.
func (mr *MockQuerierMockRecorder) ListDepositsByCustomer(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDepositsByCustomer", reflect.TypeOf((*MockQuerier)(nil).ListDepositsByCustomer), ctx, customerID)
}

// ListDepositsByMerchant mocks base method.
func (m *MockQuerier) ListDepositsByMerchant(ctx context.Context, merchantID string) ([]sqlc.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDepositsByMerchant", ctx, merchantID)
	ret0, _ := ret[0].([]sqlc.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDepositsByMerchant indicates an expected call of ListDepositsByMerchant.
func (mr *MockQuerierMockRecorder) ListDepositsByMerchant(ctx, merchantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDepositsByMerchant", reflect.TypeOf((*MockQuerier)(nil).ListDepositsByMerchant), ctx, merchantID)
}

// ListDepositsByStatus mocks base method.
func (m *MockQuerier) ListDepositsByStatus(ctx context.Context, status sqlc.DepositStatus) ([]sqlc.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDepositsByStatus", ctx, status)
	ret0, _ := ret[0].([]sqlc.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDepositsByStatus indicates an expected call of ListDepositsByStatus.
func (mr *MockQuerierMockRecorder) ListDepositsByStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDepositsByStatus", reflect.TypeOf((*MockQuerier)(nil).ListDepositsByStatus), ctx, status)
}

// ListMerchants mocks base method.
func (m *MockQuerier) ListMerchants(ctx context.Context, arg sqlc.ListMerchantsParams) ([]sqlc.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMerchants", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMerchants indicates an expected call of ListMerchants.
func (mr *MockQuerierMockRecorder) ListMerchants(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMerchants", reflect.TypeOf((*MockQuerier)(nil).ListMerchants), ctx, arg)
}

// ListPayoutsByClient mocks base method.
func (m *MockQuerier) ListPayoutsByClient(ctx context.Context, clientID uuid.UUID) ([]sqlc.Payout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPayoutsByClient", ctx, clientID)
	ret0, _ := ret[0].([]sqlc.Payout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPayoutsByClient indicates an expected call of ListPayoutsByClient.
func (mr *MockQuerierMockRecorder) ListPayoutsByClient(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPayoutsByClient", reflect.TypeOf((*MockQuerier)(nil).ListPayoutsByClient), ctx, clientID)
}

// ListPayoutsByMerchant mocks base method.
func (m *MockQuerier) ListPayoutsByMerchant(ctx context.Context, merchantID uuid.UUID) ([]sqlc.Payout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPayoutsByMerchant", ctx, merchantID)
	ret0, _ := ret[0].([]sqlc.Payout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPayoutsByMerchant indicates an expected call of ListPayoutsByMerchant.
func (mr *MockQuerierMockRecorder) ListPayoutsByMerchant(ctx, merchantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPayoutsByMerchant", reflect.TypeOf((*MockQuerier)(nil).ListPayoutsByMerchant), ctx, merchantID)
}

// ListPayoutsByStatus mocks base method.
func (m *MockQuerier) ListPayoutsByStatus(ctx context.Context, status sqlc.PayoutStatus) ([]sqlc.Payout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPayoutsByStatus", ctx, status)
	ret0, _ := ret[0].([]sqlc.Payout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPayoutsByStatus indicates an expected call of ListPayoutsByStatus.
func (mr *MockQuerierMockRecorder) ListPayoutsByStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPayoutsByStatus", reflect.TypeOf((*MockQuerier)(nil).ListPayoutsByStatus), ctx, status)
}

// UpdateCustomerStatus mocks base method.
func (m *MockQuerier) UpdateCustomerStatus(ctx context.Context, arg sqlc.UpdateCustomerStatusParams) (sqlc.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomerStatus", ctx, arg)
	ret0, _ := ret[0].(sqlc.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCustomerStatus indicates an expected call of UpdateCustomerStatus.
func (mr *MockQuerierMockRecorder) UpdateCustomerStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomerStatus", reflect.TypeOf((*MockQuerier)(nil).UpdateCustomerStatus), ctx, arg)
}

// UpdateDepositGHLReference mocks base method.
func (m *MockQuerier) UpdateDepositGHLReference(ctx context.Context, arg sqlc.UpdateDepositGHLReferenceParams) (sqlc.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDepositGHLReference", ctx, arg)
	ret0, _ := ret[0].(sqlc.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDepositGHLReference indicates an expected call of UpdateDepositGHLReference.
func (mr *MockQuerierMockRecorder) UpdateDepositGHLReference(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDepositGHLReference", reflect.TypeOf((*MockQuerier)(nil).UpdateDepositGHLReference), ctx, arg)
}

// UpdateDepositStatus mocks base method.
func (m *MockQuerier) UpdateDepositStatus(ctx context.Context, arg sqlc.UpdateDepositStatusParams) (sqlc.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDepositStatus", ctx, arg)
	ret0, _ := ret[0].(sqlc.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDepositStatus indicates an expected call of UpdateDepositStatus.
func (mr *MockQuerierMockRecorder) UpdateDepositStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDepositStatus", reflect.TypeOf((*MockQuerier)(nil).UpdateDepositStatus), ctx, arg)
}

// UpdateDepositStatusAndCompletedAt mocks base method.
func (m *MockQuerier) UpdateDepositStatusAndCompletedAt(ctx context.Context, arg sqlc.UpdateDepositStatusAndCompletedAtParams) (sqlc.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDepositStatusAndCompletedAt", ctx, arg)
	ret0, _ := ret[0].(sqlc.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDepositStatusAndCompletedAt indicates an expected call of UpdateDepositStatusAndCompletedAt.
func (mr *MockQuerierMockRecorder) UpdateDepositStatusAndCompletedAt(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDepositStatusAndCompletedAt", reflect.TypeOf((*MockQuerier)(nil).UpdateDepositStatusAndCompletedAt), ctx, arg)
}

// UpdateDepositStatusAndFailedAt mocks base method.
func (m *MockQuerier) UpdateDepositStatusAndFailedAt(ctx context.Context, arg sqlc.UpdateDepositStatusAndFailedAtParams) (sqlc.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDepositStatusAndFailedAt", ctx, arg)
	ret0, _ := ret[0].(sqlc.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDepositStatusAndFailedAt indicates an expected call of UpdateDepositStatusAndFailedAt.
func (mr *MockQuerierMockRecorder) UpdateDepositStatusAndFailedAt(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDepositStatusAndFailedAt", reflect.TypeOf((*MockQuerier)(nil).UpdateDepositStatusAndFailedAt), ctx, arg)
}

// UpdateMerchantStatus mocks base method.
func (m *MockQuerier) UpdateMerchantStatus(ctx context.Context, arg sqlc.UpdateMerchantStatusParams) (sqlc.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMerchantStatus", ctx, arg)
	ret0, _ := ret[0].(sqlc.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMerchantStatus indicates an expected call of UpdateMerchantStatus.
func (mr *MockQuerierMockRecorder) UpdateMerchantStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMerchantStatus", reflect.TypeOf((*MockQuerier)(nil).UpdateMerchantStatus), ctx, arg)
}

// UpdatePayoutStatus mocks base method.
func (m *MockQuerier) UpdatePayoutStatus(ctx context.Context, arg sqlc.UpdatePayoutStatusParams) (sqlc.Payout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePayoutStatus", ctx, arg)
	ret0, _ := ret[0].(sqlc.Payout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePayoutStatus indicates an expected call of UpdatePayoutStatus.
func (mr *MockQuerierMockRecorder) UpdatePayoutStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePayoutStatus", reflect.TypeOf((*MockQuerier)(nil).UpdatePayoutStatus), ctx, arg)
}

// UpdatePayoutStatusAndCompletedAt mocks base method.
func (m *MockQuerier) UpdatePayoutStatusAndCompletedAt(ctx context.Context, arg sqlc.UpdatePayoutStatusAndCompletedAtParams) (sqlc.Payout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePayoutStatusAndCompletedAt", ctx, arg)
	ret0, _ := ret[0].(sqlc.Payout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePayoutStatusAndCompletedAt indicates an expected call of UpdatePayoutStatusAndCompletedAt.
func (mr *MockQuerierMockRecorder) UpdatePayoutStatusAndCompletedAt(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePayoutStatusAndCompletedAt", reflect.TypeOf((*MockQuerier)(nil).UpdatePayoutStatusAndCompletedAt), ctx, arg)
}

// UpdatePayoutStatusAndFailedAt mocks base method.
func (m *MockQuerier) UpdatePayoutStatusAndFailedAt(ctx context.Context, arg sqlc.UpdatePayoutStatusAndFailedAtParams) (sqlc.Payout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePayoutStatusAndFailedAt", ctx, arg)
	ret0, _ := ret[0].(sqlc.Payout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePayoutStatusAndFailedAt indicates an expected call of UpdatePayoutStatusAndFailedAt.
func (mr *MockQuerierMockRecorder) UpdatePayoutStatusAndFailedAt(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePayoutStatusAndFailedAt", reflect.TypeOf((*MockQuerier)(nil).UpdatePayoutStatusAndFailedAt), ctx, arg)
}
