// Code generated by MockGen. DO NOT EDIT.
// Source: ./repo (interfaces: OAuthStateRepo)
//
// Generated by this command:
//
//	mockgen -destination repo/mocks/oauth_state_repo.go -package mocks ./repo OAuthStateRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	sqlc "github.com/MountainHubTech/rvpay-go/clients/db/sqlc"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockOAuthStateRepo is a mock of OAuthStateRepo interface.
type MockOAuthStateRepo struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthStateRepoMockRecorder
	isgomock struct{}
}

// MockOAuthStateRepoMockRecorder is the mock recorder for MockOAuthStateRepo.
type MockOAuthStateRepoMockRecorder struct {
	mock *MockOAuthStateRepo
}

// NewMockOAuthStateRepo creates a new mock instance.
func NewMockOAuthStateRepo(ctrl *gomock.Controller) *MockOAuthStateRepo {
	mock := &MockOAuthStateRepo{ctrl: ctrl}
	mock.recorder = &MockOAuthStateRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthStateRepo) EXPECT() *MockOAuthStateRepoMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockOAuthStateRepo) Consume(ctx context.Context, state string) (sqlc.OauthState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, state)
	ret0, _ := ret[0].(sqlc.OauthState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Consume indicates an expected call of Consume.
func (mr *MockOAuthStateRepoMockRecorder) Consume(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockOAuthStateRepo)(nil).Consume), ctx, state)
}

// Create mocks base method.
func (m *MockOAuthStateRepo) Create(ctx context.Context, state string, clientID, platformID uuid.UUID, expiresAt time.Time) (sqlc.OauthState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, state, clientID, platformID, expiresAt)
	ret0, _ := ret[0].(sqlc.OauthState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOAuthStateRepoMockRecorder) Create(ctx, state, clientID, platformID, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOAuthStateRepo)(nil).Create), ctx, state, clientID, platformID, expiresAt)
}

// DeleteExpired mocks base method.
func (m *MockOAuthStateRepo) DeleteExpired(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockOAuthStateRepoMockRecorder) DeleteExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockOAuthStateRepo)(nil).DeleteExpired), ctx)
}

// GetByState mocks base method.
func (m *MockOAuthStateRepo) GetByState(ctx context.Context, state string) (sqlc.OauthState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByState", ctx, state)
	ret0, _ := ret[0].(sqlc.OauthState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByState indicates an expected call of GetByState.
func (mr *MockOAuthStateRepoMockRecorder) GetByState(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByState", reflect.TypeOf((*MockOAuthStateRepo)(nil).GetByState), ctx, state)
}
