// Code generated by MockGen. DO NOT EDIT.
// Source: ./repo (interfaces: PlatformRepo)
//
// Generated by this command:
//
//	mockgen -destination repo/mocks/platform_repo.go -package mocks ./repo PlatformRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sqlc "github.com/MountainHubTech/rvpay-go/clients/db/sqlc"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPlatformRepo is a mock of PlatformRepo interface.
type MockPlatformRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPlatformRepoMockRecorder
	isgomock struct{}
}

// MockPlatformRepoMockRecorder is the mock recorder for MockPlatformRepo.
type MockPlatformRepoMockRecorder struct {
	mock *MockPlatformRepo
}

// NewMockPlatformRepo creates a new mock instance.
func NewMockPlatformRepo(ctrl *gomock.Controller) *MockPlatformRepo {
	mock := &MockPlatformRepo{ctrl: ctrl}
	mock.recorder = &MockPlatformRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlatformRepo) EXPECT() *MockPlatformRepoMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockPlatformRepo) Count(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockPlatformRepoMockRecorder) Count(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockPlatformRepo)(nil).Count), ctx)
}

// Create mocks base method.
func (m *MockPlatformRepo) Create(ctx context.Context, name, displayName, slug string, enabled, oauthCapable, webhookCapable bool) (sqlc.Platform, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name, displayName, slug, enabled, oauthCapable, webhookCapable)
	ret0, _ := ret[0].(sqlc.Platform)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPlatformRepoMockRecorder) Create(ctx, name, displayName, slug, enabled, oauthCapable, webhookCapable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPlatformRepo)(nil).Create), ctx, name, displayName, slug, enabled, oauthCapable, webhookCapable)
}

// Delete mocks base method.
func (m *MockPlatformRepo) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPlatformRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPlatformRepo)(nil).Delete), ctx, id)
}

// ExistsBySlug mocks base method.
func (m *MockPlatformRepo) ExistsBySlug(ctx context.Context, slug string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsBySlug", ctx, slug)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsBySlug indicates an expected call of ExistsBySlug.
func (mr *MockPlatformRepoMockRecorder) ExistsBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsBySlug", reflect.TypeOf((*MockPlatformRepo)(nil).ExistsBySlug), ctx, slug)
}

// GetByID mocks base method.
func (m *MockPlatformRepo) GetByID(ctx context.Context, id uuid.UUID) (sqlc.Platform, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(sqlc.Platform)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPlatformRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPlatformRepo)(nil).GetByID), ctx, id)
}

// GetByName mocks base method.
func (m *MockPlatformRepo) GetByName(ctx context.Context, name string) (sqlc.Platform, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(sqlc.Platform)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockPlatformRepoMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockPlatformRepo)(nil).GetByName), ctx, name)
}

// GetBySlug mocks base method.
func (m *MockPlatformRepo) GetBySlug(ctx context.Context, slug string) (sqlc.Platform, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySlug", ctx, slug)
	ret0, _ := ret[0].(sqlc.Platform)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySlug indicates an expected call of GetBySlug.
func (mr *MockPlatformRepoMockRecorder) GetBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySlug", reflect.TypeOf((*MockPlatformRepo)(nil).GetBySlug), ctx, slug)
}

// List mocks base method.
func (m *MockPlatformRepo) List(ctx context.Context, limit, offset int32) ([]sqlc.Platform, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset)
	ret0, _ := ret[0].([]sqlc.Platform)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPlatformRepoMockRecorder) List(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPlatformRepo)(nil).List), ctx, limit, offset)
}

// ListEnabled mocks base method.
func (m *MockPlatformRepo) ListEnabled(ctx context.Context, limit, offset int32) ([]sqlc.Platform, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnabled", ctx, limit, offset)
	ret0, _ := ret[0].([]sqlc.Platform)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnabled indicates an expected call of ListEnabled.
func (mr *MockPlatformRepoMockRecorder) ListEnabled(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnabled", reflect.TypeOf((*MockPlatformRepo)(nil).ListEnabled), ctx, limit, offset)
}

// Update mocks base method.
func (m *MockPlatformRepo) Update(ctx context.Context, id uuid.UUID, name, displayName, slug string, enabled, oauthCapable, webhookCapable bool) (sqlc.Platform, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, name, displayName, slug, enabled, oauthCapable, webhookCapable)
	ret0, _ := ret[0].(sqlc.Platform)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPlatformRepoMockRecorder) Update(ctx, id, name, displayName, slug, enabled, oauthCapable, webhookCapable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPlatformRepo)(nil).Update), ctx, id, name, displayName, slug, enabled, oauthCapable, webhookCapable)
}
