// Code generated by MockGen. DO NOT EDIT.
// Source: ./repo (interfaces: WebhookSubscriptionRepo)
//
// Generated by this command:
//
//	mockgen -destination repo/mocks/webhook_subscription_repo.go -package mocks ./repo WebhookSubscriptionRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sqlc "github.com/MountainHubTech/rvpay-go/clients/db/sqlc"
	uuid "github.com/google/uuid"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// MockWebhookSubscriptionRepo is a mock of WebhookSubscriptionRepo interface.
type MockWebhookSubscriptionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookSubscriptionRepoMockRecorder
	isgomock struct{}
}

// MockWebhookSubscriptionRepoMockRecorder is the mock recorder for MockWebhookSubscriptionRepo.
type MockWebhookSubscriptionRepoMockRecorder struct {
	mock *MockWebhookSubscriptionRepo
}

// NewMockWebhookSubscriptionRepo creates a new mock instance.
func NewMockWebhookSubscriptionRepo(ctrl *gomock.Controller) *MockWebhookSubscriptionRepo {
	mock := &MockWebhookSubscriptionRepo{ctrl: ctrl}
	mock.recorder = &MockWebhookSubscriptionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookSubscriptionRepo) EXPECT() *MockWebhookSubscriptionRepoMockRecorder {
	return m.recorder
}

// CountByIntegrationID mocks base method.
func (m *MockWebhookSubscriptionRepo) CountByIntegrationID(ctx context.Context, integrationID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByIntegrationID", ctx, integrationID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByIntegrationID indicates an expected call of CountByIntegrationID.
func (mr *MockWebhookSubscriptionRepoMockRecorder) CountByIntegrationID(ctx, integrationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByIntegrationID", reflect.TypeOf((*MockWebhookSubscriptionRepo)(nil).CountByIntegrationID), ctx, integrationID)
}

// Create mocks base method.
func (m *MockWebhookSubscriptionRepo) Create(ctx context.Context, integrationID uuid.UUID, endpoint, secret string, status sqlc.WebhookSubscriptionStatus) (sqlc.WebhookSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, integrationID, endpoint, secret, status)
	ret0, _ := ret[0].(sqlc.WebhookSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockWebhookSubscriptionRepoMockRecorder) Create(ctx, integrationID, endpoint, secret, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWebhookSubscriptionRepo)(nil).Create), ctx, integrationID, endpoint, secret, status)
}

// Delete mocks base method.
func (m *MockWebhookSubscriptionRepo) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWebhookSubscriptionRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWebhookSubscriptionRepo)(nil).Delete), ctx, id)
}

// Exists mocks base method.
func (m *MockWebhookSubscriptionRepo) Exists(ctx context.Context, integrationID uuid.UUID, endpoint string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, integrationID, endpoint)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockWebhookSubscriptionRepoMockRecorder) Exists(ctx, integrationID, endpoint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockWebhookSubscriptionRepo)(nil).Exists), ctx, integrationID, endpoint)
}

// GetByID mocks base method.
func (m *MockWebhookSubscriptionRepo) GetByID(ctx context.Context, id uuid.UUID) (sqlc.WebhookSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(sqlc.WebhookSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockWebhookSubscriptionRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockWebhookSubscriptionRepo)(nil).GetByID), ctx, id)
}

// GetByIntegrationIDAndEndpoint mocks base method.
func (m *MockWebhookSubscriptionRepo) GetByIntegrationIDAndEndpoint(ctx context.Context, integrationID uuid.UUID, endpoint string) (sqlc.WebhookSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIntegrationIDAndEndpoint", ctx, integrationID, endpoint)
	ret0, _ := ret[0].(sqlc.WebhookSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIntegrationIDAndEndpoint indicates an expected call of GetByIntegrationIDAndEndpoint.
func (mr *MockWebhookSubscriptionRepoMockRecorder) GetByIntegrationIDAndEndpoint(ctx, integrationID, endpoint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIntegrationIDAndEndpoint", reflect.TypeOf((*MockWebhookSubscriptionRepo)(nil).GetByIntegrationIDAndEndpoint), ctx, integrationID, endpoint)
}

// ListActiveByIntegrationID mocks base method.
func (m *MockWebhookSubscriptionRepo) ListActiveByIntegrationID(ctx context.Context, integrationID uuid.UUID) ([]sqlc.WebhookSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveByIntegrationID", ctx, integrationID)
	ret0, _ := ret[0].([]sqlc.WebhookSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveByIntegrationID indicates an expected call of ListActiveByIntegrationID.
func (mr *MockWebhookSubscriptionRepoMockRecorder) ListActiveByIntegrationID(ctx, integrationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveByIntegrationID", reflect.TypeOf((*MockWebhookSubscriptionRepo)(nil).ListActiveByIntegrationID), ctx, integrationID)
}

// ListByIntegrationID mocks base method.
func (m *MockWebhookSubscriptionRepo) ListByIntegrationID(ctx context.Context, integrationID uuid.UUID, limit, offset int32) ([]sqlc.WebhookSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByIntegrationID", ctx, integrationID, limit, offset)
	ret0, _ := ret[0].([]sqlc.WebhookSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByIntegrationID indicates an expected call of ListByIntegrationID.
func (mr *MockWebhookSubscriptionRepoMockRecorder) ListByIntegrationID(ctx, integrationID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByIntegrationID", reflect.TypeOf((*MockWebhookSubscriptionRepo)(nil).ListByIntegrationID), ctx, integrationID, limit, offset)
}

// UpdateLastDelivery mocks base method.
func (m *MockWebhookSubscriptionRepo) UpdateLastDelivery(ctx context.Context, id uuid.UUID, lastDelivery pgtype.Timestamptz) (sqlc.WebhookSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastDelivery", ctx, id, lastDelivery)
	ret0, _ := ret[0].(sqlc.WebhookSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLastDelivery indicates an expected call of UpdateLastDelivery.
func (mr *MockWebhookSubscriptionRepoMockRecorder) UpdateLastDelivery(ctx, id, lastDelivery any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastDelivery", reflect.TypeOf((*MockWebhookSubscriptionRepo)(nil).UpdateLastDelivery), ctx, id, lastDelivery)
}

// UpdateStatus mocks base method.
func (m *MockWebhookSubscriptionRepo) UpdateStatus(ctx context.Context, id uuid.UUID, status sqlc.WebhookSubscriptionStatus) (sqlc.WebhookSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(sqlc.WebhookSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockWebhookSubscriptionRepoMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockWebhookSubscriptionRepo)(nil).UpdateStatus), ctx, id, status)
}
