- envId: testing
  name: Testing
  gitRefName: release/testing/*
  awsAccountId: 073078215361
  domainName: rvpay.xyz

- envId: production
  name: Production
  gitRefName: release/production/*
  awsAccountId: 177683310442
  domainName: rvpay.co