// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: transactions.proto

package transactionsgrpc

import (
	commongrpc "github.com/I-Frostbyte/rvpay-go/grpc/go/commongrpc"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MerchantStatus represents the lifecycle state of a payment gateway.
type MerchantStatus int32

const (
	// MERCHANT_STATUS_UNSPECIFIED is the default value and is not a valid state.
	MerchantStatus_MERCHANT_STATUS_UNSPECIFIED MerchantStatus = 0
	// MERCHANT_STATUS_ONBOARDED indicates the merchant has been registered.
	MerchantStatus_MERCHANT_STATUS_ONBOARDED MerchantStatus = 1
	// MERCHANT_STATUS_ACTIVE indicates the merchant can process payments.
	MerchantStatus_MERCHANT_STATUS_ACTIVE MerchantStatus = 2
	// MERCHANT_STATUS_SUSPENDED indicates the merchant cannot process new
	// payments; in-flight payments continue.
	MerchantStatus_MERCHANT_STATUS_SUSPENDED MerchantStatus = 3
	// MERCHANT_STATUS_RETIRED indicates the merchant is decommissioned;
	// historical records remain.
	MerchantStatus_MERCHANT_STATUS_RETIRED MerchantStatus = 4
)

// Enum value maps for MerchantStatus.
var (
	MerchantStatus_name = map[int32]string{
		0: "MERCHANT_STATUS_UNSPECIFIED",
		1: "MERCHANT_STATUS_ONBOARDED",
		2: "MERCHANT_STATUS_ACTIVE",
		3: "MERCHANT_STATUS_SUSPENDED",
		4: "MERCHANT_STATUS_RETIRED",
	}
	MerchantStatus_value = map[string]int32{
		"MERCHANT_STATUS_UNSPECIFIED": 0,
		"MERCHANT_STATUS_ONBOARDED":   1,
		"MERCHANT_STATUS_ACTIVE":      2,
		"MERCHANT_STATUS_SUSPENDED":   3,
		"MERCHANT_STATUS_RETIRED":     4,
	}
)

func (x MerchantStatus) Enum() *MerchantStatus {
	p := new(MerchantStatus)
	*p = x
	return p
}

func (x MerchantStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MerchantStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_transactions_proto_enumTypes[0].Descriptor()
}

func (MerchantStatus) Type() protoreflect.EnumType {
	return &file_transactions_proto_enumTypes[0]
}

func (x MerchantStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MerchantStatus.Descriptor instead.
func (MerchantStatus) EnumDescriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{0}
}

// CustomerStatus represents the lifecycle state of a customer.
type CustomerStatus int32

const (
	// CUSTOMER_STATUS_UNSPECIFIED is the default value and is not a valid state.
	CustomerStatus_CUSTOMER_STATUS_UNSPECIFIED CustomerStatus = 0
	// CUSTOMER_STATUS_CREATED indicates the customer record has been created.
	CustomerStatus_CUSTOMER_STATUS_CREATED CustomerStatus = 1
	// CUSTOMER_STATUS_ACTIVE indicates the customer can continue initiating
	// payments.
	CustomerStatus_CUSTOMER_STATUS_ACTIVE CustomerStatus = 2
)

// Enum value maps for CustomerStatus.
var (
	CustomerStatus_name = map[int32]string{
		0: "CUSTOMER_STATUS_UNSPECIFIED",
		1: "CUSTOMER_STATUS_CREATED",
		2: "CUSTOMER_STATUS_ACTIVE",
	}
	CustomerStatus_value = map[string]int32{
		"CUSTOMER_STATUS_UNSPECIFIED": 0,
		"CUSTOMER_STATUS_CREATED":     1,
		"CUSTOMER_STATUS_ACTIVE":      2,
	}
)

func (x CustomerStatus) Enum() *CustomerStatus {
	p := new(CustomerStatus)
	*p = x
	return p
}

func (x CustomerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CustomerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_transactions_proto_enumTypes[1].Descriptor()
}

func (CustomerStatus) Type() protoreflect.EnumType {
	return &file_transactions_proto_enumTypes[1]
}

func (x CustomerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CustomerStatus.Descriptor instead.
func (CustomerStatus) EnumDescriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{1}
}

// DepositStatus represents the lifecycle state of a deposit.
type DepositStatus int32

const (
	// DEPOSIT_STATUS_UNSPECIFIED is the default value and is not a valid state.
	DepositStatus_DEPOSIT_STATUS_UNSPECIFIED DepositStatus = 0
	// DEPOSIT_STATUS_INITIATED indicates the deposit request has been accepted.
	DepositStatus_DEPOSIT_STATUS_INITIATED DepositStatus = 1
	// DEPOSIT_STATUS_PROCESSING indicates the merchant is processing the
	// payment.
	DepositStatus_DEPOSIT_STATUS_PROCESSING DepositStatus = 2
	// DEPOSIT_STATUS_COMPLETED indicates funds have been credited to the
	// merchant wallet.
	DepositStatus_DEPOSIT_STATUS_COMPLETED DepositStatus = 3
	// DEPOSIT_STATUS_FAILED indicates the payment could not be completed.
	DepositStatus_DEPOSIT_STATUS_FAILED DepositStatus = 4
)

// Enum value maps for DepositStatus.
var (
	DepositStatus_name = map[int32]string{
		0: "DEPOSIT_STATUS_UNSPECIFIED",
		1: "DEPOSIT_STATUS_INITIATED",
		2: "DEPOSIT_STATUS_PROCESSING",
		3: "DEPOSIT_STATUS_COMPLETED",
		4: "DEPOSIT_STATUS_FAILED",
	}
	DepositStatus_value = map[string]int32{
		"DEPOSIT_STATUS_UNSPECIFIED": 0,
		"DEPOSIT_STATUS_INITIATED":   1,
		"DEPOSIT_STATUS_PROCESSING":  2,
		"DEPOSIT_STATUS_COMPLETED":   3,
		"DEPOSIT_STATUS_FAILED":      4,
	}
)

func (x DepositStatus) Enum() *DepositStatus {
	p := new(DepositStatus)
	*p = x
	return p
}

func (x DepositStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DepositStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_transactions_proto_enumTypes[2].Descriptor()
}

func (DepositStatus) Type() protoreflect.EnumType {
	return &file_transactions_proto_enumTypes[2]
}

func (x DepositStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DepositStatus.Descriptor instead.
func (DepositStatus) EnumDescriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{2}
}

// PayoutStatus represents the lifecycle state of a payout.
type PayoutStatus int32

const (
	// PAYOUT_STATUS_UNSPECIFIED is the default value and is not a valid state.
	PayoutStatus_PAYOUT_STATUS_UNSPECIFIED PayoutStatus = 0
	// PAYOUT_STATUS_REQUESTED indicates the payout has been requested.
	PayoutStatus_PAYOUT_STATUS_REQUESTED PayoutStatus = 1
	// PAYOUT_STATUS_PROCESSING indicates the merchant is processing the payout.
	PayoutStatus_PAYOUT_STATUS_PROCESSING PayoutStatus = 2
	// PAYOUT_STATUS_COMPLETED indicates funds have been transferred to the
	// client.
	PayoutStatus_PAYOUT_STATUS_COMPLETED PayoutStatus = 3
	// PAYOUT_STATUS_FAILED indicates the payout could not be completed.
	PayoutStatus_PAYOUT_STATUS_FAILED PayoutStatus = 4
)

// Enum value maps for PayoutStatus.
var (
	PayoutStatus_name = map[int32]string{
		0: "PAYOUT_STATUS_UNSPECIFIED",
		1: "PAYOUT_STATUS_REQUESTED",
		2: "PAYOUT_STATUS_PROCESSING",
		3: "PAYOUT_STATUS_COMPLETED",
		4: "PAYOUT_STATUS_FAILED",
	}
	PayoutStatus_value = map[string]int32{
		"PAYOUT_STATUS_UNSPECIFIED": 0,
		"PAYOUT_STATUS_REQUESTED":   1,
		"PAYOUT_STATUS_PROCESSING":  2,
		"PAYOUT_STATUS_COMPLETED":   3,
		"PAYOUT_STATUS_FAILED":      4,
	}
)

func (x PayoutStatus) Enum() *PayoutStatus {
	p := new(PayoutStatus)
	*p = x
	return p
}

func (x PayoutStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayoutStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_transactions_proto_enumTypes[3].Descriptor()
}

func (PayoutStatus) Type() protoreflect.EnumType {
	return &file_transactions_proto_enumTypes[3]
}

func (x PayoutStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayoutStatus.Descriptor instead.
func (PayoutStatus) EnumDescriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{3}
}

// Merchant represents a payment gateway.
type Merchant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the stable public identifier of the merchant.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name is the merchant display name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// slug is a stable URL-friendly identifier.
	Slug string `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	// status is the merchant lifecycle state.
	Status MerchantStatus `protobuf:"varint,4,opt,name=status,proto3,enum=transactionsgrpc.MerchantStatus" json:"status,omitempty"`
	// created_at is the time the merchant was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at is the time the merchant was last modified.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Merchant) Reset() {
	*x = Merchant{}
	mi := &file_transactions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Merchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Merchant) ProtoMessage() {}

func (x *Merchant) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Merchant.ProtoReflect.Descriptor instead.
func (*Merchant) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{0}
}

func (x *Merchant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Merchant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Merchant) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Merchant) GetStatus() MerchantStatus {
	if x != nil {
		return x.Status
	}
	return MerchantStatus_MERCHANT_STATUS_UNSPECIFIED
}

func (x *Merchant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Merchant) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Customer represents an end user making payments.
type Customer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the stable public identifier of the customer.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// client_id references the RVPay client record.
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// merchant_id references the payment gateway serving this customer.
	MerchantId string `protobuf:"bytes,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	// phone_number is the customer's payment phone number.
	PhoneNumber string `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// status is the customer lifecycle state.
	Status CustomerStatus `protobuf:"varint,5,opt,name=status,proto3,enum=transactionsgrpc.CustomerStatus" json:"status,omitempty"`
	// created_at is the time the customer was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at is the time the customer was last modified.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Customer) Reset() {
	*x = Customer{}
	mi := &file_transactions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{1}
}

func (x *Customer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Customer) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Customer) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *Customer) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Customer) GetStatus() CustomerStatus {
	if x != nil {
		return x.Status
	}
	return CustomerStatus_CUSTOMER_STATUS_UNSPECIFIED
}

func (x *Customer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Customer) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Deposit represents an inbound customer payment.
type Deposit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the stable public identifier of the deposit.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// client_name is the RVPay client name (external identifier).
	ClientName string `protobuf:"bytes,2,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	// customer_id references the paying customer.
	CustomerId string `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// merchant_id references the processing merchant.
	MerchantId string `protobuf:"bytes,4,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	// amount is the deposit amount and currency.
	Amount *commongrpc.Money `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	// payment_type identifies the payment method.
	PaymentType commongrpc.PaymentType `protobuf:"varint,6,opt,name=payment_type,json=paymentType,proto3,enum=commongrpc.PaymentType" json:"payment_type,omitempty"`
	// payer_phone_number is the payer's phone number.
	PayerPhoneNumber string `protobuf:"bytes,7,opt,name=payer_phone_number,json=payerPhoneNumber,proto3" json:"payer_phone_number,omitempty"`
	// provider identifies the payment provider.
	Provider commongrpc.Provider `protobuf:"varint,8,opt,name=provider,proto3,enum=commongrpc.Provider" json:"provider,omitempty"`
	// status is the deposit lifecycle state.
	Status DepositStatus `protobuf:"varint,9,opt,name=status,proto3,enum=transactionsgrpc.DepositStatus" json:"status,omitempty"`
	// external_reference is the provider's reference for this deposit.
	ExternalReference string `protobuf:"bytes,10,opt,name=external_reference,json=externalReference,proto3" json:"external_reference,omitempty"`
	// initiated_at is the time the deposit was initiated.
	InitiatedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=initiated_at,json=initiatedAt,proto3" json:"initiated_at,omitempty"`
	// completed_at is the time the deposit completed.
	CompletedAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	// failed_at is the time the deposit failed.
	FailedAt *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=failed_at,json=failedAt,proto3" json:"failed_at,omitempty"`
	// failure_reason describes why the deposit failed.
	FailureReason string `protobuf:"bytes,14,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	// created_at is the time the deposit was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at is the time the deposit was last modified.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deposit) Reset() {
	*x = Deposit{}
	mi := &file_transactions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deposit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deposit) ProtoMessage() {}

func (x *Deposit) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deposit.ProtoReflect.Descriptor instead.
func (*Deposit) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{2}
}

func (x *Deposit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Deposit) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *Deposit) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Deposit) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *Deposit) GetAmount() *commongrpc.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Deposit) GetPaymentType() commongrpc.PaymentType {
	if x != nil {
		return x.PaymentType
	}
	return commongrpc.PaymentType(0)
}

func (x *Deposit) GetPayerPhoneNumber() string {
	if x != nil {
		return x.PayerPhoneNumber
	}
	return ""
}

func (x *Deposit) GetProvider() commongrpc.Provider {
	if x != nil {
		return x.Provider
	}
	return commongrpc.Provider(0)
}

func (x *Deposit) GetStatus() DepositStatus {
	if x != nil {
		return x.Status
	}
	return DepositStatus_DEPOSIT_STATUS_UNSPECIFIED
}

func (x *Deposit) GetExternalReference() string {
	if x != nil {
		return x.ExternalReference
	}
	return ""
}

func (x *Deposit) GetInitiatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.InitiatedAt
	}
	return nil
}

func (x *Deposit) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Deposit) GetFailedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FailedAt
	}
	return nil
}

func (x *Deposit) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *Deposit) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Deposit) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Payout represents an outbound settlement.
type Payout struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the stable public identifier of the payout.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// client_id references the RVPay client record.
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// merchant_id references the processing merchant.
	MerchantId string `protobuf:"bytes,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	// amount is the payout amount and currency.
	Amount *commongrpc.Money `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// provider identifies the payment provider.
	Provider commongrpc.Provider `protobuf:"varint,5,opt,name=provider,proto3,enum=commongrpc.Provider" json:"provider,omitempty"`
	// destination_reference is the destination account reference.
	DestinationReference string `protobuf:"bytes,6,opt,name=destination_reference,json=destinationReference,proto3" json:"destination_reference,omitempty"`
	// status is the payout lifecycle state.
	Status PayoutStatus `protobuf:"varint,7,opt,name=status,proto3,enum=transactionsgrpc.PayoutStatus" json:"status,omitempty"`
	// external_reference is the provider's reference for this payout.
	ExternalReference string `protobuf:"bytes,8,opt,name=external_reference,json=externalReference,proto3" json:"external_reference,omitempty"`
	// requested_at is the time the payout was requested.
	RequestedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	// completed_at is the time the payout completed.
	CompletedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	// failed_at is the time the payout failed.
	FailedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=failed_at,json=failedAt,proto3" json:"failed_at,omitempty"`
	// failure_reason describes why the payout failed.
	FailureReason string `protobuf:"bytes,12,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	// created_at is the time the payout was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at is the time the payout was last modified.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payout) Reset() {
	*x = Payout{}
	mi := &file_transactions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payout) ProtoMessage() {}

func (x *Payout) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payout.ProtoReflect.Descriptor instead.
func (*Payout) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{3}
}

func (x *Payout) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payout) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Payout) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *Payout) GetAmount() *commongrpc.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Payout) GetProvider() commongrpc.Provider {
	if x != nil {
		return x.Provider
	}
	return commongrpc.Provider(0)
}

func (x *Payout) GetDestinationReference() string {
	if x != nil {
		return x.DestinationReference
	}
	return ""
}

func (x *Payout) GetStatus() PayoutStatus {
	if x != nil {
		return x.Status
	}
	return PayoutStatus_PAYOUT_STATUS_UNSPECIFIED
}

func (x *Payout) GetExternalReference() string {
	if x != nil {
		return x.ExternalReference
	}
	return ""
}

func (x *Payout) GetRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedAt
	}
	return nil
}

func (x *Payout) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Payout) GetFailedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FailedAt
	}
	return nil
}

func (x *Payout) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *Payout) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Payout) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateMerchantRequest creates a merchant.
type CreateMerchantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the merchant display name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// slug is a stable URL-friendly identifier.
	Slug          string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMerchantRequest) Reset() {
	*x = CreateMerchantRequest{}
	mi := &file_transactions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMerchantRequest) ProtoMessage() {}

func (x *CreateMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMerchantRequest.ProtoReflect.Descriptor instead.
func (*CreateMerchantRequest) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMerchantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMerchantRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

// CreateMerchantResponse returns the created merchant.
type CreateMerchantResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// merchant is the created merchant.
	Merchant      *Merchant `protobuf:"bytes,1,opt,name=merchant,proto3" json:"merchant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMerchantResponse) Reset() {
	*x = CreateMerchantResponse{}
	mi := &file_transactions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMerchantResponse) ProtoMessage() {}

func (x *CreateMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMerchantResponse.ProtoReflect.Descriptor instead.
func (*CreateMerchantResponse) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{5}
}

func (x *CreateMerchantResponse) GetMerchant() *Merchant {
	if x != nil {
		return x.Merchant
	}
	return nil
}

// GetMerchantRequest fetches a merchant by id.
type GetMerchantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// merchant_id is the stable public identifier of the merchant.
	MerchantId    string `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantRequest) Reset() {
	*x = GetMerchantRequest{}
	mi := &file_transactions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantRequest) ProtoMessage() {}

func (x *GetMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantRequest.ProtoReflect.Descriptor instead.
func (*GetMerchantRequest) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{6}
}

func (x *GetMerchantRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

// GetMerchantResponse returns the requested merchant.
type GetMerchantResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// merchant is the requested merchant.
	Merchant      *Merchant `protobuf:"bytes,1,opt,name=merchant,proto3" json:"merchant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantResponse) Reset() {
	*x = GetMerchantResponse{}
	mi := &file_transactions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantResponse) ProtoMessage() {}

func (x *GetMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantResponse.ProtoReflect.Descriptor instead.
func (*GetMerchantResponse) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{7}
}

func (x *GetMerchantResponse) GetMerchant() *Merchant {
	if x != nil {
		return x.Merchant
	}
	return nil
}

// ListMerchantsRequest lists merchants.
type ListMerchantsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// page is the pagination request.
	Page          *commongrpc.PaginationRequest `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMerchantsRequest) Reset() {
	*x = ListMerchantsRequest{}
	mi := &file_transactions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMerchantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMerchantsRequest) ProtoMessage() {}

func (x *ListMerchantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMerchantsRequest.ProtoReflect.Descriptor instead.
func (*ListMerchantsRequest) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{8}
}

func (x *ListMerchantsRequest) GetPage() *commongrpc.PaginationRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

// ListMerchantsResponse returns a page of merchants.
type ListMerchantsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// merchants is the page of merchants.
	Merchants []*Merchant `protobuf:"bytes,1,rep,name=merchants,proto3" json:"merchants,omitempty"`
	// page is the pagination response.
	Page          *commongrpc.PaginationResponse `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMerchantsResponse) Reset() {
	*x = ListMerchantsResponse{}
	mi := &file_transactions_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMerchantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMerchantsResponse) ProtoMessage() {}

func (x *ListMerchantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMerchantsResponse.ProtoReflect.Descriptor instead.
func (*ListMerchantsResponse) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{9}
}

func (x *ListMerchantsResponse) GetMerchants() []*Merchant {
	if x != nil {
		return x.Merchants
	}
	return nil
}

func (x *ListMerchantsResponse) GetPage() *commongrpc.PaginationResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

// CreateCustomerRequest creates a customer.
type CreateCustomerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client_id references the RVPay client record.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// merchant_id references the payment gateway serving this customer.
	MerchantId string `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	// phone_number is the customer's payment phone number.
	PhoneNumber   string `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerRequest) Reset() {
	*x = CreateCustomerRequest{}
	mi := &file_transactions_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerRequest) ProtoMessage() {}

func (x *CreateCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerRequest.ProtoReflect.Descriptor instead.
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{10}
}

func (x *CreateCustomerRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CreateCustomerRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CreateCustomerRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

// CreateCustomerResponse returns the created customer.
type CreateCustomerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// customer is the created customer.
	Customer      *Customer `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerResponse) Reset() {
	*x = CreateCustomerResponse{}
	mi := &file_transactions_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerResponse) ProtoMessage() {}

func (x *CreateCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerResponse.ProtoReflect.Descriptor instead.
func (*CreateCustomerResponse) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{11}
}

func (x *CreateCustomerResponse) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

// GetCustomerRequest fetches a customer by id.
type GetCustomerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// customer_id is the stable public identifier of the customer.
	CustomerId    string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerRequest) Reset() {
	*x = GetCustomerRequest{}
	mi := &file_transactions_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerRequest) ProtoMessage() {}

func (x *GetCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerRequest) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{12}
}

func (x *GetCustomerRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

// GetCustomerResponse returns the requested customer.
type GetCustomerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// customer is the requested customer.
	Customer      *Customer `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerResponse) Reset() {
	*x = GetCustomerResponse{}
	mi := &file_transactions_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerResponse) ProtoMessage() {}

func (x *GetCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerResponse.ProtoReflect.Descriptor instead.
func (*GetCustomerResponse) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{13}
}

func (x *GetCustomerResponse) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

// CreateDepositRequest initiates a deposit. For the HighLevel payment flow the
// identifier fields carry external HighLevel string identifiers, NOT RVPay
// UUIDs: client_name is the RVPay client name derived from the HighLevel
// location (e.g. "highlevel-<locationId>"), customer_id is the HighLevel
// contact id, and merchant_id currently carries the HighLevel transactionId.
type CreateDepositRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client_name is the RVPay client name (external identifier).
	ClientName string `protobuf:"bytes,1,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	// customer_id is the external customer identifier (HighLevel contact id).
	// Optional.
	CustomerId string `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// merchant_id is the external merchant identifier (currently the HighLevel
	// transactionId). Optional.
	MerchantId string `protobuf:"bytes,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	// amount is the deposit amount and currency.
	Amount *commongrpc.Money `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// payment_type identifies the payment method.
	PaymentType commongrpc.PaymentType `protobuf:"varint,5,opt,name=payment_type,json=paymentType,proto3,enum=commongrpc.PaymentType" json:"payment_type,omitempty"`
	// payer_phone_number is the payer's phone number.
	PayerPhoneNumber string `protobuf:"bytes,6,opt,name=payer_phone_number,json=payerPhoneNumber,proto3" json:"payer_phone_number,omitempty"`
	// provider identifies the payment provider.
	Provider commongrpc.Provider `protobuf:"varint,7,opt,name=provider,proto3,enum=commongrpc.Provider" json:"provider,omitempty"`
	// ghl_transaction_id is the GoHighLevel transaction identifier, persisted
	// in deposits.ghl_transaction_id and used by the verify endpoint for
	// correlation. Optional.
	GhlTransactionId string `protobuf:"bytes,8,opt,name=ghl_transaction_id,json=ghlTransactionId,proto3" json:"ghl_transaction_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateDepositRequest) Reset() {
	*x = CreateDepositRequest{}
	mi := &file_transactions_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDepositRequest) ProtoMessage() {}

func (x *CreateDepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDepositRequest.ProtoReflect.Descriptor instead.
func (*CreateDepositRequest) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{14}
}

func (x *CreateDepositRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *CreateDepositRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateDepositRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CreateDepositRequest) GetAmount() *commongrpc.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *CreateDepositRequest) GetPaymentType() commongrpc.PaymentType {
	if x != nil {
		return x.PaymentType
	}
	return commongrpc.PaymentType(0)
}

func (x *CreateDepositRequest) GetPayerPhoneNumber() string {
	if x != nil {
		return x.PayerPhoneNumber
	}
	return ""
}

func (x *CreateDepositRequest) GetProvider() commongrpc.Provider {
	if x != nil {
		return x.Provider
	}
	return commongrpc.Provider(0)
}

func (x *CreateDepositRequest) GetGhlTransactionId() string {
	if x != nil {
		return x.GhlTransactionId
	}
	return ""
}

// CreateDepositResponse returns the created deposit.
type CreateDepositResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// deposit is the created deposit.
	Deposit       *Deposit `protobuf:"bytes,1,opt,name=deposit,proto3" json:"deposit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDepositResponse) Reset() {
	*x = CreateDepositResponse{}
	mi := &file_transactions_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDepositResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDepositResponse) ProtoMessage() {}

func (x *CreateDepositResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDepositResponse.ProtoReflect.Descriptor instead.
func (*CreateDepositResponse) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{15}
}

func (x *CreateDepositResponse) GetDeposit() *Deposit {
	if x != nil {
		return x.Deposit
	}
	return nil
}

// GetDepositRequest fetches a deposit by id.
type GetDepositRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// deposit_id is the stable public identifier of the deposit.
	DepositId     string `protobuf:"bytes,1,opt,name=deposit_id,json=depositId,proto3" json:"deposit_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepositRequest) Reset() {
	*x = GetDepositRequest{}
	mi := &file_transactions_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepositRequest) ProtoMessage() {}

func (x *GetDepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepositRequest.ProtoReflect.Descriptor instead.
func (*GetDepositRequest) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{16}
}

func (x *GetDepositRequest) GetDepositId() string {
	if x != nil {
		return x.DepositId
	}
	return ""
}

// GetDepositResponse returns the requested deposit.
type GetDepositResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// deposit is the requested deposit.
	Deposit       *Deposit `protobuf:"bytes,1,opt,name=deposit,proto3" json:"deposit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepositResponse) Reset() {
	*x = GetDepositResponse{}
	mi := &file_transactions_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepositResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepositResponse) ProtoMessage() {}

func (x *GetDepositResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepositResponse.ProtoReflect.Descriptor instead.
func (*GetDepositResponse) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{17}
}

func (x *GetDepositResponse) GetDeposit() *Deposit {
	if x != nil {
		return x.Deposit
	}
	return nil
}

// GetDepositByGHLTransactionIDRequest fetches a deposit by its GoHighLevel
// transaction identifier. This is used by the GHL Custom Payment Provider
// query endpoint to correlate a HighLevel transaction with an RVPay deposit.
type GetDepositByGHLTransactionIDRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ghl_transaction_id is the GoHighLevel transaction identifier.
	GhlTransactionId string `protobuf:"bytes,1,opt,name=ghl_transaction_id,json=ghlTransactionId,proto3" json:"ghl_transaction_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetDepositByGHLTransactionIDRequest) Reset() {
	*x = GetDepositByGHLTransactionIDRequest{}
	mi := &file_transactions_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepositByGHLTransactionIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepositByGHLTransactionIDRequest) ProtoMessage() {}

func (x *GetDepositByGHLTransactionIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepositByGHLTransactionIDRequest.ProtoReflect.Descriptor instead.
func (*GetDepositByGHLTransactionIDRequest) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{18}
}

func (x *GetDepositByGHLTransactionIDRequest) GetGhlTransactionId() string {
	if x != nil {
		return x.GhlTransactionId
	}
	return ""
}

// GetDepositByGHLTransactionIDResponse returns the requested deposit.
type GetDepositByGHLTransactionIDResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// deposit is the requested deposit.
	Deposit       *Deposit `protobuf:"bytes,1,opt,name=deposit,proto3" json:"deposit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepositByGHLTransactionIDResponse) Reset() {
	*x = GetDepositByGHLTransactionIDResponse{}
	mi := &file_transactions_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepositByGHLTransactionIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepositByGHLTransactionIDResponse) ProtoMessage() {}

func (x *GetDepositByGHLTransactionIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepositByGHLTransactionIDResponse.ProtoReflect.Descriptor instead.
func (*GetDepositByGHLTransactionIDResponse) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{19}
}

func (x *GetDepositByGHLTransactionIDResponse) GetDeposit() *Deposit {
	if x != nil {
		return x.Deposit
	}
	return nil
}

// VerifyPaymentRequest requests verification of a payment referenced by a
// GoHighLevel transaction identifier. This is used by the GHL Custom Payment
// Provider query endpoint (verify operation).
type VerifyPaymentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ghl_transaction_id is the GoHighLevel transaction identifier.
	GhlTransactionId string `protobuf:"bytes,1,opt,name=ghl_transaction_id,json=ghlTransactionId,proto3" json:"ghl_transaction_id,omitempty"`
	// ghl_charge_id is the GoHighLevel charge identifier. It is used as a
	// fallback lookup when the transaction identifier is not present or does
	// not resolve to a deposit.
	GhlChargeId string `protobuf:"bytes,2,opt,name=ghl_charge_id,json=ghlChargeId,proto3" json:"ghl_charge_id,omitempty"`
	// subscription_id is the GoHighLevel subscription identifier. RVPay only
	// supports one-time payments; a non-empty subscription_id is rejected.
	SubscriptionId string `protobuf:"bytes,3,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerifyPaymentRequest) Reset() {
	*x = VerifyPaymentRequest{}
	mi := &file_transactions_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPaymentRequest) ProtoMessage() {}

func (x *VerifyPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPaymentRequest.ProtoReflect.Descriptor instead.
func (*VerifyPaymentRequest) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{20}
}

func (x *VerifyPaymentRequest) GetGhlTransactionId() string {
	if x != nil {
		return x.GhlTransactionId
	}
	return ""
}

func (x *VerifyPaymentRequest) GetGhlChargeId() string {
	if x != nil {
		return x.GhlChargeId
	}
	return ""
}

func (x *VerifyPaymentRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

// VerifyPaymentResponse returns the payment verification result.
type VerifyPaymentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates the payment has succeeded.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// failed indicates the payment has failed.
	Failed        bool `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPaymentResponse) Reset() {
	*x = VerifyPaymentResponse{}
	mi := &file_transactions_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPaymentResponse) ProtoMessage() {}

func (x *VerifyPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPaymentResponse.ProtoReflect.Descriptor instead.
func (*VerifyPaymentResponse) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{21}
}

func (x *VerifyPaymentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VerifyPaymentResponse) GetFailed() bool {
	if x != nil {
		return x.Failed
	}
	return false
}

// ProcessPaymentWebhookRequest carries a payment-provider webhook event for
// business processing. Only one-time payment events relevant to RVPay are
// processed (e.g. payment.captured); subscription events are not supported.
type ProcessPaymentWebhookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event_type is the HighLevel payment event type (e.g. payment.captured).
	EventType string `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// transaction_id is the GoHighLevel transaction identifier.
	TransactionId string `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	// charge_id is the GoHighLevel charge identifier.
	ChargeId string `protobuf:"bytes,3,opt,name=charge_id,json=chargeId,proto3" json:"charge_id,omitempty"`
	// location_id is the GoHighLevel location identifier.
	LocationId    string `protobuf:"bytes,4,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentWebhookRequest) Reset() {
	*x = ProcessPaymentWebhookRequest{}
	mi := &file_transactions_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentWebhookRequest) ProtoMessage() {}

func (x *ProcessPaymentWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentWebhookRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentWebhookRequest) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{22}
}

func (x *ProcessPaymentWebhookRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ProcessPaymentWebhookRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ProcessPaymentWebhookRequest) GetChargeId() string {
	if x != nil {
		return x.ChargeId
	}
	return ""
}

func (x *ProcessPaymentWebhookRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

// ProcessPaymentWebhookResponse acknowledges a processed payment webhook.
type ProcessPaymentWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentWebhookResponse) Reset() {
	*x = ProcessPaymentWebhookResponse{}
	mi := &file_transactions_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentWebhookResponse) ProtoMessage() {}

func (x *ProcessPaymentWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentWebhookResponse.ProtoReflect.Descriptor instead.
func (*ProcessPaymentWebhookResponse) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{23}
}

// CreatePayoutRequest requests a payout.
type CreatePayoutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client_id references the RVPay client record.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// merchant_id references the processing merchant.
	MerchantId string `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	// amount is the payout amount and currency.
	Amount *commongrpc.Money `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// provider identifies the payment provider.
	Provider commongrpc.Provider `protobuf:"varint,4,opt,name=provider,proto3,enum=commongrpc.Provider" json:"provider,omitempty"`
	// destination_reference is the destination account reference.
	DestinationReference string `protobuf:"bytes,5,opt,name=destination_reference,json=destinationReference,proto3" json:"destination_reference,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreatePayoutRequest) Reset() {
	*x = CreatePayoutRequest{}
	mi := &file_transactions_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePayoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePayoutRequest) ProtoMessage() {}

func (x *CreatePayoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePayoutRequest.ProtoReflect.Descriptor instead.
func (*CreatePayoutRequest) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{24}
}

func (x *CreatePayoutRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CreatePayoutRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CreatePayoutRequest) GetAmount() *commongrpc.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *CreatePayoutRequest) GetProvider() commongrpc.Provider {
	if x != nil {
		return x.Provider
	}
	return commongrpc.Provider(0)
}

func (x *CreatePayoutRequest) GetDestinationReference() string {
	if x != nil {
		return x.DestinationReference
	}
	return ""
}

// CreatePayoutResponse returns the created payout.
type CreatePayoutResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// payout is the created payout.
	Payout        *Payout `protobuf:"bytes,1,opt,name=payout,proto3" json:"payout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePayoutResponse) Reset() {
	*x = CreatePayoutResponse{}
	mi := &file_transactions_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePayoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePayoutResponse) ProtoMessage() {}

func (x *CreatePayoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePayoutResponse.ProtoReflect.Descriptor instead.
func (*CreatePayoutResponse) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{25}
}

func (x *CreatePayoutResponse) GetPayout() *Payout {
	if x != nil {
		return x.Payout
	}
	return nil
}

// GetPayoutRequest fetches a payout by id.
type GetPayoutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// payout_id is the stable public identifier of the payout.
	PayoutId      string `protobuf:"bytes,1,opt,name=payout_id,json=payoutId,proto3" json:"payout_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayoutRequest) Reset() {
	*x = GetPayoutRequest{}
	mi := &file_transactions_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayoutRequest) ProtoMessage() {}

func (x *GetPayoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayoutRequest.ProtoReflect.Descriptor instead.
func (*GetPayoutRequest) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{26}
}

func (x *GetPayoutRequest) GetPayoutId() string {
	if x != nil {
		return x.PayoutId
	}
	return ""
}

// GetPayoutResponse returns the requested payout.
type GetPayoutResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// payout is the requested payout.
	Payout        *Payout `protobuf:"bytes,1,opt,name=payout,proto3" json:"payout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayoutResponse) Reset() {
	*x = GetPayoutResponse{}
	mi := &file_transactions_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayoutResponse) ProtoMessage() {}

func (x *GetPayoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayoutResponse.ProtoReflect.Descriptor instead.
func (*GetPayoutResponse) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{27}
}

func (x *GetPayoutResponse) GetPayout() *Payout {
	if x != nil {
		return x.Payout
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_transactions_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{28}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_transactions_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{29}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_transactions_proto protoreflect.FileDescriptor

const file_transactions_proto_rawDesc = "" +
	"\n" +
	"\x12transactions.proto\x12\x10transactionsgrpc\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\fcommon.proto\"\xf2\x01\n" +
	"\bMerchant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x128\n" +
	"\x06status\x18\x04 \x01(\x0e2 .transactionsgrpc.MerchantStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xab\x02\n" +
	"\bCustomer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\tR\n" +
	"merchantId\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x128\n" +
	"\x06status\x18\x05 \x01(\x0e2 .transactionsgrpc.CustomerStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xff\x05\n" +
	"\aDeposit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vclient_name\x18\x02 \x01(\tR\n" +
	"clientName\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12\x1f\n" +
	"\vmerchant_id\x18\x04 \x01(\tR\n" +
	"merchantId\x12)\n" +
	"\x06amount\x18\x05 \x01(\v2\x11.commongrpc.MoneyR\x06amount\x12:\n" +
	"\fpayment_type\x18\x06 \x01(\x0e2\x17.commongrpc.PaymentTypeR\vpaymentType\x12,\n" +
	"\x12payer_phone_number\x18\a \x01(\tR\x10payerPhoneNumber\x120\n" +
	"\bprovider\x18\b \x01(\x0e2\x14.commongrpc.ProviderR\bprovider\x127\n" +
	"\x06status\x18\t \x01(\x0e2\x1f.transactionsgrpc.DepositStatusR\x06status\x12-\n" +
	"\x12external_reference\x18\n" +
	" \x01(\tR\x11externalReference\x12=\n" +
	"\finitiated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vinitiatedAt\x12=\n" +
	"\fcompleted_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x127\n" +
	"\tfailed_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\bfailedAt\x12%\n" +
	"\x0efailure_reason\x18\x0e \x01(\tR\rfailureReason\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa3\x05\n" +
	"\x06Payout\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\tR\n" +
	"merchantId\x12)\n" +
	"\x06amount\x18\x04 \x01(\v2\x11.commongrpc.MoneyR\x06amount\x120\n" +
	"\bprovider\x18\x05 \x01(\x0e2\x14.commongrpc.ProviderR\bprovider\x123\n" +
	"\x15destination_reference\x18\x06 \x01(\tR\x14destinationReference\x126\n" +
	"\x06status\x18\a \x01(\x0e2\x1e.transactionsgrpc.PayoutStatusR\x06status\x12-\n" +
	"\x12external_reference\x18\b \x01(\tR\x11externalReference\x12=\n" +
	"\frequested_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vrequestedAt\x12=\n" +
	"\fcompleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x127\n" +
	"\tfailed_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\bfailedAt\x12%\n" +
	"\x0efailure_reason\x18\f \x01(\tR\rfailureReason\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"?\n" +
	"\x15CreateMerchantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\"P\n" +
	"\x16CreateMerchantResponse\x126\n" +
	"\bmerchant\x18\x01 \x01(\v2\x1a.transactionsgrpc.MerchantR\bmerchant\"5\n" +
	"\x12GetMerchantRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\"M\n" +
	"\x13GetMerchantResponse\x126\n" +
	"\bmerchant\x18\x01 \x01(\v2\x1a.transactionsgrpc.MerchantR\bmerchant\"I\n" +
	"\x14ListMerchantsRequest\x121\n" +
	"\x04page\x18\x01 \x01(\v2\x1d.commongrpc.PaginationRequestR\x04page\"\x85\x01\n" +
	"\x15ListMerchantsResponse\x128\n" +
	"\tmerchants\x18\x01 \x03(\v2\x1a.transactionsgrpc.MerchantR\tmerchants\x122\n" +
	"\x04page\x18\x02 \x01(\v2\x1e.commongrpc.PaginationResponseR\x04page\"x\n" +
	"\x15CreateCustomerRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\"P\n" +
	"\x16CreateCustomerResponse\x126\n" +
	"\bcustomer\x18\x01 \x01(\v2\x1a.transactionsgrpc.CustomerR\bcustomer\"5\n" +
	"\x12GetCustomerRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\"M\n" +
	"\x13GetCustomerResponse\x126\n" +
	"\bcustomer\x18\x01 \x01(\v2\x1a.transactionsgrpc.CustomerR\bcustomer\"\xee\x02\n" +
	"\x14CreateDepositRequest\x12\x1f\n" +
	"\vclient_name\x18\x01 \x01(\tR\n" +
	"clientName\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\tR\n" +
	"merchantId\x12)\n" +
	"\x06amount\x18\x04 \x01(\v2\x11.commongrpc.MoneyR\x06amount\x12:\n" +
	"\fpayment_type\x18\x05 \x01(\x0e2\x17.commongrpc.PaymentTypeR\vpaymentType\x12,\n" +
	"\x12payer_phone_number\x18\x06 \x01(\tR\x10payerPhoneNumber\x120\n" +
	"\bprovider\x18\a \x01(\x0e2\x14.commongrpc.ProviderR\bprovider\x12,\n" +
	"\x12ghl_transaction_id\x18\b \x01(\tR\x10ghlTransactionId\"L\n" +
	"\x15CreateDepositResponse\x123\n" +
	"\adeposit\x18\x01 \x01(\v2\x19.transactionsgrpc.DepositR\adeposit\"2\n" +
	"\x11GetDepositRequest\x12\x1d\n" +
	"\n" +
	"deposit_id\x18\x01 \x01(\tR\tdepositId\"I\n" +
	"\x12GetDepositResponse\x123\n" +
	"\adeposit\x18\x01 \x01(\v2\x19.transactionsgrpc.DepositR\adeposit\"S\n" +
	"#GetDepositByGHLTransactionIDRequest\x12,\n" +
	"\x12ghl_transaction_id\x18\x01 \x01(\tR\x10ghlTransactionId\"[\n" +
	"$GetDepositByGHLTransactionIDResponse\x123\n" +
	"\adeposit\x18\x01 \x01(\v2\x19.transactionsgrpc.DepositR\adeposit\"\x91\x01\n" +
	"\x14VerifyPaymentRequest\x12,\n" +
	"\x12ghl_transaction_id\x18\x01 \x01(\tR\x10ghlTransactionId\x12\"\n" +
	"\rghl_charge_id\x18\x02 \x01(\tR\vghlChargeId\x12'\n" +
	"\x0fsubscription_id\x18\x03 \x01(\tR\x0esubscriptionId\"I\n" +
	"\x15VerifyPaymentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\bR\x06failed\"\xa2\x01\n" +
	"\x1cProcessPaymentWebhookRequest\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x1b\n" +
	"\tcharge_id\x18\x03 \x01(\tR\bchargeId\x12\x1f\n" +
	"\vlocation_id\x18\x04 \x01(\tR\n" +
	"locationId\"\x1f\n" +
	"\x1dProcessPaymentWebhookResponse\"\xe5\x01\n" +
	"\x13CreatePayoutRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12)\n" +
	"\x06amount\x18\x03 \x01(\v2\x11.commongrpc.MoneyR\x06amount\x120\n" +
	"\bprovider\x18\x04 \x01(\x0e2\x14.commongrpc.ProviderR\bprovider\x123\n" +
	"\x15destination_reference\x18\x05 \x01(\tR\x14destinationReference\"H\n" +
	"\x14CreatePayoutResponse\x120\n" +
	"\x06payout\x18\x01 \x01(\v2\x18.transactionsgrpc.PayoutR\x06payout\"/\n" +
	"\x10GetPayoutRequest\x12\x1b\n" +
	"\tpayout_id\x18\x01 \x01(\tR\bpayoutId\"E\n" +
	"\x11GetPayoutResponse\x120\n" +
	"\x06payout\x18\x01 \x01(\v2\x18.transactionsgrpc.PayoutR\x06payout\"\x14\n" +
	"\x12HealthCheckRequest\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status*\xa8\x01\n" +
	"\x0eMerchantStatus\x12\x1f\n" +
	"\x1bMERCHANT_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19MERCHANT_STATUS_ONBOARDED\x10\x01\x12\x1a\n" +
	"\x16MERCHANT_STATUS_ACTIVE\x10\x02\x12\x1d\n" +
	"\x19MERCHANT_STATUS_SUSPENDED\x10\x03\x12\x1b\n" +
	"\x17MERCHANT_STATUS_RETIRED\x10\x04*j\n" +
	"\x0eCustomerStatus\x12\x1f\n" +
	"\x1bCUSTOMER_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CUSTOMER_STATUS_CREATED\x10\x01\x12\x1a\n" +
	"\x16CUSTOMER_STATUS_ACTIVE\x10\x02*\xa5\x01\n" +
	"\rDepositStatus\x12\x1e\n" +
	"\x1aDEPOSIT_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18DEPOSIT_STATUS_INITIATED\x10\x01\x12\x1d\n" +
	"\x19DEPOSIT_STATUS_PROCESSING\x10\x02\x12\x1c\n" +
	"\x18DEPOSIT_STATUS_COMPLETED\x10\x03\x12\x19\n" +
	"\x15DEPOSIT_STATUS_FAILED\x10\x04*\x9f\x01\n" +
	"\fPayoutStatus\x12\x1d\n" +
	"\x19PAYOUT_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PAYOUT_STATUS_REQUESTED\x10\x01\x12\x1c\n" +
	"\x18PAYOUT_STATUS_PROCESSING\x10\x02\x12\x1b\n" +
	"\x17PAYOUT_STATUS_COMPLETED\x10\x03\x12\x18\n" +
	"\x14PAYOUT_STATUS_FAILED\x10\x042\xa1\x03\n" +
	"\x0fMerchantService\x12\x84\x01\n" +
	"\x0eCreateMerchant\x12'.transactionsgrpc.CreateMerchantRequest\x1a(.transactionsgrpc.CreateMerchantResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/public/merchants\x12\x86\x01\n" +
	"\vGetMerchant\x12$.transactionsgrpc.GetMerchantRequest\x1a%.transactionsgrpc.GetMerchantResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/v1/public/merchants/{merchant_id}\x12~\n" +
	"\rListMerchants\x12&.transactionsgrpc.ListMerchantsRequest\x1a'.transactionsgrpc.ListMerchantsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/public/merchants2\xa1\x02\n" +
	"\x0fCustomerService\x12\x84\x01\n" +
	"\x0eCreateCustomer\x12'.transactionsgrpc.CreateCustomerRequest\x1a(.transactionsgrpc.CreateCustomerResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/public/customers\x12\x86\x01\n" +
	"\vGetCustomer\x12$.transactionsgrpc.GetCustomerRequest\x1a%.transactionsgrpc.GetCustomerResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/v1/public/customers/{customer_id}2\xee\x03\n" +
	"\x0eDepositService\x12\x82\x01\n" +
	"\x0fInitiateDeposit\x12&.transactionsgrpc.CreateDepositRequest\x1a'.transactionsgrpc.CreateDepositResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/public/deposits\x12\x81\x01\n" +
	"\n" +
	"GetDeposit\x12#.transactionsgrpc.GetDepositRequest\x1a$.transactionsgrpc.GetDepositResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/public/deposits/{deposit_id}\x12\xd2\x01\n" +
	"\x1cGetDepositByGHLTransactionID\x125.transactionsgrpc.GetDepositByGHLTransactionIDRequest\x1a6.transactionsgrpc.GetDepositByGHLTransactionIDResponse\"C\x82\xd3\xe4\x93\x02=\x12;/v1/public/deposits/by-ghl-transaction/{ghl_transaction_id}2\xba\x02\n" +
	"\x0ePaymentService\x12\x84\x01\n" +
	"\rVerifyPayment\x12&.transactionsgrpc.VerifyPaymentRequest\x1a'.transactionsgrpc.VerifyPaymentResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/public/payments/verify\x12\xa0\x01\n" +
	"\x15ProcessPaymentWebhook\x12..transactionsgrpc.ProcessPaymentWebhookRequest\x1a/.transactionsgrpc.ProcessPaymentWebhookResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/public/payments/webhook2\x8c\x02\n" +
	"\rPayoutService\x12}\n" +
	"\rRequestPayout\x12%.transactionsgrpc.CreatePayoutRequest\x1a&.transactionsgrpc.CreatePayoutResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/public/payouts\x12|\n" +
	"\tGetPayout\x12\".transactionsgrpc.GetPayoutRequest\x1a#.transactionsgrpc.GetPayoutResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v1/public/payouts/{payout_id}2\x99\x01\n" +
	"\rHealthService\x12\x87\x01\n" +
	"\vHealthCheck\x12$.transactionsgrpc.HealthCheckRequest\x1a%.transactionsgrpc.HealthCheckResponse\"+\x82\xd3\xe4\x93\x02%\x12#/v1/public/transactions/healthcheckB:Z8github.com/I-Frostbyte/rvpay-go/grpc/go/transactionsgrpcb\x06proto3"

var (
	file_transactions_proto_rawDescOnce sync.Once
	file_transactions_proto_rawDescData []byte
)

func file_transactions_proto_rawDescGZIP() []byte {
	file_transactions_proto_rawDescOnce.Do(func() {
		file_transactions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transactions_proto_rawDesc), len(file_transactions_proto_rawDesc)))
	})
	return file_transactions_proto_rawDescData
}

var file_transactions_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_transactions_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_transactions_proto_goTypes = []any{
	(MerchantStatus)(0),                          // 0: transactionsgrpc.MerchantStatus
	(CustomerStatus)(0),                          // 1: transactionsgrpc.CustomerStatus
	(DepositStatus)(0),                           // 2: transactionsgrpc.DepositStatus
	(PayoutStatus)(0),                            // 3: transactionsgrpc.PayoutStatus
	(*Merchant)(nil),                             // 4: transactionsgrpc.Merchant
	(*Customer)(nil),                             // 5: transactionsgrpc.Customer
	(*Deposit)(nil),                              // 6: transactionsgrpc.Deposit
	(*Payout)(nil),                               // 7: transactionsgrpc.Payout
	(*CreateMerchantRequest)(nil),                // 8: transactionsgrpc.CreateMerchantRequest
	(*CreateMerchantResponse)(nil),               // 9: transactionsgrpc.CreateMerchantResponse
	(*GetMerchantRequest)(nil),                   // 10: transactionsgrpc.GetMerchantRequest
	(*GetMerchantResponse)(nil),                  // 11: transactionsgrpc.GetMerchantResponse
	(*ListMerchantsRequest)(nil),                 // 12: transactionsgrpc.ListMerchantsRequest
	(*ListMerchantsResponse)(nil),                // 13: transactionsgrpc.ListMerchantsResponse
	(*CreateCustomerRequest)(nil),                // 14: transactionsgrpc.CreateCustomerRequest
	(*CreateCustomerResponse)(nil),               // 15: transactionsgrpc.CreateCustomerResponse
	(*GetCustomerRequest)(nil),                   // 16: transactionsgrpc.GetCustomerRequest
	(*GetCustomerResponse)(nil),                  // 17: transactionsgrpc.GetCustomerResponse
	(*CreateDepositRequest)(nil),                 // 18: transactionsgrpc.CreateDepositRequest
	(*CreateDepositResponse)(nil),                // 19: transactionsgrpc.CreateDepositResponse
	(*GetDepositRequest)(nil),                    // 20: transactionsgrpc.GetDepositRequest
	(*GetDepositResponse)(nil),                   // 21: transactionsgrpc.GetDepositResponse
	(*GetDepositByGHLTransactionIDRequest)(nil),  // 22: transactionsgrpc.GetDepositByGHLTransactionIDRequest
	(*GetDepositByGHLTransactionIDResponse)(nil), // 23: transactionsgrpc.GetDepositByGHLTransactionIDResponse
	(*VerifyPaymentRequest)(nil),                 // 24: transactionsgrpc.VerifyPaymentRequest
	(*VerifyPaymentResponse)(nil),                // 25: transactionsgrpc.VerifyPaymentResponse
	(*ProcessPaymentWebhookRequest)(nil),         // 26: transactionsgrpc.ProcessPaymentWebhookRequest
	(*ProcessPaymentWebhookResponse)(nil),        // 27: transactionsgrpc.ProcessPaymentWebhookResponse
	(*CreatePayoutRequest)(nil),                  // 28: transactionsgrpc.CreatePayoutRequest
	(*CreatePayoutResponse)(nil),                 // 29: transactionsgrpc.CreatePayoutResponse
	(*GetPayoutRequest)(nil),                     // 30: transactionsgrpc.GetPayoutRequest
	(*GetPayoutResponse)(nil),                    // 31: transactionsgrpc.GetPayoutResponse
	(*HealthCheckRequest)(nil),                   // 32: transactionsgrpc.HealthCheckRequest
	(*HealthCheckResponse)(nil),                  // 33: transactionsgrpc.HealthCheckResponse
	(*timestamppb.Timestamp)(nil),                // 34: google.protobuf.Timestamp
	(*commongrpc.Money)(nil),                     // 35: commongrpc.Money
	(commongrpc.PaymentType)(0),                  // 36: commongrpc.PaymentType
	(commongrpc.Provider)(0),                     // 37: commongrpc.Provider
	(*commongrpc.PaginationRequest)(nil),         // 38: commongrpc.PaginationRequest
	(*commongrpc.PaginationResponse)(nil),        // 39: commongrpc.PaginationResponse
}
var file_transactions_proto_depIdxs = []int32{
	0,  // 0: transactionsgrpc.Merchant.status:type_name -> transactionsgrpc.MerchantStatus
	34, // 1: transactionsgrpc.Merchant.created_at:type_name -> google.protobuf.Timestamp
	34, // 2: transactionsgrpc.Merchant.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: transactionsgrpc.Customer.status:type_name -> transactionsgrpc.CustomerStatus
	34, // 4: transactionsgrpc.Customer.created_at:type_name -> google.protobuf.Timestamp
	34, // 5: transactionsgrpc.Customer.updated_at:type_name -> google.protobuf.Timestamp
	35, // 6: transactionsgrpc.Deposit.amount:type_name -> commongrpc.Money
	36, // 7: transactionsgrpc.Deposit.payment_type:type_name -> commongrpc.PaymentType
	37, // 8: transactionsgrpc.Deposit.provider:type_name -> commongrpc.Provider
	2,  // 9: transactionsgrpc.Deposit.status:type_name -> transactionsgrpc.DepositStatus
	34, // 10: transactionsgrpc.Deposit.initiated_at:type_name -> google.protobuf.Timestamp
	34, // 11: transactionsgrpc.Deposit.completed_at:type_name -> google.protobuf.Timestamp
	34, // 12: transactionsgrpc.Deposit.failed_at:type_name -> google.protobuf.Timestamp
	34, // 13: transactionsgrpc.Deposit.created_at:type_name -> google.protobuf.Timestamp
	34, // 14: transactionsgrpc.Deposit.updated_at:type_name -> google.protobuf.Timestamp
	35, // 15: transactionsgrpc.Payout.amount:type_name -> commongrpc.Money
	37, // 16: transactionsgrpc.Payout.provider:type_name -> commongrpc.Provider
	3,  // 17: transactionsgrpc.Payout.status:type_name -> transactionsgrpc.PayoutStatus
	34, // 18: transactionsgrpc.Payout.requested_at:type_name -> google.protobuf.Timestamp
	34, // 19: transactionsgrpc.Payout.completed_at:type_name -> google.protobuf.Timestamp
	34, // 20: transactionsgrpc.Payout.failed_at:type_name -> google.protobuf.Timestamp
	34, // 21: transactionsgrpc.Payout.created_at:type_name -> google.protobuf.Timestamp
	34, // 22: transactionsgrpc.Payout.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 23: transactionsgrpc.CreateMerchantResponse.merchant:type_name -> transactionsgrpc.Merchant
	4,  // 24: transactionsgrpc.GetMerchantResponse.merchant:type_name -> transactionsgrpc.Merchant
	38, // 25: transactionsgrpc.ListMerchantsRequest.page:type_name -> commongrpc.PaginationRequest
	4,  // 26: transactionsgrpc.ListMerchantsResponse.merchants:type_name -> transactionsgrpc.Merchant
	39, // 27: transactionsgrpc.ListMerchantsResponse.page:type_name -> commongrpc.PaginationResponse
	5,  // 28: transactionsgrpc.CreateCustomerResponse.customer:type_name -> transactionsgrpc.Customer
	5,  // 29: transactionsgrpc.GetCustomerResponse.customer:type_name -> transactionsgrpc.Customer
	35, // 30: transactionsgrpc.CreateDepositRequest.amount:type_name -> commongrpc.Money
	36, // 31: transactionsgrpc.CreateDepositRequest.payment_type:type_name -> commongrpc.PaymentType
	37, // 32: transactionsgrpc.CreateDepositRequest.provider:type_name -> commongrpc.Provider
	6,  // 33: transactionsgrpc.CreateDepositResponse.deposit:type_name -> transactionsgrpc.Deposit
	6,  // 34: transactionsgrpc.GetDepositResponse.deposit:type_name -> transactionsgrpc.Deposit
	6,  // 35: transactionsgrpc.GetDepositByGHLTransactionIDResponse.deposit:type_name -> transactionsgrpc.Deposit
	35, // 36: transactionsgrpc.CreatePayoutRequest.amount:type_name -> commongrpc.Money
	37, // 37: transactionsgrpc.CreatePayoutRequest.provider:type_name -> commongrpc.Provider
	7,  // 38: transactionsgrpc.CreatePayoutResponse.payout:type_name -> transactionsgrpc.Payout
	7,  // 39: transactionsgrpc.GetPayoutResponse.payout:type_name -> transactionsgrpc.Payout
	8,  // 40: transactionsgrpc.MerchantService.CreateMerchant:input_type -> transactionsgrpc.CreateMerchantRequest
	10, // 41: transactionsgrpc.MerchantService.GetMerchant:input_type -> transactionsgrpc.GetMerchantRequest
	12, // 42: transactionsgrpc.MerchantService.ListMerchants:input_type -> transactionsgrpc.ListMerchantsRequest
	14, // 43: transactionsgrpc.CustomerService.CreateCustomer:input_type -> transactionsgrpc.CreateCustomerRequest
	16, // 44: transactionsgrpc.CustomerService.GetCustomer:input_type -> transactionsgrpc.GetCustomerRequest
	18, // 45: transactionsgrpc.DepositService.InitiateDeposit:input_type -> transactionsgrpc.CreateDepositRequest
	20, // 46: transactionsgrpc.DepositService.GetDeposit:input_type -> transactionsgrpc.GetDepositRequest
	22, // 47: transactionsgrpc.DepositService.GetDepositByGHLTransactionID:input_type -> transactionsgrpc.GetDepositByGHLTransactionIDRequest
	24, // 48: transactionsgrpc.PaymentService.VerifyPayment:input_type -> transactionsgrpc.VerifyPaymentRequest
	26, // 49: transactionsgrpc.PaymentService.ProcessPaymentWebhook:input_type -> transactionsgrpc.ProcessPaymentWebhookRequest
	28, // 50: transactionsgrpc.PayoutService.RequestPayout:input_type -> transactionsgrpc.CreatePayoutRequest
	30, // 51: transactionsgrpc.PayoutService.GetPayout:input_type -> transactionsgrpc.GetPayoutRequest
	32, // 52: transactionsgrpc.HealthService.HealthCheck:input_type -> transactionsgrpc.HealthCheckRequest
	9,  // 53: transactionsgrpc.MerchantService.CreateMerchant:output_type -> transactionsgrpc.CreateMerchantResponse
	11, // 54: transactionsgrpc.MerchantService.GetMerchant:output_type -> transactionsgrpc.GetMerchantResponse
	13, // 55: transactionsgrpc.MerchantService.ListMerchants:output_type -> transactionsgrpc.ListMerchantsResponse
	15, // 56: transactionsgrpc.CustomerService.CreateCustomer:output_type -> transactionsgrpc.CreateCustomerResponse
	17, // 57: transactionsgrpc.CustomerService.GetCustomer:output_type -> transactionsgrpc.GetCustomerResponse
	19, // 58: transactionsgrpc.DepositService.InitiateDeposit:output_type -> transactionsgrpc.CreateDepositResponse
	21, // 59: transactionsgrpc.DepositService.GetDeposit:output_type -> transactionsgrpc.GetDepositResponse
	23, // 60: transactionsgrpc.DepositService.GetDepositByGHLTransactionID:output_type -> transactionsgrpc.GetDepositByGHLTransactionIDResponse
	25, // 61: transactionsgrpc.PaymentService.VerifyPayment:output_type -> transactionsgrpc.VerifyPaymentResponse
	27, // 62: transactionsgrpc.PaymentService.ProcessPaymentWebhook:output_type -> transactionsgrpc.ProcessPaymentWebhookResponse
	29, // 63: transactionsgrpc.PayoutService.RequestPayout:output_type -> transactionsgrpc.CreatePayoutResponse
	31, // 64: transactionsgrpc.PayoutService.GetPayout:output_type -> transactionsgrpc.GetPayoutResponse
	33, // 65: transactionsgrpc.HealthService.HealthCheck:output_type -> transactionsgrpc.HealthCheckResponse
	53, // [53:66] is the sub-list for method output_type
	40, // [40:53] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_transactions_proto_init() }
func file_transactions_proto_init() {
	if File_transactions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transactions_proto_rawDesc), len(file_transactions_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   6,
		},
		GoTypes:           file_transactions_proto_goTypes,
		DependencyIndexes: file_transactions_proto_depIdxs,
		EnumInfos:         file_transactions_proto_enumTypes,
		MessageInfos:      file_transactions_proto_msgTypes,
	}.Build()
	File_transactions_proto = out.File
	file_transactions_proto_goTypes = nil
	file_transactions_proto_depIdxs = nil
}
