// Code generated by MockGen. DO NOT EDIT.
// Source: ./clients/db/sqlc (interfaces: Querier)
//
// Generated by this command:
//
//	mockgen -destination clients/db/sqlc/mocks/querier.go -package mocks ./clients/db/sqlc Querier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sqlc "github.com/I-Frostbyte/rvpay-go/clients/db/sqlc"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// ClientExistsByID mocks base method.
func (m *MockQuerier) ClientExistsByID(ctx context.Context, id uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientExistsByID", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClientExistsByID indicates an expected call of ClientExistsByID.
func (mr *MockQuerierMockRecorder) ClientExistsByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientExistsByID", reflect.TypeOf((*MockQuerier)(nil).ClientExistsByID), ctx, id)
}

// ConsumeOAuthState mocks base method.
func (m *MockQuerier) ConsumeOAuthState(ctx context.Context, state string) (sqlc.OauthState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeOAuthState", ctx, state)
	ret0, _ := ret[0].(sqlc.OauthState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConsumeOAuthState indicates an expected call of ConsumeOAuthState.
func (mr *MockQuerierMockRecorder) ConsumeOAuthState(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeOAuthState", reflect.TypeOf((*MockQuerier)(nil).ConsumeOAuthState), ctx, state)
}

// CountClients mocks base method.
func (m *MockQuerier) CountClients(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountClients", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountClients indicates an expected call of CountClients.
func (mr *MockQuerierMockRecorder) CountClients(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountClients", reflect.TypeOf((*MockQuerier)(nil).CountClients), ctx)
}

// CountIntegrationsByClient mocks base method.
func (m *MockQuerier) CountIntegrationsByClient(ctx context.Context, clientID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountIntegrationsByClient", ctx, clientID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountIntegrationsByClient indicates an expected call of CountIntegrationsByClient.
func (mr *MockQuerierMockRecorder) CountIntegrationsByClient(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountIntegrationsByClient", reflect.TypeOf((*MockQuerier)(nil).CountIntegrationsByClient), ctx, clientID)
}

// CountPlatforms mocks base method.
func (m *MockQuerier) CountPlatforms(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPlatforms", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPlatforms indicates an expected call of CountPlatforms.
func (mr *MockQuerierMockRecorder) CountPlatforms(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPlatforms", reflect.TypeOf((*MockQuerier)(nil).CountPlatforms), ctx)
}

// CountSubAccountsFiltered mocks base method.
func (m *MockQuerier) CountSubAccountsFiltered(ctx context.Context, arg sqlc.CountSubAccountsFilteredParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSubAccountsFiltered", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSubAccountsFiltered indicates an expected call of CountSubAccountsFiltered.
func (mr *MockQuerierMockRecorder) CountSubAccountsFiltered(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSubAccountsFiltered", reflect.TypeOf((*MockQuerier)(nil).CountSubAccountsFiltered), ctx, arg)
}

// CountWebhookSubscriptionsByIntegrationID mocks base method.
func (m *MockQuerier) CountWebhookSubscriptionsByIntegrationID(ctx context.Context, integrationID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountWebhookSubscriptionsByIntegrationID", ctx, integrationID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountWebhookSubscriptionsByIntegrationID indicates an expected call of CountWebhookSubscriptionsByIntegrationID.
func (mr *MockQuerierMockRecorder) CountWebhookSubscriptionsByIntegrationID(ctx, integrationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountWebhookSubscriptionsByIntegrationID", reflect.TypeOf((*MockQuerier)(nil).CountWebhookSubscriptionsByIntegrationID), ctx, integrationID)
}

// CreateClient mocks base method.
func (m *MockQuerier) CreateClient(ctx context.Context, arg sqlc.CreateClientParams) (sqlc.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClient", ctx, arg)
	ret0, _ := ret[0].(sqlc.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateClient indicates an expected call of CreateClient.
func (mr *MockQuerierMockRecorder) CreateClient(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClient", reflect.TypeOf((*MockQuerier)(nil).CreateClient), ctx, arg)
}

// CreateIntegration mocks base method.
func (m *MockQuerier) CreateIntegration(ctx context.Context, arg sqlc.CreateIntegrationParams) (sqlc.Integration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIntegration", ctx, arg)
	ret0, _ := ret[0].(sqlc.Integration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIntegration indicates an expected call of CreateIntegration.
func (mr *MockQuerierMockRecorder) CreateIntegration(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIntegration", reflect.TypeOf((*MockQuerier)(nil).CreateIntegration), ctx, arg)
}

// CreateOAuthState mocks base method.
func (m *MockQuerier) CreateOAuthState(ctx context.Context, arg sqlc.CreateOAuthStateParams) (sqlc.OauthState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOAuthState", ctx, arg)
	ret0, _ := ret[0].(sqlc.OauthState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOAuthState indicates an expected call of CreateOAuthState.
func (mr *MockQuerierMockRecorder) CreateOAuthState(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOAuthState", reflect.TypeOf((*MockQuerier)(nil).CreateOAuthState), ctx, arg)
}

// CreateOAuthToken mocks base method.
func (m *MockQuerier) CreateOAuthToken(ctx context.Context, arg sqlc.CreateOAuthTokenParams) (sqlc.OauthToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOAuthToken", ctx, arg)
	ret0, _ := ret[0].(sqlc.OauthToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOAuthToken indicates an expected call of CreateOAuthToken.
func (mr *MockQuerierMockRecorder) CreateOAuthToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOAuthToken", reflect.TypeOf((*MockQuerier)(nil).CreateOAuthToken), ctx, arg)
}

// CreatePaymentProviderConfig mocks base method.
func (m *MockQuerier) CreatePaymentProviderConfig(ctx context.Context, arg sqlc.CreatePaymentProviderConfigParams) (sqlc.PaymentProviderConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePaymentProviderConfig", ctx, arg)
	ret0, _ := ret[0].(sqlc.PaymentProviderConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePaymentProviderConfig indicates an expected call of CreatePaymentProviderConfig.
func (mr *MockQuerierMockRecorder) CreatePaymentProviderConfig(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePaymentProviderConfig", reflect.TypeOf((*MockQuerier)(nil).CreatePaymentProviderConfig), ctx, arg)
}

// CreatePlatform mocks base method.
func (m *MockQuerier) CreatePlatform(ctx context.Context, arg sqlc.CreatePlatformParams) (sqlc.Platform, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlatform", ctx, arg)
	ret0, _ := ret[0].(sqlc.Platform)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePlatform indicates an expected call of CreatePlatform.
func (mr *MockQuerierMockRecorder) CreatePlatform(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlatform", reflect.TypeOf((*MockQuerier)(nil).CreatePlatform), ctx, arg)
}

// CreateWebhookEvent mocks base method.
func (m *MockQuerier) CreateWebhookEvent(ctx context.Context, arg sqlc.CreateWebhookEventParams) (sqlc.WebhookEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWebhookEvent", ctx, arg)
	ret0, _ := ret[0].(sqlc.WebhookEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWebhookEvent indicates an expected call of CreateWebhookEvent.
func (mr *MockQuerierMockRecorder) CreateWebhookEvent(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWebhookEvent", reflect.TypeOf((*MockQuerier)(nil).CreateWebhookEvent), ctx, arg)
}

// CreateWebhookSubscription mocks base method.
func (m *MockQuerier) CreateWebhookSubscription(ctx context.Context, arg sqlc.CreateWebhookSubscriptionParams) (sqlc.WebhookSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWebhookSubscription", ctx, arg)
	ret0, _ := ret[0].(sqlc.WebhookSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWebhookSubscription indicates an expected call of CreateWebhookSubscription.
func (mr *MockQuerierMockRecorder) CreateWebhookSubscription(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWebhookSubscription", reflect.TypeOf((*MockQuerier)(nil).CreateWebhookSubscription), ctx, arg)
}

// DeleteClient mocks base method.
func (m *MockQuerier) DeleteClient(ctx context.Context, id uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteClient", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteClient indicates an expected call of DeleteClient.
func (mr *MockQuerierMockRecorder) DeleteClient(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteClient", reflect.TypeOf((*MockQuerier)(nil).DeleteClient), ctx, id)
}

// DeleteExpiredOAuthStates mocks base method.
func (m *MockQuerier) DeleteExpiredOAuthStates(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredOAuthStates", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpiredOAuthStates indicates an expected call of DeleteExpiredOAuthStates.
func (mr *MockQuerierMockRecorder) DeleteExpiredOAuthStates(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredOAuthStates", reflect.TypeOf((*MockQuerier)(nil).DeleteExpiredOAuthStates), ctx)
}

// DeleteIntegration mocks base method.
func (m *MockQuerier) DeleteIntegration(ctx context.Context, id uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIntegration", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteIntegration indicates an expected call of DeleteIntegration.
func (mr *MockQuerierMockRecorder) DeleteIntegration(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIntegration", reflect.TypeOf((*MockQuerier)(nil).DeleteIntegration), ctx, id)
}

// DeleteOAuthToken mocks base method.
func (m *MockQuerier) DeleteOAuthToken(ctx context.Context, id uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOAuthToken", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOAuthToken indicates an expected call of DeleteOAuthToken.
func (mr *MockQuerierMockRecorder) DeleteOAuthToken(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOAuthToken", reflect.TypeOf((*MockQuerier)(nil).DeleteOAuthToken), ctx, id)
}

// DeleteOAuthTokenByIntegrationID mocks base method.
func (m *MockQuerier) DeleteOAuthTokenByIntegrationID(ctx context.Context, integrationID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOAuthTokenByIntegrationID", ctx, integrationID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOAuthTokenByIntegrationID indicates an expected call of DeleteOAuthTokenByIntegrationID.
func (mr *MockQuerierMockRecorder) DeleteOAuthTokenByIntegrationID(ctx, integrationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOAuthTokenByIntegrationID", reflect.TypeOf((*MockQuerier)(nil).DeleteOAuthTokenByIntegrationID), ctx, integrationID)
}

// DeletePaymentProviderConfig mocks base method.
func (m *MockQuerier) DeletePaymentProviderConfig(ctx context.Context, integrationID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePaymentProviderConfig", ctx, integrationID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePaymentProviderConfig indicates an expected call of DeletePaymentProviderConfig.
func (mr *MockQuerierMockRecorder) DeletePaymentProviderConfig(ctx, integrationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePaymentProviderConfig", reflect.TypeOf((*MockQuerier)(nil).DeletePaymentProviderConfig), ctx, integrationID)
}

// DeletePlatform mocks base method.
func (m *MockQuerier) DeletePlatform(ctx context.Context, id uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePlatform", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePlatform indicates an expected call of DeletePlatform.
func (mr *MockQuerierMockRecorder) DeletePlatform(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePlatform", reflect.TypeOf((*MockQuerier)(nil).DeletePlatform), ctx, id)
}

// DeleteWebhookSubscription mocks base method.
func (m *MockQuerier) DeleteWebhookSubscription(ctx context.Context, id uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWebhookSubscription", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteWebhookSubscription indicates an expected call of DeleteWebhookSubscription.
func (mr *MockQuerierMockRecorder) DeleteWebhookSubscription(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWebhookSubscription", reflect.TypeOf((*MockQuerier)(nil).DeleteWebhookSubscription), ctx, id)
}

// GetClientByID mocks base method.
func (m *MockQuerier) GetClientByID(ctx context.Context, id uuid.UUID) (sqlc.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientByID", ctx, id)
	ret0, _ := ret[0].(sqlc.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientByID indicates an expected call of GetClientByID.
func (mr *MockQuerierMockRecorder) GetClientByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientByID", reflect.TypeOf((*MockQuerier)(nil).GetClientByID), ctx, id)
}

// GetClientByName mocks base method.
func (m *MockQuerier) GetClientByName(ctx context.Context, clientName string) (sqlc.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientByName", ctx, clientName)
	ret0, _ := ret[0].(sqlc.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientByName indicates an expected call of GetClientByName.
func (mr *MockQuerierMockRecorder) GetClientByName(ctx, clientName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientByName", reflect.TypeOf((*MockQuerier)(nil).GetClientByName), ctx, clientName)
}

// GetIntegrationByClientAndPlatform mocks base method.
func (m *MockQuerier) GetIntegrationByClientAndPlatform(ctx context.Context, arg sqlc.GetIntegrationByClientAndPlatformParams) (sqlc.Integration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIntegrationByClientAndPlatform", ctx, arg)
	ret0, _ := ret[0].(sqlc.Integration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIntegrationByClientAndPlatform indicates an expected call of GetIntegrationByClientAndPlatform.
func (mr *MockQuerierMockRecorder) GetIntegrationByClientAndPlatform(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIntegrationByClientAndPlatform", reflect.TypeOf((*MockQuerier)(nil).GetIntegrationByClientAndPlatform), ctx, arg)
}

// GetIntegrationByExternalAccountID mocks base method.
func (m *MockQuerier) GetIntegrationByExternalAccountID(ctx context.Context, externalAccountID string) (sqlc.Integration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIntegrationByExternalAccountID", ctx, externalAccountID)
	ret0, _ := ret[0].(sqlc.Integration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIntegrationByExternalAccountID indicates an expected call of GetIntegrationByExternalAccountID.
func (mr *MockQuerierMockRecorder) GetIntegrationByExternalAccountID(ctx, externalAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIntegrationByExternalAccountID", reflect.TypeOf((*MockQuerier)(nil).GetIntegrationByExternalAccountID), ctx, externalAccountID)
}

// GetIntegrationByID mocks base method.
func (m *MockQuerier) GetIntegrationByID(ctx context.Context, id uuid.UUID) (sqlc.Integration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIntegrationByID", ctx, id)
	ret0, _ := ret[0].(sqlc.Integration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIntegrationByID indicates an expected call of GetIntegrationByID.
func (mr *MockQuerierMockRecorder) GetIntegrationByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIntegrationByID", reflect.TypeOf((*MockQuerier)(nil).GetIntegrationByID), ctx, id)
}

// GetOAuthStateByState mocks base method.
func (m *MockQuerier) GetOAuthStateByState(ctx context.Context, state string) (sqlc.OauthState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOAuthStateByState", ctx, state)
	ret0, _ := ret[0].(sqlc.OauthState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOAuthStateByState indicates an expected call of GetOAuthStateByState.
func (mr *MockQuerierMockRecorder) GetOAuthStateByState(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOAuthStateByState", reflect.TypeOf((*MockQuerier)(nil).GetOAuthStateByState), ctx, state)
}

// GetOAuthTokenByID mocks base method.
func (m *MockQuerier) GetOAuthTokenByID(ctx context.Context, id uuid.UUID) (sqlc.OauthToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOAuthTokenByID", ctx, id)
	ret0, _ := ret[0].(sqlc.OauthToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOAuthTokenByID indicates an expected call of GetOAuthTokenByID.
func (mr *MockQuerierMockRecorder) GetOAuthTokenByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOAuthTokenByID", reflect.TypeOf((*MockQuerier)(nil).GetOAuthTokenByID), ctx, id)
}

// GetOAuthTokenByIntegrationID mocks base method.
func (m *MockQuerier) GetOAuthTokenByIntegrationID(ctx context.Context, integrationID uuid.UUID) (sqlc.OauthToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOAuthTokenByIntegrationID", ctx, integrationID)
	ret0, _ := ret[0].(sqlc.OauthToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOAuthTokenByIntegrationID indicates an expected call of GetOAuthTokenByIntegrationID.
func (mr *MockQuerierMockRecorder) GetOAuthTokenByIntegrationID(ctx, integrationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOAuthTokenByIntegrationID", reflect.TypeOf((*MockQuerier)(nil).GetOAuthTokenByIntegrationID), ctx, integrationID)
}

// GetPaymentProviderConfigByAPIKey mocks base method.
func (m *MockQuerier) GetPaymentProviderConfigByAPIKey(ctx context.Context, providerApiKey string) (sqlc.PaymentProviderConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentProviderConfigByAPIKey", ctx, providerApiKey)
	ret0, _ := ret[0].(sqlc.PaymentProviderConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentProviderConfigByAPIKey indicates an expected call of GetPaymentProviderConfigByAPIKey.
func (mr *MockQuerierMockRecorder) GetPaymentProviderConfigByAPIKey(ctx, providerApiKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentProviderConfigByAPIKey", reflect.TypeOf((*MockQuerier)(nil).GetPaymentProviderConfigByAPIKey), ctx, providerApiKey)
}

// GetPaymentProviderConfigByIntegrationID mocks base method.
func (m *MockQuerier) GetPaymentProviderConfigByIntegrationID(ctx context.Context, integrationID uuid.UUID) (sqlc.PaymentProviderConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentProviderConfigByIntegrationID", ctx, integrationID)
	ret0, _ := ret[0].(sqlc.PaymentProviderConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentProviderConfigByIntegrationID indicates an expected call of GetPaymentProviderConfigByIntegrationID.
func (mr *MockQuerierMockRecorder) GetPaymentProviderConfigByIntegrationID(ctx, integrationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentProviderConfigByIntegrationID", reflect.TypeOf((*MockQuerier)(nil).GetPaymentProviderConfigByIntegrationID), ctx, integrationID)
}

// GetPaymentProviderConfigByLocationID mocks base method.
func (m *MockQuerier) GetPaymentProviderConfigByLocationID(ctx context.Context, locationID string) (sqlc.PaymentProviderConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentProviderConfigByLocationID", ctx, locationID)
	ret0, _ := ret[0].(sqlc.PaymentProviderConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentProviderConfigByLocationID indicates an expected call of GetPaymentProviderConfigByLocationID.
func (mr *MockQuerierMockRecorder) GetPaymentProviderConfigByLocationID(ctx, locationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentProviderConfigByLocationID", reflect.TypeOf((*MockQuerier)(nil).GetPaymentProviderConfigByLocationID), ctx, locationID)
}

// GetPlatformByID mocks base method.
func (m *MockQuerier) GetPlatformByID(ctx context.Context, id uuid.UUID) (sqlc.Platform, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlatformByID", ctx, id)
	ret0, _ := ret[0].(sqlc.Platform)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlatformByID indicates an expected call of GetPlatformByID.
func (mr *MockQuerierMockRecorder) GetPlatformByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlatformByID", reflect.TypeOf((*MockQuerier)(nil).GetPlatformByID), ctx, id)
}

// GetPlatformByName mocks base method.
func (m *MockQuerier) GetPlatformByName(ctx context.Context, name string) (sqlc.Platform, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlatformByName", ctx, name)
	ret0, _ := ret[0].(sqlc.Platform)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlatformByName indicates an expected call of GetPlatformByName.
func (mr *MockQuerierMockRecorder) GetPlatformByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlatformByName", reflect.TypeOf((*MockQuerier)(nil).GetPlatformByName), ctx, name)
}

// GetPlatformBySlug mocks base method.
func (m *MockQuerier) GetPlatformBySlug(ctx context.Context, slug string) (sqlc.Platform, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlatformBySlug", ctx, slug)
	ret0, _ := ret[0].(sqlc.Platform)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlatformBySlug indicates an expected call of GetPlatformBySlug.
func (mr *MockQuerierMockRecorder) GetPlatformBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlatformBySlug", reflect.TypeOf((*MockQuerier)(nil).GetPlatformBySlug), ctx, slug)
}

// GetWebhookEventByIntegrationAndProvider mocks base method.
func (m *MockQuerier) GetWebhookEventByIntegrationAndProvider(ctx context.Context, arg sqlc.GetWebhookEventByIntegrationAndProviderParams) (sqlc.WebhookEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhookEventByIntegrationAndProvider", ctx, arg)
	ret0, _ := ret[0].(sqlc.WebhookEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebhookEventByIntegrationAndProvider indicates an expected call of GetWebhookEventByIntegrationAndProvider.
func (mr *MockQuerierMockRecorder) GetWebhookEventByIntegrationAndProvider(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhookEventByIntegrationAndProvider", reflect.TypeOf((*MockQuerier)(nil).GetWebhookEventByIntegrationAndProvider), ctx, arg)
}

// GetWebhookSubscriptionByID mocks base method.
func (m *MockQuerier) GetWebhookSubscriptionByID(ctx context.Context, id uuid.UUID) (sqlc.WebhookSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhookSubscriptionByID", ctx, id)
	ret0, _ := ret[0].(sqlc.WebhookSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebhookSubscriptionByID indicates an expected call of GetWebhookSubscriptionByID.
func (mr *MockQuerierMockRecorder) GetWebhookSubscriptionByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhookSubscriptionByID", reflect.TypeOf((*MockQuerier)(nil).GetWebhookSubscriptionByID), ctx, id)
}

// GetWebhookSubscriptionByIntegrationIDAndEndpoint mocks base method.
func (m *MockQuerier) GetWebhookSubscriptionByIntegrationIDAndEndpoint(ctx context.Context, arg sqlc.GetWebhookSubscriptionByIntegrationIDAndEndpointParams) (sqlc.WebhookSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhookSubscriptionByIntegrationIDAndEndpoint", ctx, arg)
	ret0, _ := ret[0].(sqlc.WebhookSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebhookSubscriptionByIntegrationIDAndEndpoint indicates an expected call of GetWebhookSubscriptionByIntegrationIDAndEndpoint.
func (mr *MockQuerierMockRecorder) GetWebhookSubscriptionByIntegrationIDAndEndpoint(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhookSubscriptionByIntegrationIDAndEndpoint", reflect.TypeOf((*MockQuerier)(nil).GetWebhookSubscriptionByIntegrationIDAndEndpoint), ctx, arg)
}

// IntegrationExistsByClientAndPlatform mocks base method.
func (m *MockQuerier) IntegrationExistsByClientAndPlatform(ctx context.Context, arg sqlc.IntegrationExistsByClientAndPlatformParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntegrationExistsByClientAndPlatform", ctx, arg)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IntegrationExistsByClientAndPlatform indicates an expected call of IntegrationExistsByClientAndPlatform.
func (mr *MockQuerierMockRecorder) IntegrationExistsByClientAndPlatform(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntegrationExistsByClientAndPlatform", reflect.TypeOf((*MockQuerier)(nil).IntegrationExistsByClientAndPlatform), ctx, arg)
}

// ListActiveClients mocks base method.
func (m *MockQuerier) ListActiveClients(ctx context.Context, arg sqlc.ListActiveClientsParams) ([]sqlc.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveClients", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveClients indicates an expected call of ListActiveClients.
func (mr *MockQuerierMockRecorder) ListActiveClients(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveClients", reflect.TypeOf((*MockQuerier)(nil).ListActiveClients), ctx, arg)
}

// ListActiveIntegrationsByClient mocks base method.
func (m *MockQuerier) ListActiveIntegrationsByClient(ctx context.Context, arg sqlc.ListActiveIntegrationsByClientParams) ([]sqlc.Integration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveIntegrationsByClient", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Integration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveIntegrationsByClient indicates an expected call of ListActiveIntegrationsByClient.
func (mr *MockQuerierMockRecorder) ListActiveIntegrationsByClient(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveIntegrationsByClient", reflect.TypeOf((*MockQuerier)(nil).ListActiveIntegrationsByClient), ctx, arg)
}

// ListActiveWebhookSubscriptionsByIntegrationID mocks base method.
func (m *MockQuerier) ListActiveWebhookSubscriptionsByIntegrationID(ctx context.Context, integrationID uuid.UUID) ([]sqlc.WebhookSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveWebhookSubscriptionsByIntegrationID", ctx, integrationID)
	ret0, _ := ret[0].([]sqlc.WebhookSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveWebhookSubscriptionsByIntegrationID indicates an expected call of ListActiveWebhookSubscriptionsByIntegrationID.
func (mr *MockQuerierMockRecorder) ListActiveWebhookSubscriptionsByIntegrationID(ctx, integrationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveWebhookSubscriptionsByIntegrationID", reflect.TypeOf((*MockQuerier)(nil).ListActiveWebhookSubscriptionsByIntegrationID), ctx, integrationID)
}

// ListClients mocks base method.
func (m *MockQuerier) ListClients(ctx context.Context, arg sqlc.ListClientsParams) ([]sqlc.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClients", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClients indicates an expected call of ListClients.
func (mr *MockQuerierMockRecorder) ListClients(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClients", reflect.TypeOf((*MockQuerier)(nil).ListClients), ctx, arg)
}

// ListEnabledPlatforms mocks base method.
func (m *MockQuerier) ListEnabledPlatforms(ctx context.Context, arg sqlc.ListEnabledPlatformsParams) ([]sqlc.Platform, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnabledPlatforms", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Platform)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnabledPlatforms indicates an expected call of ListEnabledPlatforms.
func (mr *MockQuerierMockRecorder) ListEnabledPlatforms(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnabledPlatforms", reflect.TypeOf((*MockQuerier)(nil).ListEnabledPlatforms), ctx, arg)
}

// ListIntegrationsByClient mocks base method.
func (m *MockQuerier) ListIntegrationsByClient(ctx context.Context, arg sqlc.ListIntegrationsByClientParams) ([]sqlc.Integration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIntegrationsByClient", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Integration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIntegrationsByClient indicates an expected call of ListIntegrationsByClient.
func (mr *MockQuerierMockRecorder) ListIntegrationsByClient(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIntegrationsByClient", reflect.TypeOf((*MockQuerier)(nil).ListIntegrationsByClient), ctx, arg)
}

// ListIntegrationsByPlatform mocks base method.
func (m *MockQuerier) ListIntegrationsByPlatform(ctx context.Context, arg sqlc.ListIntegrationsByPlatformParams) ([]sqlc.Integration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIntegrationsByPlatform", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Integration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIntegrationsByPlatform indicates an expected call of ListIntegrationsByPlatform.
func (mr *MockQuerierMockRecorder) ListIntegrationsByPlatform(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIntegrationsByPlatform", reflect.TypeOf((*MockQuerier)(nil).ListIntegrationsByPlatform), ctx, arg)
}

// ListPlatforms mocks base method.
func (m *MockQuerier) ListPlatforms(ctx context.Context, arg sqlc.ListPlatformsParams) ([]sqlc.Platform, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPlatforms", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Platform)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPlatforms indicates an expected call of ListPlatforms.
func (mr *MockQuerierMockRecorder) ListPlatforms(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPlatforms", reflect.TypeOf((*MockQuerier)(nil).ListPlatforms), ctx, arg)
}

// ListSubAccountsFiltered mocks base method.
func (m *MockQuerier) ListSubAccountsFiltered(ctx context.Context, arg sqlc.ListSubAccountsFilteredParams) ([]sqlc.ListSubAccountsFilteredRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubAccountsFiltered", ctx, arg)
	ret0, _ := ret[0].([]sqlc.ListSubAccountsFilteredRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubAccountsFiltered indicates an expected call of ListSubAccountsFiltered.
func (mr *MockQuerierMockRecorder) ListSubAccountsFiltered(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubAccountsFiltered", reflect.TypeOf((*MockQuerier)(nil).ListSubAccountsFiltered), ctx, arg)
}

// ListWebhookSubscriptionsByIntegrationID mocks base method.
func (m *MockQuerier) ListWebhookSubscriptionsByIntegrationID(ctx context.Context, arg sqlc.ListWebhookSubscriptionsByIntegrationIDParams) ([]sqlc.WebhookSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWebhookSubscriptionsByIntegrationID", ctx, arg)
	ret0, _ := ret[0].([]sqlc.WebhookSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWebhookSubscriptionsByIntegrationID indicates an expected call of ListWebhookSubscriptionsByIntegrationID.
func (mr *MockQuerierMockRecorder) ListWebhookSubscriptionsByIntegrationID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWebhookSubscriptionsByIntegrationID", reflect.TypeOf((*MockQuerier)(nil).ListWebhookSubscriptionsByIntegrationID), ctx, arg)
}

// OAuthTokenExistsByIntegrationID mocks base method.
func (m *MockQuerier) OAuthTokenExistsByIntegrationID(ctx context.Context, integrationID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OAuthTokenExistsByIntegrationID", ctx, integrationID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OAuthTokenExistsByIntegrationID indicates an expected call of OAuthTokenExistsByIntegrationID.
func (mr *MockQuerierMockRecorder) OAuthTokenExistsByIntegrationID(ctx, integrationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OAuthTokenExistsByIntegrationID", reflect.TypeOf((*MockQuerier)(nil).OAuthTokenExistsByIntegrationID), ctx, integrationID)
}

// PlatformExistsBySlug mocks base method.
func (m *MockQuerier) PlatformExistsBySlug(ctx context.Context, slug string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlatformExistsBySlug", ctx, slug)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlatformExistsBySlug indicates an expected call of PlatformExistsBySlug.
func (mr *MockQuerierMockRecorder) PlatformExistsBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlatformExistsBySlug", reflect.TypeOf((*MockQuerier)(nil).PlatformExistsBySlug), ctx, slug)
}

// UpdateClientStatus mocks base method.
func (m *MockQuerier) UpdateClientStatus(ctx context.Context, arg sqlc.UpdateClientStatusParams) (sqlc.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateClientStatus", ctx, arg)
	ret0, _ := ret[0].(sqlc.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateClientStatus indicates an expected call of UpdateClientStatus.
func (mr *MockQuerierMockRecorder) UpdateClientStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateClientStatus", reflect.TypeOf((*MockQuerier)(nil).UpdateClientStatus), ctx, arg)
}

// UpdateIntegrationLastSyncAt mocks base method.
func (m *MockQuerier) UpdateIntegrationLastSyncAt(ctx context.Context, arg sqlc.UpdateIntegrationLastSyncAtParams) (sqlc.Integration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIntegrationLastSyncAt", ctx, arg)
	ret0, _ := ret[0].(sqlc.Integration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateIntegrationLastSyncAt indicates an expected call of UpdateIntegrationLastSyncAt.
func (mr *MockQuerierMockRecorder) UpdateIntegrationLastSyncAt(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIntegrationLastSyncAt", reflect.TypeOf((*MockQuerier)(nil).UpdateIntegrationLastSyncAt), ctx, arg)
}

// UpdateIntegrationStatus mocks base method.
func (m *MockQuerier) UpdateIntegrationStatus(ctx context.Context, arg sqlc.UpdateIntegrationStatusParams) (sqlc.Integration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIntegrationStatus", ctx, arg)
	ret0, _ := ret[0].(sqlc.Integration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateIntegrationStatus indicates an expected call of UpdateIntegrationStatus.
func (mr *MockQuerierMockRecorder) UpdateIntegrationStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIntegrationStatus", reflect.TypeOf((*MockQuerier)(nil).UpdateIntegrationStatus), ctx, arg)
}

// UpdateOAuthToken mocks base method.
func (m *MockQuerier) UpdateOAuthToken(ctx context.Context, arg sqlc.UpdateOAuthTokenParams) (sqlc.OauthToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOAuthToken", ctx, arg)
	ret0, _ := ret[0].(sqlc.OauthToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOAuthToken indicates an expected call of UpdateOAuthToken.
func (mr *MockQuerierMockRecorder) UpdateOAuthToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOAuthToken", reflect.TypeOf((*MockQuerier)(nil).UpdateOAuthToken), ctx, arg)
}

// UpdatePaymentProviderConfig mocks base method.
func (m *MockQuerier) UpdatePaymentProviderConfig(ctx context.Context, arg sqlc.UpdatePaymentProviderConfigParams) (sqlc.PaymentProviderConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePaymentProviderConfig", ctx, arg)
	ret0, _ := ret[0].(sqlc.PaymentProviderConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePaymentProviderConfig indicates an expected call of UpdatePaymentProviderConfig.
func (mr *MockQuerierMockRecorder) UpdatePaymentProviderConfig(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePaymentProviderConfig", reflect.TypeOf((*MockQuerier)(nil).UpdatePaymentProviderConfig), ctx, arg)
}

// UpdatePlatform mocks base method.
func (m *MockQuerier) UpdatePlatform(ctx context.Context, arg sqlc.UpdatePlatformParams) (sqlc.Platform, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlatform", ctx, arg)
	ret0, _ := ret[0].(sqlc.Platform)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePlatform indicates an expected call of UpdatePlatform.
func (mr *MockQuerierMockRecorder) UpdatePlatform(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlatform", reflect.TypeOf((*MockQuerier)(nil).UpdatePlatform), ctx, arg)
}

// UpdateWebhookSubscriptionLastDelivery mocks base method.
func (m *MockQuerier) UpdateWebhookSubscriptionLastDelivery(ctx context.Context, arg sqlc.UpdateWebhookSubscriptionLastDeliveryParams) (sqlc.WebhookSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWebhookSubscriptionLastDelivery", ctx, arg)
	ret0, _ := ret[0].(sqlc.WebhookSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWebhookSubscriptionLastDelivery indicates an expected call of UpdateWebhookSubscriptionLastDelivery.
func (mr *MockQuerierMockRecorder) UpdateWebhookSubscriptionLastDelivery(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWebhookSubscriptionLastDelivery", reflect.TypeOf((*MockQuerier)(nil).UpdateWebhookSubscriptionLastDelivery), ctx, arg)
}

// UpdateWebhookSubscriptionStatus mocks base method.
func (m *MockQuerier) UpdateWebhookSubscriptionStatus(ctx context.Context, arg sqlc.UpdateWebhookSubscriptionStatusParams) (sqlc.WebhookSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWebhookSubscriptionStatus", ctx, arg)
	ret0, _ := ret[0].(sqlc.WebhookSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWebhookSubscriptionStatus indicates an expected call of UpdateWebhookSubscriptionStatus.
func (mr *MockQuerierMockRecorder) UpdateWebhookSubscriptionStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWebhookSubscriptionStatus", reflect.TypeOf((*MockQuerier)(nil).UpdateWebhookSubscriptionStatus), ctx, arg)
}

// WebhookSubscriptionExists mocks base method.
func (m *MockQuerier) WebhookSubscriptionExists(ctx context.Context, arg sqlc.WebhookSubscriptionExistsParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebhookSubscriptionExists", ctx, arg)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WebhookSubscriptionExists indicates an expected call of WebhookSubscriptionExists.
func (mr *MockQuerierMockRecorder) WebhookSubscriptionExists(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebhookSubscriptionExists", reflect.TypeOf((*MockQuerier)(nil).WebhookSubscriptionExists), ctx, arg)
}
